language: node_js
node_js: 14
addons:
  chrome: stable
script:
- npm run lint
- |
  if [ $TRAVIS_PULL_REQUEST != false ] && [ $TRAVIS_SECURE_ENV_VARS == true ]; then
    echo "Pull request with secure environment variables, running Sauce tests...";
    npm run test:polymer:sauce || travis_terminate 1;
  else
    echo "Not a pull request and/or no secure environment variables, running headless tests...";
    npm run test:polymer:local || travis_terminate 1;
  fi
env:
  global:
  - SAUCE_USERNAME: Desire2Learn
  - secure: GIL/5CqfpYMgYIWncuxe0dNJDGBtkcosn6HiUii8zV+I5NjUdVQW4uy8CgfMWE9rYy2mbfPpQ2LXEa9qw7RLVThka7OWScoswre1yMhibwUqpPWtYC6NgajGjk9kqOdB0XrTprvcTpuQJW5gAdPWlR2bXGBxrm70eH+kwxyYHeymJCy8UybYtf7/ipz3DV29t8zWx7PscWR/R2U8ltAOcrj39gnenfUBSQs+3SJ/GPPlOPnrRxzaAO2P1tBNHvfST3bCAK8m6hud6LMxagBLCY4I1+6j2FbOZIyy6Mbqzlmlroodbf7nP77FSA0M/hElbJQGGPu0UhJCbHTucEvewPQBkFAMuA3JObixCGqhEhmJMH1/HIJOGXcLnR0n8ts66gNVcPOKEB9xbkrJAULTydfgqpolPJGVqUdUnk2nkWp1INq4TnfcTjJs7Od029PFACsKR3g9aPjJAm71Zqvxx8W9RBHVm8DnqZf4FHdewrneim2oYup0gdJqYyBsT08FLC8FyXYDhHDhLwUy3T9B5F40pG8qUx3vm6u4lsP7ApkLFWpEfC0O0+Nk0hcDhDbWxEEYnkn6fn6L1IyXCBx1E83ypoaFhLiRChoHpCOois/lNX8fkq+0losQTf8gwLfmU4jm6E9vqaTxmaIS/foMpZBC87dHzfvqR6UorMVzgJM=
