tinymce.addI18n('ar_SA',{
"Cut": "قص",
"Heading 5": "العنوان 5",
"Header 2": "الرأس 2",
"Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X\/C\/V keyboard shortcuts instead.": "لا يدعم مستعرضك الوصول المباشر إلى الحافظة. يرجى استخدام اختصارات لوحة المفاتيح Ctrl+X\/C\/V بدلاً من ذلك.",
"Heading 4": "العنوان 4",
"Div": "Div",
"Heading 2": "العنوان 2",
"Paste": "لصق",
"Close": "إغلاق",
"Font Family": "عائلة الخطوط",
"Pre": "قبل",
"Align Right": "محاذاة لليمين",
"New document": "مستند جديد",
"Blockquote": "Blockquote",
"Numbered list": "لائحة رقمية",
"Heading 1": "العنوان 1",
"Headings": "العناوين",
"Increase indent": "زيادة المسافة البادئة",
"Formats": "التنسيقات",
"Headers": "الرؤوس",
"Select all": "تحديد الكل",
"Header 3": "الرأس 3",
"Blocks": "حظورات",
"Undo": "تراجع",
"Strikethrough": "يتوسطه خط",
"Bullet list": "لائحة نقطية",
"Header 1": "الرأس 1",
"Superscript": "مرتفع",
"Clear formatting": "مسح التنسيق",
"Font Sizes": "أحجام الخط",
"Subscript": "منخفض",
"Header 6": "الرأس 6",
"Redo": "إعادة",
"Paragraph": "فقرة",
"Ok": "موافق",
"Bold": "غامق",
"Code": "الكود",
"Italic": "مائل",
"Align Center": "محاذاة للوسط",
"Header 5": "الرأس 5",
"Heading 6": "العنوان 6",
"Heading 3": "العنوان 3",
"Decrease indent": "خفض المسافة البادئة",
"Header 4": "الرأس 4",
"Paste is now in plain text mode. Contents will now be pasted as plain text until you toggle this option off.": "اللصق الآن في وضع النص العادي. سيتم لصق المحتويات الآن كنص عادي إلى أن يتم إيقاف تشغيل هذا الخيار.",
"Underline": "مسطر",
"Cancel": "إلغاء",
"Justify": "ضبط",
"Inline": "مضمن",
"Copy": "نسخ",
"Align Left": "محاذاة لليسار",
"Visual aids": "مساعدات بصرية",
"Lower Greek": "Lower Greek",
"Square": "مربع",
"Default": "افتراضي",
"Lower Alpha": "Lower Alpha",
"Circle": "دائري",
"Disc": "قرص",
"Upper Alpha": "Upper Alpha",
"Upper Roman": "Upper Roman",
"Lower Roman": "Lower Roman",
"Name": "الاسم",
"Anchor": "مثبّت",
"You have unsaved changes are you sure you want to navigate away?": "لديك تغييرات غير محفوظة، هل ترغب بالتأكيد في التنقل خارج الصفحة؟",
"Restore last draft": "استعادة المسودة الأخيرة",
"Special character": "حرف خاص",
"Source code": "رمز المصدر",
"B": "B",
"R": "R",
"G": "G",
"Color": "Colour",
"Right to Left": "من اليمين إلى اليسار",
"Left to Right": "من اليسار إلى اليمين",
"Emoticons": "رموز المشاعر",
"Robots": "روبوتات",
"Document properties": "خصائص المستند",
"Title": "العنوان",
"Keywords": "الكلمات الأساسية",
"Encoding": "الترميز",
"Description": "الوصف",
"Author": "الكاتب",
"Fullscreen": "ملء الشاشة",
"Horizontal line": "خط أفقي",
"Horizontal space": "مسافة أفقية",
"Insert\/edit image": "إدراج\/تحرير الصورة",
"General": "عام",
"Advanced": "خيارات متقدمة",
"Source": "مصدر",
"Border": "الحد",
"Constrain proportions": "تقييد التناسب",
"Vertical space": "مسافة عمودية",
"Image description": "وصف الصورة",
"Style": "النمط",
"Dimensions": "الأبعاد",
"Insert image": "إدراج صورة",
"Zoom in": "تكبير",
"Contrast": "تباين",
"Back": "العودة",
"Gamma": "جاما",
"Flip horizontally": "عكس بشكل أفقي",
"Resize": "تغيير الحجم",
"Sharpen": "زيادة الحدة",
"Zoom out": "تصغير",
"Image options": "خيارات الصورة",
"Apply": "التطبيق",
"Brightness": "السطوع",
"Rotate clockwise": "تدوير باتجاه عقارب الساعة",
"Rotate counterclockwise": "تدوير بعكس اتجاه عقارب الساعة",
"Edit image": "تحرير الصورة",
"Color levels": "مستويات اللون",
"Crop": "اقتصاص",
"Orientation": "الاتجاه",
"Flip vertically": "عكس باتجاه عمودي",
"Invert": "عكس",
"Insert date\/time": "إدراج التاريخ\/الوقت",
"Remove link": "إزالة الارتباط",
"Url": "محدد موقع المعلومات",
"Text to display": "النص لعرضه",
"Anchors": "مثبتات",
"Insert link": "إدراج ارتباط",
"New window": "نافذة جديدة",
"None": "لا شيء",
"The URL you entered seems to be an external link. Do you want to add the required http:\/\/ prefix?": "يبدو محدد موقع المعلومات الذي أدخلته ارتباطًا خارجيًا. هل تريد إضافة البادئة http:\/\/ المطلوبة؟",
"Target": "الهدف",
"The URL you entered seems to be an email address. Do you want to add the required mailto: prefix?": "يبدو موقع محدد المعلومات الذي أدخلته عنوان بريد إلكتروني. هل تريد إضافة البادئة mailto:‎ المطلوبة؟",
"Insert\/edit link": "إدراج/تحرير الارتباط",
"Insert\/edit video": "إدراج/تحرير الفيديو",
"Poster": "منشور",
"Alternative source": "مصدر بديل",
"Paste your embed code below:": "الصق الكود المضمن أدناه:",
"Insert video": "إدراج فيديو",
"Embed": "تضمين",
"Nonbreaking space": "مسافة غير فاصلة",
"Page break": "فاصل الصفحات",
"Paste as text": "اللصق كنص",
"Preview": "معاينة",
"Print": "طباعة",
"Save": "حفظ",
"Could not find the specified string.": "تعذر العثور على السلسلة المحددة.",
"Replace": "استبدال",
"Next": "التالي",
"Whole words": "كلمات كاملة",
"Find and replace": "بحث واستبدال",
"Replace with": "استبدال بـ",
"Find": "بحث",
"Replace all": "استبدال الكل",
"Match case": "مطابقة حالة الأحرف",
"Prev": "السابق",
"Spellcheck": "تدقيق إملائي",
"Finish": "إنهاء",
"Ignore all": "تجاهل الكل",
"Ignore": "تجاهل",
"Add to Dictionary": "إضافة إلى القاموس",
"Insert row before": "إدراج صف قبل",
"Rows": "الصفوف",
"Height": "الارتفاع",
"Paste row after": "لصق صف بعد",
"Alignment": "محاذاة",
"Border color": "لون الحد",
"Column group": "مجموعة الأعمدة",
"Row": "صف",
"Insert column before": "إدراج عمود قبل",
"Split cell": "تقسيم الخلية",
"Cell padding": "نطاق الخلية",
"Cell spacing": "تباعد الخلايا",
"Row type": "نوع الصف",
"Insert table": "إدراج جدول",
"Body": "النص الأساسي",
"Caption": "التسمية التوضيحية",
"Footer": "التذييل",
"Delete row": "حذف صف",
"Paste row before": "لصق صف قبل",
"Scope": "النطاق",
"Delete table": "حذف جدول",
"H Align": "محاذاة أفقية",
"Top": "أعلى",
"Header cell": "خلية الرأس",
"Column": "العمود",
"Row group": "مجموعة الصفوف",
"Cell": "الخلية",
"Middle": "الوسط",
"Cell type": "نوع الخلية",
"Copy row": "نسخ صف",
"Row properties": "خصائص الصف",
"Table properties": "خصائص الجدول",
"Row group": "مجموعة الصفوف",
"Bottom": "أسفل",
"V Align": "محاذاة عمودية",
"Header": "الرأس",
"Right": "يمين",
"Insert column after": "إدراج عمود بعد",
"Cols": "الأعمدة",
"Insert row after": "إدراج صف بعد",
"Width": "العرض",
"Cell properties": "خصائص الخلية",
"Left": "يسار",
"Cut row": "قص صف",
"Delete column": "حذف عمود",
"Center": "توسيط",
"Merge cells": "دمج الخلايا",
"Insert template": "إدراج قالب",
"Templates": "القوالب",
"Background color": "لون الخلفية",
"Custom...": "مخصص...",
"Custom color": "لون مخصص",
"No color": "ما من لون",
"Text color": "لون النص",
"Show blocks": "إظهار الحظورات",
"Show invisible characters": "إظهار الأحرف غير المرئية",
"Words: {0}": "الكلمات: {0}",
"Insert": "إدراج",
"File": "الملف",
"Edit": "تحرير",
"Rich Text Area. Press ALT-F9 for menu. Press ALT-F10 for toolbar. Press ALT-0 for help": "منطقة النص المنسق اضغط على ALT-F10 لشريط الأدوات واضغط على ESC للخروج من شريط الأدوات عندما تكون في داخله.",
"Tools": "الأدوات",
"View": "عرض",
"Table": "الجدول",
"Format": "التنسيق",
"_dir": "rtl"
});
