tinymce.addI18n('da_DK',{
	"Cut": "Klip",
	"Heading 5": "Overskrift 5",
	"Header 2": "Sidehoved 2",
	"Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X/C/V keyboard shortcuts instead.": "Din browser understøtter ikke direkte adgang til udklipsholder. Brug i stedet tastaturgenvejene Ctrl+X/C/V.",
	"Heading 4": "Overskrift 4",
	"Div": "Div",
	"Heading 2": "Overskrift 2",
	"Paste": "Indsæt",
	"Close": "Luk",
	"Font Family": "Skrifttypefamilie",
	"Pre": "Præ",
	"Align Right": "Højrejuster",
	"New document": "Nyt dokument",
	"Blockquote": "Blokanførselstegn",
	"Numbered list": "Nummereret liste",
	"Heading 1": "Overskrift 1",
	"Headings": "Overskrifter",
	"Increase indent": "Forøg indrykning",
	"Formats": "Formater",
	"Headers": "Sidehoveder",
	"Select all": "Vælg alle",
	"Header 3": "Sidehoved 3",
	"Blocks": "Blokke",
	"Undo": "Fortryd",
	"Strikethrough": "Gennemstreget",
	"Bullet list": "Punktliste",
	"Header 1": "Sidehoved 1",
	"Superscript": "Hævet skrift",
	"Clear formatting": "Ryd formatering",
	"Font Sizes": "Skriftstørrelser",
	"Subscript": "Sænket skrift",
	"Header 6": "Sidehoved 6",
	"Redo": "Annuller fortryd",
	"Paragraph": "Afsnit",
	"Ok": "Ok",
	"Bold": "Fed",
	"Code": "Kode",
	"Italic": "Kursiv",
	"Align Center": "Centrer",
	"Header 5": "Sidehoved 5",
	"Heading 6": "Overskrift 6",
	"Heading 3": "Overskrift 3",
	"Decrease indent": "Formindsk indrykning",
	"Header 4": "Sidehoved 4",
	"Paste is now in plain text mode. Contents will now be pasted as plain text until you toggle this option off.": "Indsæt er nu i almindelig teksttilstand. Indholdet vil nu blive indsat som almindelig tekst, indtil du slår denne funktion fra.",
	"Underline": "Understreg",
	"Cancel": "Annuller",
	"Justify": "Lige margener",
	"Inline": "Indbygget",
	"Copy": "Kopiér",
	"Align Left": "Venstrejuster",
	"Visual aids": "Visuelle hjælpemidler",
	"Lower Greek": "Græske bogstaver, små",
	"Square": "Firkant",
	"Default": "Standard",
	"Lower Alpha": "Små bogstaver",
	"Circle": "Cirkel",
	"Disc": "Disk",
	"Upper Alpha": "Store bogstaver",
	"Upper Roman": "Antikva, store",
	"Lower Roman": "Antikva, små",
	"Name": "Navn",
	"Anchor": "Forankring",
	"You have unsaved changes are you sure you want to navigate away?": "Du har foretaget ændringer uden at gemme. Er du sikker på, at du vil navigere væk?",
	"Restore last draft": "Gendan sidste kladde",
	"Special character": "Specialtegn",
	"Source code": "Kildekode",
	"B": "B",
	"R": "R",
	"G": "G",
	"Color": "Farve",
	"Right to Left": "Højre til venstre",
	"Left to Right": "Venstre til højre",
	"Emoticons": "Humørikoner",
	"Robots": "Robotter",
	"Document properties": "Dokumentegenskaber",
	"Title": "Titel",
	"Keywords": "Nøgleord",
	"Encoding": "Kodning",
	"Description": "Beskrivelse",
	"Author": "Forfatter",
	"Fullscreen": "Fuld skærm",
	"Horizontal line": "Vandret linje",
	"Horizontal space": "Vandret mellemrum",
	"Insert/edit image": "Indsæt/rediger billede",
	"General": "Generel",
	"Advanced": "Avanceret",
	"Source": "Kilde",
	"Border": "Kant",
	"Constrain proportions": "Begræns proportioner",
	"Vertical space": "Lodret mellemrum",
	"Image description": "Billedbeskrivelse",
	"Style": "Typografi",
	"Dimensions": "Størrelse",
	"Insert image": "Indsæt billede",
	"Zoom in": "Zoom ind",
	"Contrast": "Kontrast",
	"Back": "Tilbage",
	"Gamma": "Gamma",
	"Flip horizontally": "Spejlvend vandret",
	"Resize": "Tilpas størrelse",
	"Sharpen": "Gør skarpere",
	"Zoom out": "Zoom ud",
	"Image options": "Billedindstillinger",
	"Apply": "Anvend",
	"Brightness": "Lysstyrke",
	"Rotate clockwise": "Drej med uret",
	"Rotate counterclockwise": "Drej mod uret",
	"Edit image": "Rediger billede",
	"Color levels": "Farveniveauer",
	"Crop": "Beskær",
	"Orientation": "Retning",
	"Flip vertically": "Spejlvend lodret",
	"Invert": "Inverter",
	"Insert date/time": "Indsæt dato/tid",
	"Remove link": "Fjern link",
	"Url": "URL-adresse",
	"Text to display": "Tekst, der skal vises",
	"Anchors": "Forankringer",
	"Insert link": "Indsæt link",
	"New window": "Nyt vindue",
	"None": "Ingen",
	"The URL you entered seems to be an external link. Do you want to add the required http:// prefix?": "Den angivne URL-adresse er tilsyneladende et eksternt link. Vil du tilføje det påkrævede præfiks http://?",
	"Target": "Mål",
	"The URL you entered seems to be an email address. Do you want to add the required mailto: prefix?": "Den angivne URL-adresse er tilsyneladende en e-mailadresse. Vil du tilføje det påkrævede præfiks mailto:?",
	"Insert/edit link": "Indsæt/rediger link",
	"Insert/edit video": "Indsæt/rediger video",
	"Poster": "Plakat",
	"Alternative source": "Alternativ kilde",
	"Paste your embed code below:": "Indsæt din indlejringskode nedenfor:",
	"Insert video": "Indsæt video",
	"Embed": "Indlejr",
	"Nonbreaking space": "Hårdt mellemrum",
	"Page break": "Sideskift",
	"Paste as text": "Indsæt som tekst",
	"Preview": "Forhåndsvisning",
	"Print": "Udskriv",
	"Save": "Gem",
	"Could not find the specified string.": "Kunne ikke finde den angivne streng.",
	"Replace": "Erstat",
	"Next": "Næste",
	"Whole words": "Hele ord",
	"Find and replace": "Søg og erstat",
	"Replace with": "Erstat med",
	"Find": "Søg",
	"Replace all": "Erstat alle",
	"Match case": "Forskel på store og små bogstaver",
	"Prev": "Tidligere",
	"Spellcheck": "Stavekontrol",
	"Finish": "Afslut",
	"Ignore all": "Ignorer alle",
	"Ignore": "Ignorer",
	"Add to Dictionary": "Føj til ordbog",
	"Insert row before": "Indsæt række før",
	"Rows": "Rækker",
	"Height": "Højde",
	"Paste row after": "Indsæt række efter",
	"Alignment": "Justering",
	"Border color": "Kantfarve",
	"Column group": "Kolonnegruppe",
	"Row": "Række",
	"Insert column before": "Indsæt kolonne før",
	"Split cell": "Opdel celle",
	"Cell padding": "Cellemargen",
	"Cell spacing": "Celleafstand",
	"Row type": "Rækketype",
	"Insert table": "Indsæt tabel",
	"Body": "Brødtekst",
	"Caption": "Billedtekst",
	"Footer": "Sidefod",
	"Delete row": "Slet række",
	"Paste row before": "Indsæt række før",
	"Scope": "Omfang",
	"Delete table": "Slet tabel",
	"H Align": "H juster",
	"Top": "Øverst",
	"Header cell": "Tabelhovedcelle",
	"Column": "Kolonne",
	"Row group": "Rækkegruppe",
	"Cell": "Celle",
	"Middle": "Midterst",
	"Cell type": "Celletype",
	"Copy row": "Kopiér række",
	"Row properties": "Egenskaber for række",
	"Table properties": "Egenskaber for tabel",
	"Bottom": "Nederst",
	"V Align": "V juster",
	"Header": "Sidehoved",
	"Right": "Højre",
	"Insert column after": "Indsæt kolonne efter",
	"Cols": "Kolonner",
	"Insert row after": "Indsæt række efter",
	"Width": "Bredde",
	"Cell properties": "Egenskaber for celle",
	"Left": "Venstre",
	"Cut row": "Klip række",
	"Delete column": "Slet kolonne",
	"Center": "Centrer",
	"Merge cells": "Flet celler",
	"Insert template": "Indsæt skabelon",
	"Templates": "Skabeloner",
	"Background color": "Baggrundsfarve",
	"Custom...": "Brugerdefineret...",
	"Custom color": "Brugerdefineret farve",
	"No color": "Ingen farve",
	"Text color": "Tekstfarve",
	"Show blocks": "Vis blokke",
	"Show invisible characters": "Vis usynlige tegn",
	"Words: {0}": "Ord: {0}",
	"Insert": "Indsæt",
	"File": "Fil",
	"Edit": "Rediger",
	"Rich Text Area. Press ALT-F9 for menu. Press ALT-F10 for toolbar. Press ALT-0 for help": "RTF-område. Tryk på ALT-F9 for at se menuen. Tryk på ALT-F10 for at se værktøjslinjen. Tryk på ALT-0 for at få hjælp",
	"Tools": "Værktøjer",
	"View": "Vis",
	"Table": "Tabel",
	"Format": "Format"
});
