tinymce.addI18n('de_DE',{
"Cut": "Ausschneiden",
"Heading 5": "Überschrift 5",
"Header 2": "Kopfzeile 2",
"Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X\/C\/V keyboard shortcuts instead.": "Ihr Browser unterstützt keinen Direktzugriff auf die Zwischenablage. Verwenden Sie stattdessen die Tastenkürzel Strg+X\/C\/V.",
"Heading 4": "Überschrift 4",
"Div": "Div",
"Heading 2": "Überschrift 2",
"Paste": "Einfügen",
"Close": "Schließen",
"Font Family": "Schriftfamilie",
"Pre": "Vorformatiert",
"Align Right": "Rechtsbündig",
"New document": "Neues Dokument",
"Blockquote": "Blockquote",
"Numbered list": "Nummerierte Liste",
"Heading 1": "Überschrift 1",
"Headings": "Überschriften",
"Increase indent": "Einzug vergrößern",
"Formats": "Formate",
"Headers": "Kopfzeile",
"Select all": "Alle auswählen",
"Header 3": "Überschrift 3",
"Blocks": "Blocks",
"Undo": "Rückgängig",
"Strikethrough": "Durchgestrichen",
"Bullet list": "Aufzählung",
"Header 1": "Überschrift 1",
"Superscript": "Hochgestellt",
"Clear formatting": "Formatierung löschen",
"Font Sizes": "Schriftgrößen",
"Subscript": "Tiefgestellt",
"Header 6": "Kopfzeile 6",
"Redo": "Wiederholen",
"Paragraph": "Absatz",
"Ok": "OK",
"Bold": "Fett",
"Code": "Code",
"Italic": "Kursiv",
"Align Center": "Zentrieren",
"Header 5": "Kopfzeile 5",
"Heading 6": "Überschrift 6",
"Heading 3": "Überschrift 3",
"Decrease indent": "Einzug verringern",
"Header 4": "Kopfzeile 4",
"Paste is now in plain text mode. Contents will now be pasted as plain text until you toggle this option off.": "Einfügen im Modus „einfacher Text“. Inhalte werden als einfacher Text eingefügt, bis Sie diese Option deaktivieren.",
"Underline": "Unterstreichen",
"Cancel": "Abbrechen",
"Justify": "Blocksatz",
"Inline": "Inline",
"Copy": "Kopieren",
"Align Left": "Linksbündig",
"Visual aids": "Sehhilfen",
"Lower Greek": "Griechisch klein",
"Square": "Quadrat",
"Default": "Standard",
"Lower Alpha": "Alpha klein",
"Circle": "Kreis",
"Disc": "Scheibe",
"Upper Alpha": "Alpha groß",
"Upper Roman": "Römisch groß",
"Lower Roman": "Römisch groß",
"Name": "Name",
"Anchor": "Festpunkt",
"You have unsaved changes are you sure you want to navigate away?": "Sie haben ungespeicherte Änderungen. Möchten Sie die Seite wirklich verlassen?",
"Restore last draft": "Letzten Entwurf wiederherstellen",
"Special character": "Sonderzeichen",
"Source code": "Quellcode",
"B": "B",
"R": "R",
"G": "G",
"Color": "Farbe",
"Right to Left": "Rechts nach links",
"Left to Right": "Links nach rechts",
"Emoticons": "Emoticons",
"Robots": "Roboter",
"Document properties": "Dokumenteneigenschaften",
"Title": "Titel",
"Keywords": "Schlüsselwörter",
"Encoding": "Encodierung",
"Description": "Beschreibung",
"Author": "Verfasser",
"Fullscreen": "Vollbildmodus",
"Horizontal line": "Horizontale Linie",
"Horizontal space": "Horizontaler Abstand",
"Insert\/edit image": "Bild einfügen\/bearbeiten",
"General": "Allgemein",
"Advanced": "Erweitert",
"Source": "Quelle",
"Border": "Rahmen",
"Constrain proportions": "Proportionen behalten",
"Vertical space": "Vertikaler Abstand",
"Image description": "Bildbeschreibung",
"Style": "Stil",
"Dimensions": "Abmessungen",
"Insert image": "Bild einfügen",
"Zoom in": "Vergrößern",
"Contrast": "Kontrast",
"Back": "Zurück",
"Gamma": "Gamma",
"Flip horizontally": "Horizontal spiegeln",
"Resize": "Größe ändern",
"Sharpen": "Verschärfen",
"Zoom out": "Verkleinern",
"Image options": "Bildoptionen",
"Apply": "Anwenden",
"Brightness": "Helligkeit",
"Rotate clockwise": "Im Uhrzeigersinn drehen",
"Rotate counterclockwise": "Gegen den Uhrzeigersinn drehen",
"Edit image": "Bild bearbeiten",
"Color levels": "Farbstufen",
"Crop": "Beschneiden",
"Orientation": "Ausrichtung",
"Flip vertically": "Vertikal spiegeln",
"Invert": "Umkehren",
"Insert date\/time": "Datum\/Uhrzeit einfügen",
"Remove link": "Link entfernen",
"Url": "URL",
"Text to display": "Text zum Anzeigen",
"Anchors": "Festpunkte",
"Insert link": "Link einfügen",
"New window": "Neues Fenster",
"None": "Keine",
"The URL you entered seems to be an external link. Do you want to add the required http:\/\/ prefix?": "Bei der eingegebenen URL handelt es sich offenbar um einen externen Link. Wollen Sie das erforderliche Präfix http:\/\/ einfügen?",
"Target": "Ziel",
"The URL you entered seems to be an email address. Do you want to add the required mailto: prefix?": "Bei der eingegebenen URL handelt es sich offenbar um eine E-Mail-Adresse. Wollen Sie das erforderliche Präfix mailto: einfügen?",
"Insert\/edit link": "Link einfügen\/bearbeiten",
"Insert\/edit video": "Video einfügen\/bearbeiten",
"Poster": "Poster",
"Alternative source": "Alternative Quelle",
"Paste your embed code below:": "Fügen Sie unten Ihren Einbindungscode ein:",
"Insert video": "Video einfügen",
"Embed": "Einbinden",
"Nonbreaking space": "Geschütztes Leerzeichen",
"Page break": "Seitenumbruch",
"Paste as text": "Als Text einfügen",
"Preview": "Vorschau",
"Print": "Drucken",
"Save": "Speichern",
"Could not find the specified string.": "Die angegebene Zeichenfolge konnte nicht gefunden werden.",
"Replace": "Ersetzen",
"Next": "Weiter",
"Whole words": "Ganze Wörter",
"Find and replace": "Suchen und ersetzen",
"Replace with": "Ersetzen durch",
"Find": "Finden",
"Replace all": "Alle ersetzen",
"Match case": "Groß-\/Kleinschreibung beachten",
"Prev": "Zurück",
"Spellcheck": "Rechtschreibprüfung",
"Finish": "Fertigstellen",
"Ignore all": "Alle ignorieren",
"Ignore": "Ignorieren",
"Add to Dictionary": "Zu Wörterbuch hinzufügen",
"Insert row before": "Zeile darüber hinzufügen",
"Rows": "Zeilen",
"Height": "Höhe",
"Paste row after": "Zeile darunter einfügen",
"Alignment": "Ausrichtung",
"Border color": "Farbe des Rands",
"Column group": "Spaltengruppe",
"Row": "Zeile",
"Insert column before": "Spalte davor einfügen",
"Split cell": "Zelle teilen",
"Cell padding": "Zelle – Textabstand",
"Cell spacing": "Abstand zwischen Zellen",
"Row type": "Zeilentyp",
"Insert table": "Tabelle einfügen",
"Body": "Text",
"Caption": "Beschriftung",
"Footer": "Fußzeile",
"Delete row": "Zeile löschen",
"Paste row before": "Zeile darüber einfügen",
"Scope": "Anwendungsbereich",
"Delete table": "Tabelle löschen",
"H Align": "Horizontal zentrieren",
"Top": "Oben",
"Header cell": "Kopfzeilenzelle",
"Column": "Spalte",
"Row group": "Zeilengruppe",
"Cell": "Zelle",
"Middle": "Mitte",
"Cell type": "Zellentyp",
"Copy row": "Zeile kopieren",
"Row properties": "Zeileneigenschaften",
"Table properties": "Tabelleneigenschaften",
"Bottom": "Unten",
"V Align": "Vertikal zentrieren",
"Header": "Kopfzeile",
"Right": "Rechts",
"Insert column after": "Spalte danach hinzufügen",
"Cols": "Spalten",
"Insert row after": "Zeile darunter hinzufügen",
"Width": "Breite",
"Cell properties": "Zelleneigenschaften",
"Left": "Links",
"Cut row": "Zeile ausschneiden",
"Delete column": "Spalte löschen",
"Center": "Zentriert",
"Merge cells": "Zellen verbinden",
"Insert template": "Vorlage einfügen",
"Templates": "Vorlagen",
"Background color": "Hintergrundfarbe",
"Custom...": "Benutzerdefiniert...",
"Custom color": "Benutzerdefinierte Farbe",
"No color": "Keine Farbe",
"Text color": "Textfarbe",
"Show blocks": "Blöcke anzeigen",
"Show invisible characters": "Unsichtbare Zeichen anzeigen",
"Words: {0}": "Wörter: {0}",
"Insert": "Einfügen",
"File": "Datei",
"Edit": "Bearbeiten",
"Rich Text Area. Press ALT-F9 for menu. Press ALT-F10 for toolbar. Press ALT-0 for help": "Rich-Text-Bereich. Drücken Sie ALT-F9, um das Menü zu öffnen. Drücken Sie ALT-F10, um die Symbolleiste zu öffnen. Drücken Sie ALT-F0, um die Hilfe zu öffnen.",
"Tools": "Tools",
"View": "Anzeigen",
"Table": "Tabelle",
"Format": "Format"
});
