tinymce.addI18n('es_MX',{
"Cut": "Cortar",
"Heading 5": "Encabezado 5",
"Header 2": "Encabezado 2",
"Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X\/C\/V keyboard shortcuts instead.": "Su navegador no admite el acceso directo al portapapeles. En vez de ello, utilice los accesos rápidos del teclado de Ctrl+X\/C\/V.",
"Heading 4": "Encabezado 4",
"Div": "Div",
"Heading 2": "Encabezado 2",
"Paste": "Pegar",
"Close": "Cerrar",
"Font Family": "Familia de fuentes",
"Pre": "Pre",
"Align Right": "Alinear a la derecha",
"New document": "Documento nuevo",
"Blockquote": "Blockquote",
"Numbered list": "Lista numerada",
"Heading 1": "Encabezado 1",
"Headings": "Encabezados",
"Increase indent": "Aumentar sangría",
"Formats": "Formatos",
"Headers": "Encabezados",
"Select all": "Seleccionar todo",
"Header 3": "Encabezado 3",
"Blocks": "Bloques",
"Undo": "Deshacer",
"Strikethrough": "Tachado",
"Bullet list": "Lista de viñetas",
"Header 1": "Encabezado 1",
"Superscript": "Superíndice",
"Clear formatting": "Borrar formato",
"Font Sizes": "Tamaños de fuente",
"Subscript": "Subíndice",
"Header 6": "Encabezado 6",
"Redo": "Rehacer",
"Paragraph": "Párrafo",
"Ok": "Aceptar",
"Bold": "Negrita",
"Code": "Código",
"Italic": "Cursiva",
"Align Center": "Alinear al centro",
"Header 5": "Encabezado 5",
"Heading 6": "Encabezado 6",
"Heading 3": "Encabezado 3",
"Decrease indent": "Reducir sangría",
"Header 4": "Encabezado 4",
"Paste is now in plain text mode. Contents will now be pasted as plain text until you toggle this option off.": "La herramienta Pegar ahora funciona en modo de texto sin formato. Los contenidos se pegarán como texto sin formato hasta que desactive esta opción.",
"Underline": "Subrayar",
"Cancel": "Cancelar",
"Justify": "Justificar",
"Inline": "En línea",
"Copy": "Copiar",
"Align Left": "Alinear a la izquierda",
"Visual aids": "Ayudas visuales",
"Lower Greek": "Lower Greek",
"Square": "Square",
"Default": "Predeterminado",
"Lower Alpha": "Lower Alpha",
"Circle": "Circle",
"Disc": "Disc",
"Upper Alpha": "Upper Alpha",
"Upper Roman": "Upper Roman",
"Lower Roman": "Lower Roman",
"Name": "Nombre",
"Anchor": "Enlace",
"You have unsaved changes are you sure you want to navigate away?": "Hay cambios sin guardar, ¿está seguro de que desea salir?",
"Restore last draft": "Restaurar el último borrador",
"Special character": "Caracter especial",
"Source code": "Código fuente",
"B": "B",
"R": "R",
"G": "G",
"Color": "Color",
"Right to Left": "Derecha a izquierda",
"Left to Right": "Izquierda a derecha",
"Emoticons": "Emoticonos",
"Robots": "Robots",
"Document properties": "Propiedades del documento",
"Title": "Título",
"Keywords": "Palabras clave",
"Encoding": "Codificación",
"Description": "Descripción",
"Author": "Autor",
"Fullscreen": "Pantalla completa",
"Horizontal line": "Línea horizontal",
"Horizontal space": "Espacio horizontal",
"Insert\/edit image": "Insertar\/editar imagen",
"General": "General",
"Advanced": "Avanzado",
"Source": "Fuente",
"Border": "Borde",
"Constrain proportions": "Restringir las proporciones",
"Vertical space": "Espacio vertical",
"Image description": "Descripción de la imagen",
"Style": "Estilo",
"Dimensions": "Dimensiones",
"Insert image": "Insertar imagen",
"Zoom in": "Ampliar",
"Contrast": "Contraste",
"Back": "Volver",
"Gamma": "Gama",
"Flip horizontally": "Voltear horizontalmente",
"Resize": "Cambiar tamaño",
"Sharpen": "Dar nitidez",
"Zoom out": "Alejar",
"Image options": "Opciones de la imagen",
"Apply": "Aplicar",
"Brightness": "Brillo",
"Rotate clockwise": "Girar hacia la derecha",
"Rotate counterclockwise": "Girar hacia la izquierda",
"Edit image": "Editar imagen",
"Color levels": "Niveles de color",
"Crop": "Recortar",
"Orientation": "Orientación",
"Flip vertically": "Voltear verticalmente",
"Invert": "Invertir",
"Insert date\/time": "Insertar fecha\/hora",
"Remove link": "Quitar enlace",
"Url": "Dirección URL",
"Text to display": "Texto que se va a mostrar",
"Anchors": "Enlaces",
"Insert link": "Insertar enlace",
"New window": "Ventana nueva",
"None": "Ninguno",
"The URL you entered seems to be an external link. Do you want to add the required http:\/\/ prefix?": "La URL que ingresó parece ser un enlace externo. ¿Desea agregar el prefijo http:\/\/ necesario?",
"Target": "Destino",
"The URL you entered seems to be an email address. Do you want to add the required mailto: prefix?": "La URL que ingresó parece ser una dirección de correo electrónico. ¿Desea agregar el prefijo mailto: necesario?",
"Insert\/edit link": "Insertar\/editar enlace",
"Insert\/edit video": "Insertar\/editar video",
"Poster": "Autor",
"Alternative source": "Fuente alternativa",
"Paste your embed code below:": "Pegue su código incrustado a continuación:",
"Insert video": "Insertar video",
"Embed": "Integrar",
"Nonbreaking space": "Espacio duro",
"Page break": "Salto de página",
"Paste as text": "Pegar como texto",
"Preview": "Vista previa",
"Print": "Imprimir",
"Save": "Guardar",
"Could not find the specified string.": "No se pudo encontrar la cadena especificada.",
"Replace": "Reemplazar",
"Next": "Siguiente",
"Whole words": "Palabras completas",
"Find and replace": "Buscar y reemplazar",
"Replace with": "Reemplazar por",
"Find": "Buscar",
"Replace all": "Reemplazar todo",
"Match case": "Coincidir mayúsculas y minúsculas",
"Prev": "Anterior",
"Spellcheck": "Corrector ortográfico",
"Finish": "Finalizar",
"Ignore all": "Ignorar todo",
"Ignore": "Ignorar",
"Add to Dictionary": "Agregar al diccionario",
"Insert row before": "Insertar fila antes",
"Rows": "Filas",
"Height": "Altura",
"Paste row after": "Pegar fila a continuación",
"Alignment": "Alineación",
"Border color": "Color de borde",
"Column group": "Grupo de columnas",
"Row": "Fila",
"Insert column before": "Insertar columna antes",
"Split cell": "Dividir celda",
"Cell padding": "Relleno de celda",
"Cell spacing": "Espaciado de celda",
"Row type": "Tipo de fila",
"Insert table": "Insertar tabla",
"Body": "Cuerpo",
"Caption": "Leyenda",
"Footer": "Pie de página",
"Delete row": "Eliminar fila",
"Paste row before": "Pegar fila antes",
"Scope": "Ámbito",
"Delete table": "Eliminar tabla",
"H Align": "Alinear H",
"Top": "Superior",
"Header cell": "Celda de encabezado",
"Column": "Columna",
"Row group": "Grupo de filas",
"Cell": "Celda",
"Middle": "Central",
"Cell type": "Tipo de celda",
"Copy row": "Copiar fila",
"Row properties": "Propiedades de fila",
"Table properties": "Propiedades de tabla",
"Row group": "Grupo de filas",
"Bottom": "Inferior",
"V Align": "Alinear V",
"Header": "Encabezado",
"Right": "Derecha",
"Insert column after": "Insertar columna después",
"Cols": "Columnas",
"Insert row after": "Insertar fila después",
"Width": "Ancho",
"Cell properties": "Propiedades de celda",
"Left": "Izquierda",
"Cut row": "Cortar fila",
"Delete column": "Eliminar columna",
"Center": "Centro",
"Merge cells": "Combinar celdas",
"Insert template": "Insertar plantilla",
"Templates": "Plantillas",
"Background color": "Color de fondo",
"Custom...": "Personalizado...",
"Custom color": "Color personalizado",
"No color": "Sin color",
"Text color": "Color de texto",
"Show blocks": "Mostrar bloques",
"Show invisible characters": "Mostrar caracteres invisibles",
"Words: {0}": "Palabras: {0}",
"Insert": "Insertar",
"File": "Archivo",
"Edit": "Editar",
"Rich Text Area. Press ALT-F9 for menu. Press ALT-F10 for toolbar. Press ALT-0 for help": "Área de texto enriquecido. Presione ALT-F10 para ver la barra de herramientas y presione ESC para salir de la barra de herramientas.",
"Tools": "Herramientas",
"View": "Vista",
"Table": "Tabla",
"Format": "Formato"
});
