tinymce.addI18n('fi',{
    "Cut": "Leikkaa",
    "Heading 5": "Otsikko 5",
    "Header 2": "Alatunniste 2",
    "Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X/C/V keyboard shortcuts instead.": "Selain ei tue suoraa leikepöydän käyttöä. Käytä Ctrl+X/C/V-pikanäppäimiä.",
    "Heading 4": "Otsikko 4",
    "Div": "Div",
    "Heading 2": "Otsikko 2",
    "Paste": "Liitä",
    "Close": "Sulje",
    "Font Family": "Fonttiperhe",
    "Pre": "Pre",
    "Align Right": "Tasaa oikealle",
    "New document": "Uusi asiakirja",
    "Blockquote": "Blockquote",
    "Numbered list": "Numeroitu luettelo",
    "Heading 1": "Otsikko 1",
    "Headings": "Otsikot",
    "Increase indent": "Lisää sisennystä",
    "Formats": "Muotoilut",
    "Headers": "Ylätunnisteet",
    "Select all": "Valitse kaikki",
    "Header 3": "Alatunniste 3",
    "Blocks": "Lohkot",
    "Undo": "Kumoa",
    "Strikethrough": "Päälleviivaus",
    "Bullet list": "Luettelomerkitty luettelo",
    "Header 1": "Alatunniste 1",
    "Superscript": "Yläindeksi",
    "Clear formatting": "Tyhjennä muotoilut",
    "Font Sizes": "Fonttikoot",
    "Subscript": "Alaindeksi",
    "Header 6": "Alatunniste 6",
    "Redo": "Tee uudelleen",
    "Paragraph": "Kappale",
    "Ok": "OK",
    "Bold": "Lihavoitu",
    "Code": "Koodi",
    "Italic": "Kursivoitu",
    "Align Center": "Tasaa keskelle",
    "Header 5": "Alatunniste 5",
    "Heading 6": "Otsikko 6",
    "Heading 3": "Otsikko 3",
    "Decrease indent": "Vähennä sisennystä",
    "Header 4": "Alatunniste 4",
    "Paste is now in plain text mode. Contents will now be pasted as plain text until you toggle this option off.": "Liittäminen on nyt vain teksti -tilassa. Sisältö liitetään vain tekstinä, kunnes poistat asetuksen käytöstä.",
    "Underline": "Alleviivaus",
    "Cancel": "Peruuta",
    "Justify": "Tasaa",
    "Inline": "Sisäinen",
    "Copy": "Kopioi",
    "Align Left": "Tasaa vasemmalle",
    "Visual aids": "Visuaaliset apuvälineet",
    "Lower Greek": "Lower Greek",
    "Square": "Neliö",
    "Default": "Oletus",
    "Lower Alpha": "Lower Alpha",
    "Circle": "Ympyrä",
    "Disc": "Levy",
    "Upper Alpha": "Upper Alpha",
    "Upper Roman": "Upper Roman",
    "Lower Roman": "Lower Roman",
    "Name": "Nimi",
    "Anchor": "Ankkuri",
    "You have unsaved changes are you sure you want to navigate away?": "Muutoksia on tallentamatta, haluatko varmasti poistua?",
    "Restore last draft": "Palauta viimeinen luonnos",
    "Special character": "Erikoismerkki",
    "Source code": "Lähdekoodi",
    "B": "B",
    "R": "R",
    "G": "G",
    "Color": "Väri",
    "Right to Left": "Oikealta vasemmalle",
    "Left to Right": "Vasemmalta oikealle",
    "Emoticons": "Hymiöt",
    "Robots": "Robotit",
    "Document properties": "Asiakirjan ominaisuudet",
    "Title": "Otsikko",
    "Keywords": "Avainsanat",
    "Encoding": "Koodaus",
    "Description": "Kuvaus",
    "Author": "Tekijä",
    "Fullscreen": "Koko näyttö",
    "Horizontal line": "Vaakaviiva",
    "Horizontal space": "Vaakaväli",
    "Insert/edit image": "Lisää kuva / muokkaa kuvaa",
    "General": "Yleiset",
    "Advanced": "Lisäasetukset",
    "Source": "Lähde",
    "Border": "Reunus",
    "Constrain proportions": "Säilytä mittasuhteet",
    "Vertical space": "Pystytila",
    "Image description": "Kuvan kuvaus",
    "Style": "Tyyli",
    "Dimensions": "Mitat",
    "Insert image": "Lisää kuva",
    "Zoom in": "Lähennä",
    "Contrast": "Kontrasti",
    "Back": "Takaisin",
    "Gamma": "Gamma",
    "Flip horizontally": "Vaakakääntö",
    "Resize": "Muuta kokoa",
    "Sharpen": "Terävöitä",
    "Zoom out": "Loitonna",
    "Image options": "Kuva-asetukset",
    "Apply": "Käytä",
    "Brightness": "Kirkkaus",
    "Rotate clockwise": "Kierrä myötäpäivään",
    "Rotate counterclockwise": "Kierrä vastapäivään",
    "Edit image": "Muokkaa kuvaa",
    "Color levels": "Väritasot",
    "Crop": "Rajaa",
    "Orientation": "Suunta",
    "Flip vertically": "Pystykääntö",
    "Invert": "Käänteinen",
    "Insert date/time": "Lisää päivämäärä/kellonaika",
    "Remove link": "Poista linkki",
    "Url": "URL-osoite",
    "Text to display": "Näytettävä teksti",
    "Anchors": "Ankkurit",
    "Insert link": "Lisää linkki",
    "New window": "Uusi ikkuna",
    "None": "Ei mitään",
    "The URL you entered seems to be an external link. Do you want to add the required http:// prefix?": "Antamasi URL näyttää olevan ulkoinen linkki. Haluatko lisätä tarvittavan etuliitteen http://?",
    "Target": "Kohde",
    "The URL you entered seems to be an email address. Do you want to add the required mailto: prefix?": "Antamasi URL näyttää olevan sähköpostiosoite. Haluatko lisätä tarvittavan etuliitteen mailto:?",
    "Insert/edit link": "Lisää linkki / muokkaa linkkiä",
    "Insert/edit video": "Lisää video / muokkaa videota",
    "Poster": "Juliste",
    "Alternative source": "Vaihtoehtoinen lähde",
    "Paste your embed code below:": "Liitä upotuskoodi alle:",
    "Insert video": "Lisää video",
    "Embed": "Upota",
    "Nonbreaking space": "Sitova välilyönti",
    "Page break": "Sivunvaihto",
    "Paste as text": "Liitä tekstinä",
    "Preview": "Esikatselu",
    "Print": "Tulosta",
    "Save": "Tallenna",
    "Could not find the specified string.": "Määritettyä merkkijonoa ei löydy.",
    "Replace": "Korvaa",
    "Next": "Seuraava",
    "Whole words": "Kokonaiset sanat",
    "Find and replace": "Etsi ja korvaa",
    "Replace with": "Korvaava",
    "Find": "Etsi",
    "Replace all": "Korvaa kaikki",
    "Match case": "Sama kirjainkoko",
    "Prev": "Edellinen",
    "Spellcheck": "Oikeinkirjoituksen tarkistus",
    "Finish": "Valmis",
    "Ignore all": "Ohita kaikki",
    "Ignore": "Ohita",
    "Add to Dictionary": "Lisää sanastoon",
    "Insert row before": "Lisää rivi edelle",
    "Rows": "Rivit",
    "Height": "Korkeus",
    "Paste row after": "Liitä rivi jälkeen",
    "Alignment": "Tasaus",
    "Border color": "Reunuksen väri",
    "Column group": "Sarakeryhmä",
    "Row": "Rivi",
    "Insert column before": "Lisää sarake edelle",
    "Split cell": "Jaa solu",
    "Cell padding": "Solujen täyttö",
    "Cell spacing": "Solujen välistys",
    "Row type": "Rivin tyyppi",
    "Insert table": "Lisää taulukko",
    "Body": "Teksti",
    "Caption": "Kuvateksti",
    "Footer": "Alatunniste",
    "Delete row": "Poista rivi",
    "Paste row before": "Liitä rivi edelle",
    "Scope": "Laajuus",
    "Delete table": "Poista taulukko",
    "H Align": "H Align",
    "Top": "Ylös",
    "Header cell": "Otsikkosolu",
    "Column": "Sarake",
    "Row group": "Riviryhmä",
    "Cell": "Solu",
    "Middle": "Keski",
    "Cell type": "Solun tyyppi",
    "Copy row": "Kopioi rivi",
    "Row properties": "Rivin ominaisuudet",
    "Table properties": "Taulukon ominaisuudet",
    "Bottom": "Alareuna",
    "V Align": "V Align",
    "Header": "Ylätunniste",
    "Right": "Oikea",
    "Insert column after": "Lisää sarake jälkeen",
    "Cols": "Sarakkeet",
    "Insert row after": "Lisää rivi jälkeen",
    "Width": "Leveys",
    "Cell properties": "Solun ominaisuudet",
    "Left": "Vasen",
    "Cut row": "Leikkaa rivi",
    "Delete column": "Poista sarake",
    "Center": "Keskikohta",
    "Merge cells": "Yhdistä solut",
    "Insert template": "Lisää malli",
    "Templates": "Mallit",
    "Background color": "Taustaväri",
    "Custom...": "Mukautettu...",
    "Custom color": "Mukautettu väri",
    "No color": "Ei väriä",
    "Text color": "Tekstin väri",
    "Show blocks": "Näytä lohkot",
    "Show invisible characters": "Näytä näkymättömät merkit",
    "Words: {0}": "Sanat: {0}",
    "Insert": "Lisää",
    "File": "Tiedosto",
    "Edit": "Muokkaa",
    "Rich Text Area. Press ALT-F9 for menu. Press ALT-F10 for toolbar. Press ALT-0 for help": "Rich Text -alue. Valikko: ALT-F9. Työkalurivi: ALT-F10. Ohje: ALT-0",
    "Tools": "Työkalut",
    "View": "Näytä",
    "Table": "Taulukko",
    "Format": "Muotoilu"
});
