tinymce.addI18n('fr_CA',{
"Cut": "Couper",
"Heading 5": "En-tête de section 5",
"Header 2": "En-tête 2",
"Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X\/C\/V keyboard shortcuts instead.": "Votre navigateur ne permet pas l’accès direct au presse-papier. Veuillez en conséquence utiliser les touches de raccourci Ctrl + X, Ctrl + C et Ctrl + V.",
"Heading 4": "En-tête de section 4",
"Div": "Div.",
"Heading 2": "En-tête de section 2",
"Paste": "Coller",
"Close": "Fermer",
"Font Family": "Famille de police de caractères",
"Pre": "Pré",
"Align Right": "Aligner à droite",
"New document": "Nouveau document",
"Blockquote": "Bloc de citations",
"Numbered list": "Liste numérotée",
"Heading 1": "En-tête de section 1",
"Headings": "En-têtes de section",
"Increase indent": "Augmenter le retrait positif",
"Formats": "Formats",
"Headers": "En-têtes",
"Select all": "Tout sélectionner",
"Header 3": "En-tête 3",
"Blocks": "Blocs",
"Undo": "Annuler",
"Strikethrough": "Barrer",
"Bullet list": "Liste à puces",
"Header 1": "En-tête 1",
"Superscript": "Indice supérieur",
"Clear formatting": "Effacer le formatage",
"Font Sizes": "Tailles de police",
"Subscript": "Indice inférieur",
"Header 6": "En-tête 6",
"Redo": "Rétablir",
"Paragraph": "Paragraphe",
"Ok": "OK",
"Bold": "Gras",
"Code": "Code",
"Italic": "Italique",
"Align Center": "Centrer",
"Header 5": "En-tête 5",
"Heading 6": "En-tête de section 6",
"Heading 3": "En-tête de section 3",
"Decrease indent": "Diminuer le retrait",
"Header 4": "En-tête 4",
"Paste is now in plain text mode. Contents will now be pasted as plain text until you toggle this option off.": "La fonction Coller est maintenant en mode texte en clair. Le contenu sera maintenant collé en texte en clair jusqu’à la désactivation de la fonction.",
"Underline": "Souligner",
"Cancel": "Annuler",
"Justify": "Justifier",
"Inline": "Intégré",
"Copy": "Copier",
"Align Left": "Aligner à gauche",
"Visual aids": "Aides visuelles",
"Lower Greek": "Caractère grec minuscule",
"Square": "Carré",
"Default": "Par défaut",
"Lower Alpha": "Caractère alphabétique minuscule",
"Circle": "Cercle",
"Disc": "Disque",
"Upper Alpha": "Caractère alphabétique majuscule",
"Upper Roman": "Caractère romain majuscule",
"Lower Roman": "Caractère romain minuscule",
"Name": "Nom",
"Anchor": "Point d’ancrage",
"You have unsaved changes are you sure you want to navigate away?": "Vous avez des changements non enregistrés, êtes-vous certain de vouloir poursuivre la navigation?",
"Restore last draft": "Restaurer le dernier brouillon",
"Special character": "Caractère spécial",
"Source code": "Code source",
"B": "B",
"R": "R",
"G": "G",
"Color": "Couleur",
"Right to Left": "Droite à gauche",
"Left to Right": "Gauche à droite",
"Emoticons": "Émoticônes",
"Robots": "Robots",
"Document properties": "Propriétés du document",
"Title": "Titre",
"Keywords": "Mots clés",
"Encoding": "Encodage",
"Description": "Description",
"Author": "Auteur",
"Fullscreen": "Plein écran",
"Horizontal line": "Ligne horizontale",
"Horizontal space": "Espace horizontal",
"Insert\/edit image": "Insérer ou modifier une image",
"General": "Général",
"Advanced": "Avancé",
"Source": "Source",
"Border": "Bordure",
"Constrain proportions": "Limiter les proportions",
"Vertical space": "Espace vertical",
"Image description": "Description de l’image",
"Style": "Style",
"Dimensions": "Dimensions",
"Insert image": "Insérer une image",
"Zoom in": "Zoom avant",
"Contrast": "Contraste",
"Back": "Retour",
"Gamma": "Gamma",
"Flip horizontally": "Retourner horizontalement",
"Resize": "Redimensionner",
"Sharpen": "Accentuer",
"Zoom out": "Zoom arrière",
"Image options": "Options de l’image",
"Apply": "Appliquer",
"Brightness": "Luminosité",
"Rotate clockwise": "Pivoter dans le sens horaire",
"Rotate counterclockwise": "Pivoter dans le sens antihoraire",
"Edit image": "Modifier l’image",
"Color levels": "Niveaux de couleur",
"Crop": "Recadrer",
"Orientation": "Orientation",
"Flip vertically": "Retourner verticalement",
"Invert": "Inverser",
"Insert date\/time": "Insérer la date et l’heure",
"Remove link": "Supprimer le lien",
"Url": "URL",
"Text to display": "Texte à afficher",
"Anchors": "Points d’ancrage",
"Insert link": "Insérer le lien",
"New window": "Nouvelle fenêtre",
"None": "Aucun",
"The URL you entered seems to be an external link. Do you want to add the required http:\/\/ prefix?": "L’URL que vous avez entrée semble provenir d’un lien externe. Voulez-vous ajouter le préfixe http://W requis?",
"Target": "Cible",
"The URL you entered seems to be an email address. Do you want to add the required mailto: prefix?": "L’URL que vous avez entrée semble provenir d’une adresse courriel. Voulez-vous ajouter le préfixe « mailto: » requis?",
"Insert\/edit link": "Insérer ou modifier un lien",
"Insert\/edit video": "Insérer ou modifier une vidéo",
"Poster": "Affiche",
"Alternative source": "Source de remplacement",
"Paste your embed code below:": "Collez votre code d’incorporation ci-dessous :",
"Insert video": "Insérer une vidéo",
"Embed": "Incorporer",
"Nonbreaking space": "Espace insécable",
"Page break": "Saut de page",
"Paste as text": "Coller comme texte",
"Preview": "Prévisualiser",
"Print": "Imprimer",
"Save": "Enregistrer",
"Could not find the specified string.": "Impossible de trouver la chaîne indiquée.",
"Replace": "Remplacer",
"Next": "Suivant",
"Whole words": "Mots complets",
"Find and replace": "Recherche et remplacement",
"Replace with": "Remplacer par",
"Find": "Rechercher",
"Replace all": "Remplacer tout",
"Match case": "Respecter la casse",
"Prev": "Précédent",
"Spellcheck": "Vérification orthographique",
"Finish": "Terminer",
"Ignore all": "Ignorer tout",
"Ignore": "Ignorer",
"Add to Dictionary": "Ajouter au dictionnaire",
"Insert row before": "Insérer une rangée au-dessus",
"Rows": "Rangées",
"Height": "Hauteur",
"Paste row after": "Coller la rangée au-dessous",
"Alignment": "Alignement",
"Border color": "Couleur de la bordure",
"Column group": "Groupe de colonnes",
"Row": "Rangées",
"Insert column before": "Insérer une colonne à gauche",
"Split cell": "Diviser la cellule",
"Cell padding": "Remplissage de cellule",
"Cell spacing": "Espacement de cellule",
"Row type": "Type de rangée",
"Insert table": "Insérer un tableau",
"Body": "Corps",
"Caption": "Légende",
"Footer": "Pied de page",
"Delete row": "Supprimer la rangée",
"Paste row before": "Coller la rangée au-dessus",
"Scope": "Portée",
"Delete table": "Supprimer le tableau",
"H Align": "Alignement horizontal",
"Top": "Haut",
"Header cell": "Cellule d’en-tête",
"Column": "Colonne",
"Row group": "Groupe de rangées",
"Cell": "Cellule",
"Middle": "Milieu",
"Cell type": "Type de cellule",
"Copy row": "Copier la rangée",
"Row properties": "Propriétés de la rangée",
"Table properties": "Propriétés du tableau",
"Row group": "Groupe de rangées",
"Bottom": "Bas",
"V Align": "Alignement vertical",
"Header": "En-tête",
"Right": "Droite",
"Insert column after": "Insérer une colonne à droite",
"Cols": "Colonnes",
"Insert row after": "Insérer une rangée au-dessous",
"Width": "Largeur",
"Cell properties": "Propriétés de la cellule",
"Left": "Gauche",
"Cut row": "Couper la rangée",
"Delete column": "Supprimer la colonne",
"Center": "Centre",
"Merge cells": "Fusionner les cellules",
"Insert template": "Insérer un modèle",
"Templates": "Modèles",
"Background color": "Couleur de l’arrière-plan",
"Custom...": "Personnaliser...",
"Custom color": "Personnaliser la couleur",
"No color": "Aucune couleur",
"Text color": "Couleur du texte",
"Show blocks": "Montrer les blocs",
"Show invisible characters": "Montrer les caractères invisibles",
"Words: {0}": "Mots : {0}",
"Insert": "Insérer",
"File": "Fichier",
"Edit": "Modifier",
"Rich Text Area. Press ALT-F9 for menu. Press ALT-F10 for toolbar. Press ALT-0 for help": "Zone de texte enrichi Cliquez sur Alt + F10 pour afficher la barre d’outils et sur Échap pour la faire disparaître.",
"Tools": "Outils",
"View": "Afficher",
"Table": "Tableau",
"Format": "Format"
});
