tinymce.addI18n('ja',{
"Cut": "切り取り",
"Heading 5": "見出し 5",
"Header 2": "ヘッダー 2",
"Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X\/C\/V keyboard shortcuts instead.": "お使いのブラウザでは、クリップボードへの直接アクセスはサポートされていません。代わりにキーボードショートカット（Ctrl+X、Ctrl+C、Ctrl+V）を使用してください。",
"Heading 4": "見出し 4",
"Div": "Div",
"Heading 2": "見出し 2",
"Paste": "貼り付け",
"Close": "閉じる",
"Font Family": "フォントファミリ",
"Pre": "Pre",
"Align Right": "右揃え",
"New document": "新規ドキュメント",
"Blockquote": "Blockquote",
"Numbered list": "番号付きリスト",
"Heading 1": "見出し 1",
"Headings": "見出し",
"Increase indent": "インデントを増やす",
"Formats": "形式",
"Headers": "ヘッダー",
"Select all": "すべてを選択",
"Header 3": "ヘッダー 3",
"Blocks": "ブロック",
"Undo": "元に戻す",
"Strikethrough": "取り消し線",
"Bullet list": "箇条書きリスト",
"Header 1": "ヘッダー 1",
"Superscript": "上付き文字",
"Clear formatting": "書式の消去",
"Font Sizes": "フォントサイズ",
"Subscript": "下付き文字",
"Header 6": "ヘッダー 6",
"Redo": "やり直し",
"Paragraph": "パラグラフ",
"Ok": "OK",
"Bold": "太字",
"Code": "コード",
"Italic": "斜体",
"Align Center": "中央揃え",
"Header 5": "ヘッダー 5",
"Heading 6": "見出し 6",
"Heading 3": "見出し 3",
"Decrease indent": "インデントを減らす",
"Header 4": "ヘッダー 4",
"Paste is now in plain text mode. Contents will now be pasted as plain text until you toggle this option off.": "現在、貼り付けはプレーンテキストモードです。このオプションをオフにしない場合、内容はプレーンテキストとして貼り付けられます。",
"Underline": "下線",
"Cancel": "キャンセル",
"Justify": "行揃え",
"Inline": "インライン",
"Copy": "コピー",
"Align Left": "左揃え",
"Visual aids": "視覚的素材",
"Lower Greek": "ギリシャ文字小文字",
"Square": "四角",
"Default": "デフォルト",
"Lower Alpha": "アルファベット小文字",
"Circle": "白丸",
"Disc": "黒丸",
"Upper Alpha": "アルファベット大文字",
"Upper Roman": "ローマ数字大文字",
"Lower Roman": "ローマ数字小文字",
"Name": "名前",
"Anchor": "アンカー",
"You have unsaved changes are you sure you want to navigate away?": "まだ変更を保存していません。別の場所に移動してもよろしいですか？",
"Restore last draft": "前回の下書きの復元",
"Special character": "特殊文字",
"Source code": "ソースコード",
"B": "B",
"R": "R",
"G": "G",
"Color": "カラー",
"Right to Left": "右から左",
"Left to Right": "左から右",
"Emoticons": "顔文字",
"Robots": "ロボット",
"Document properties": "ドキュメントのプロパティ",
"Title": "タイトル",
"Keywords": "キーワード",
"Encoding": "エンコード",
"Description": "説明",
"Author": "作成者",
"Fullscreen": "全画面",
"Horizontal line": "横線",
"Horizontal space": "左右の間隔",
"Insert\/edit image": "イメージの挿入\/編集",
"General": "一般",
"Advanced": "アドバンスト",
"Source": "ソース",
"Border": "境界線",
"Constrain proportions": "縦横比の固定",
"Vertical space": "上下の間隔",
"Image description": "イメージの説明",
"Style": "スタイル",
"Dimensions": "寸法",
"Insert image": "イメージの挿入",
"Zoom in": "ズームイン",
"Contrast": "コントラスト",
"Back": "戻る",
"Gamma": "ガンマ",
"Flip horizontally": "左右反転",
"Resize": "サイズ変更",
"Sharpen": "シャープ",
"Zoom out": "ズームアウト",
"Image options": "イメージのオプション",
"Apply": "適用",
"Brightness": "明度",
"Rotate clockwise": "時計回りの回転",
"Rotate counterclockwise": "反時計回りの回転",
"Edit image": "イメージの編集",
"Color levels": "色レベル",
"Crop": "トリミング",
"Orientation": "方向",
"Flip vertically": "上下反転",
"Invert": "反転",
"Insert date\/time": "日付\/時刻の挿入",
"Remove link": "リンクの削除",
"Url": "URL",
"Text to display": "表示するテキスト",
"Anchors": "アンカー",
"Insert link": "リンクの挿入",
"New window": "新規ウィンドウ",
"None": "なし",
"The URL you entered seems to be an external link. Do you want to add the required http:\/\/ prefix?": "入力された URL は外部リンクの可能性があります。必須の http:\/\/ 接頭辞を追加しますか？",
"Target": "ターゲット",
"The URL you entered seems to be an email address. Do you want to add the required mailto: prefix?": "入力された URL は、電子メールアドレスの可能性があります。必須の mailto: 接頭辞を追加しますか？",
"Insert\/edit link": "リンクの挿入\/編集",
"Insert\/edit video": "ビデオの挿入\/編集",
"Poster": "ポスター",
"Alternative source": "代替ソース",
"Paste your embed code below:": "組み込みコードを以下に貼り付け:",
"Insert video": "ビデオの挿入",
"Embed": "埋め込み",
"Nonbreaking space": "改行をしないスペース",
"Page break": "改ページ",
"Paste as text": "テキストとして貼り付け",
"Preview": "プレビュー",
"Print": "印刷",
"Save": "保存",
"Could not find the specified string.": "指定された文字列が見つかりませんでした。",
"Replace": "置換",
"Next": "次へ",
"Whole words": "単語全体",
"Find and replace": "検索して置換",
"Replace with": "置換後",
"Find": "検索",
"Replace all": "すべて置換",
"Match case": "大文字と小文字を区別",
"Prev": "前へ",
"Spellcheck": "スペルチェック",
"Finish": "完了",
"Ignore all": "すべてを無視",
"Ignore": "無視",
"Add to Dictionary": "辞書に追加",
"Insert row before": "上に行を挿入",
"Rows": "行",
"Height": "高さ",
"Paste row after": "下に行を貼り付け",
"Alignment": "配置",
"Border color": "境界線の色",
"Column group": "列グループ",
"Row": "行",
"Insert column before": "左に列を挿入",
"Split cell": "セルの分割",
"Cell padding": "セルのパディング",
"Cell spacing": "セルのスペーシング",
"Row type": "行のタイプ",
"Insert table": "表の挿入",
"Body": "本文",
"Caption": "キャプション",
"Footer": "フッター",
"Delete row": "行の削除",
"Paste row before": "上に行を貼り付け",
"Scope": "範囲",
"Delete table": "表の削除",
"H Align": "横揃え",
"Top": "上部",
"Header cell": "ヘッダーセル",
"Column": "列",
"Row group": "行グループ",
"Cell": "セル",
"Middle": "中央",
"Cell type": "セルのタイプ",
"Copy row": "行のコピー",
"Row properties": "行のプロパティ",
"Table properties": "表のプロパティ",
"Row group": "行グループ",
"Bottom": "下部",
"V Align": "縦揃え",
"Header": "ヘッダー",
"Right": "右",
"Insert column after": "右に列を挿入",
"Cols": "列",
"Insert row after": "下に行を挿入",
"Width": "幅",
"Cell properties": "セルのプロパティ",
"Left": "左",
"Cut row": "行の切り取り",
"Delete column": "列の削除",
"Center": "中央",
"Merge cells": "セルの結合",
"Insert template": "テンプレートの挿入",
"Templates": "テンプレート",
"Background color": "背景色",
"Custom...": "カスタム...",
"Custom color": "カスタムの色",
"No color": "色なし",
"Text color": "テキストの色",
"Show blocks": "ブロックの表示",
"Show invisible characters": "非表示文字の表示",
"Words: {0}": "単語: {0}",
"Insert": "挿入",
"File": "ファイル",
"Edit": "編集",
"Rich Text Area. Press ALT-F9 for menu. Press ALT-F10 for toolbar. Press ALT-0 for help": "リッチテキスト領域。ツールバーを表示するには、ALT キーを押したまま F10 キーを押します。表示状態でツールバーを閉じるには、ESC キーを押します。",
"Tools": "ツール",
"View": "表示",
"Table": "表",
"Format": "形式"
});
