tinymce.addI18n('ko_KR',{
"Cut": "잘라내기",
"Heading 5": "머리글 5",
"Header 2": "머리글 2",
"Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X\/C\/V keyboard shortcuts instead.": "해당 브라우저는 클립보드로의 직접 액세스를 지원하지 않습니다. 대신 Ctrl+X\/C\/V 키보드 단축키를 사용해 보십시오.",
"Heading 4": "머리글 4",
"Div": "분할",
"Heading 2": "머리글 2",
"Paste": "붙여넣기",
"Close": "닫기",
"Font Family": "글꼴 패밀리",
"Pre": "사전",
"Align Right": "오른쪽 정렬",
"New document": "새 문서",
"Blockquote": "Blockquote",
"Numbered list": "번호가 매겨진 목록",
"Heading 1": "머리글 1",
"Headings": "머리글",
"Increase indent": "들여쓰기",
"Formats": "형식",
"Headers": "머리글",
"Select all": "모두 선택",
"Header 3": "머리글 3",
"Blocks": "블록",
"Undo": "실행 취소",
"Strikethrough": "취소선",
"Bullet list": "글머리표 목록",
"Header 1": "머리글 1",
"Superscript": "위 첨자",
"Clear formatting": "서식 제거",
"Font Sizes": "글꼴 크기",
"Subscript": "아래 첨자",
"Header 6": "머리글 6",
"Redo": "반복 실행",
"Paragraph": "단락",
"Ok": "확인",
"Bold": "굵게",
"Code": "코드",
"Italic": "기울임꼴",
"Align Center": "가운데 정렬",
"Header 5": "머리글 5",
"Heading 6": "머리글 6",
"Heading 3": "머리글 3",
"Decrease indent": "내어쓰기",
"Header 4": "머리글 4",
"Paste is now in plain text mode. Contents will now be pasted as plain text until you toggle this option off.": "이제 붙여넣기가 일반 텍스트 모드로 설정되었습니다. 이 옵션을 해제할 때까지 콘텐츠를 일반 텍스트로 붙여 넣습니다.",
"Underline": "밑줄",
"Cancel": "취소",
"Justify": "양쪽 맞춤",
"Inline": "인라인",
"Copy": "복사",
"Align Left": "왼쪽 정렬",
"Visual aids": "시각 보조 도구",
"Lower Greek": "그리스어 소문자",
"Square": "사각형",
"Default": "기본값",
"Lower Alpha": "알파벳 소문자",
"Circle": "원",
"Disc": "디스크",
"Upper Alpha": "알파벳 대문자",
"Upper Roman": "로마어 대문자",
"Lower Roman": "로마어 소문자",
"Name": "이름",
"Anchor": "기준 위치",
"You have unsaved changes are you sure you want to navigate away?": "변경 사항이 저장되지 않았습니다. 계속 탐색하시겠습니까?",
"Restore last draft": "마지막 초안 복원",
"Special character": "특수 문자",
"Source code": "소스 코드",
"B": "B",
"R": "R",
"G": "G",
"Color": "색상",
"Right to Left": "오른쪽에서 왼쪽으로",
"Left to Right": "왼쪽에서 오른쪽으로",
"Emoticons": "이모티콘",
"Robots": "로봇",
"Document properties": "문서 속성",
"Title": "제목",
"Keywords": "키워드",
"Encoding": "인코딩",
"Description": "설명",
"Author": "작성자",
"Fullscreen": "전체 화면",
"Horizontal line": "가로줄",
"Horizontal space": "가로 간격",
"Insert\/edit image": "이미지 삽입\/편집",
"General": "일반",
"Advanced": "고급",
"Source": "소스",
"Border": "테두리",
"Constrain proportions": "비율 제약",
"Vertical space": "세로 간격",
"Image description": "이미지 설명",
"Style": "스타일",
"Dimensions": "크기",
"Insert image": "이미지 삽입",
"Zoom in": "확대",
"Contrast": "명암비",
"Back": "뒤로",
"Gamma": "감마",
"Flip horizontally": "좌우 반전",
"Resize": "크기 조정",
"Sharpen": "선명도 조정",
"Zoom out": "축소",
"Image options": "이미지 옵션",
"Apply": "적용",
"Brightness": "밝기",
"Rotate clockwise": "시계 방향으로 회전",
"Rotate counterclockwise": "시계 반대 방향으로 회전",
"Edit image": "이미지 편집",
"Color levels": "색상 수준",
"Crop": "자르기",
"Orientation": "방향",
"Flip vertically": "상하 반전",
"Invert": "반전",
"Insert date\/time": "날짜\/시간 삽입",
"Remove link": "링크 제거",
"Url": "URL",
"Text to display": "표시할 텍스트",
"Anchors": "기준 위치",
"Insert link": "링크 삽입",
"New window": "새 창",
"None": "없음",
"The URL you entered seems to be an external link. Do you want to add the required http:\/\/ prefix?": "입력한 URL은 외부 링크인 것 같습니다. 필수 접두사인 http:\/\/을 추가하시겠습니까?",
"Target": "목표",
"The URL you entered seems to be an email address. Do you want to add the required mailto: prefix?": "입력한 URL은 이메일 주소인 것 같습니다. 필수 접두사인 mailto:을 추가하시겠습니까?",
"Insert\/edit link": "링크 삽입\/편집",
"Insert\/edit video": "동영상 삽입\/편집",
"Poster": "포스터",
"Alternative source": "대체 소스",
"Paste your embed code below:": "아래에 임베드 코드를 붙여 넣으십시오.",
"Insert video": "동영상 삽입",
"Embed": "임베드",
"Nonbreaking space": "줄 바꿈 없는 공백",
"Page break": "페이지 구분",
"Paste as text": "텍스트로 붙여 넣기",
"Preview": "미리 보기",
"Print": "인쇄",
"Save": "저장",
"Could not find the specified string.": "지정된 스트링을 찾을 수 없습니다.",
"Replace": "바꾸기",
"Next": "다음",
"Whole words": "전체 단어",
"Find and replace": "찾기 및 바꾸기",
"Replace with": "바꿀 내용",
"Find": "찾기",
"Replace all": "모두 바꾸기",
"Match case": "대/소문자 구분",
"Prev": "이전",
"Spellcheck": "맞춤법 검사",
"Finish": "완료",
"Ignore all": "모두 무시",
"Ignore": "무시",
"Add to Dictionary": "사전에 추가",
"Insert row before": "앞에 행 삽입",
"Rows": "행",
"Height": "높이",
"Paste row after": "뒤에 행 붙여넣기",
"Alignment": "정렬",
"Border color": "테두리 색상",
"Column group": "열 그룹",
"Row": "행",
"Insert column before": "앞에 열 삽입",
"Split cell": "셀 분할",
"Cell padding": "셀 안쪽 여백",
"Cell spacing": "셀 간격",
"Row type": "행 유형",
"Insert table": "표 삽입",
"Body": "본문",
"Caption": "캡션",
"Footer": "바닥글",
"Delete row": "행 삭제",
"Paste row before": "앞에 행 붙여넣기",
"Scope": "범위",
"Delete table": "표 삭제",
"H Align": "H 정렬",
"Top": "맨 위",
"Header cell": "머리글 셀",
"Column": "열",
"Row group": "행 그룹",
"Cell": "셀",
"Middle": "가운데",
"Cell type": "셀 유형",
"Copy row": "행 복사",
"Row properties": "행 속성",
"Table properties": "표 속성",
"Row group": "행 그룹",
"Bottom": "하단",
"V Align": "V 정렬",
"Header": "머리글",
"Right": "오른쪽",
"Insert column after": "뒤에 열 삽입",
"Cols": "열",
"Insert row after": "뒤에 행 삽입",
"Width": "너비",
"Cell properties": "셀 속성",
"Left": "왼쪽",
"Cut row": "행 잘라내기",
"Delete column": "열 삭제",
"Center": "가운데",
"Merge cells": "셀 병합",
"Insert template": "템플릿 삽입",
"Templates": "템플릿",
"Background color": "배경 색상",
"Custom...": "사용자 정의...",
"Custom color": "사용자 정의 색상",
"No color": "색상 없음",
"Text color": "텍스트 색상",
"Show blocks": "블록 표시",
"Show invisible characters": "보이지 않는 문자 표시",
"Words: {0}": "단어: {0}",
"Insert": "삽입",
"File": "파일",
"Edit": "편집",
"Rich Text Area. Press ALT-F9 for menu. Press ALT-F10 for toolbar. Press ALT-0 for help": "서식 있는 텍스트 영역. 도구 모음을 불러오려면 ALT-F10을 누르고, 도구 모음을 끝내려면 도구 모음 내에서 ESC를 누르십시오.",
"Tools": "도구",
"View": "보기",
"Table": "표",
"Format": "형식"
});
