tinymce.addI18n('nb_NO',{
"Cut": "Klipp ut",
"Heading 5": "Overskrift 5",
"Header 2": "Overskrift 2",
"Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X\/C\/V keyboard shortcuts instead.": "Nettleseren din støtter ikke direkte tilgang til utklippstavlen. Bruk hurtigtastene Ctrl+X\/C\/V i stedet.",
"Heading 4": "Overskrift 4",
"Div": "Diverse",
"Heading 2": "Overskrift 2",
"Paste": "Lim inn",
"Close": "Lukk",
"Font Family": "Skriftfamilie",
"Pre": "Forh.",
"Align Right": "Høyrejuster",
"New document": "Nytt dokument",
"Blockquote": "Blockquote",
"Numbered list": "Nummerert liste",
"Heading 1": "Overskrift 1",
"Headings": "Overskrifter",
"Increase indent": "Øk innrykk",
"Formats": "Formater",
"Headers": "Overskrifter",
"Select all": "Velg alle",
"Header 3": "Overskrift 3",
"Blocks": "Blokker",
"Undo": "Angre",
"Strikethrough": "Gjennomstreking",
"Bullet list": "Punktliste",
"Header 1": "Overskrift 1",
"Superscript": "Hevet skrift",
"Clear formatting": "Tøm formatering",
"Font Sizes": "Skriftstørrelser",
"Subscript": "Senket skrift",
"Header 6": "Overskrift 6",
"Redo": "Gjør om",
"Paragraph": "Avsnitt",
"Ok": "OK",
"Bold": "Fet",
"Code": "Kode",
"Italic": "Kursiv",
"Align Center": "Midtstill loddrett",
"Header 5": "Overskrift 5",
"Heading 6": "Overskrift 6",
"Heading 3": "Overskrift 3",
"Decrease indent": "Reduser innrykk",
"Header 4": "Overskrift 4",
"Paste is now in plain text mode. Contents will now be pasted as plain text until you toggle this option off.": "Lim inn er nå i modus for ren tekst. Innhold limes nå inn som ren tekst helt til du slår av dette alternativet.",
"Underline": "Understreking",
"Cancel": "Avbryt",
"Justify": "Blokkjuster",
"Inline": "Radjuster",
"Copy": "Kopier",
"Align Left": "Venstrejuster",
"Visual aids": "Visuelle hjelpemidler",
"Lower Greek": "små greske bokstaver",
"Square": "Kvadrat",
"Default": "Standard",
"Lower Alpha": "små alfanumeriske tall",
"Circle": "Sirkel",
"Disc": "Plate",
"Upper Alpha": "store alfanumeriske tall",
"Upper Roman": "store romertall",
"Lower Roman": "små romertall",
"Name": "Navn",
"Anchor": "Anker",
"You have unsaved changes are you sure you want to navigate away?": "Du har endringer som ikke er lagret. Er du sikker på at du vil navigere bort likevel?",
"Restore last draft": "Gjenopprett siste utkast",
"Special character": "Spesialtegn",
"Source code": "Kildekode",
"B": "B",
"R": "R",
"G": "G",
"Color": "Farge",
"Right to Left": "Fra høyre mot venstre",
"Left to Right": "Fra venstre mot høyre",
"Emoticons": "Uttrykksikoner",
"Robots": "Roboter",
"Document properties": "Dokumentegenskaper",
"Title": "Tittel",
"Keywords": "Nøkkelord",
"Encoding": "Koding",
"Description": "Beskrivelse",
"Author": "Forfatter",
"Fullscreen": "Fullskjerm",
"Horizontal line": "Vannrett linje",
"Horizontal space": "Vannrett avstand",
"Insert\/edit image": "Sett inn \/ rediger bilde",
"General": "Generelt",
"Advanced": "Avansert",
"Source": "Kilde",
"Border": "Kantlinje",
"Constrain proportions": "Begrens proporsjoner",
"Vertical space": "Loddrett avstand",
"Image description": "Bildebeskrivelse",
"Style": "Stil",
"Dimensions": "Dimensjoner",
"Insert image": "Sett inn bilde",
"Zoom in": "Zoom inn",
"Contrast": "Kontrast",
"Back": "Tilbake",
"Gamma": "Gamma",
"Flip horizontally": "Vend vannrett",
"Resize": "Endre størrelse",
"Sharpen": "Gjør skarpere",
"Zoom out": "Zoom ut",
"Image options": "Bildealternativer",
"Apply": "Bruk",
"Brightness": "Lysstyrke",
"Rotate clockwise": "Roter med klokken",
"Rotate counterclockwise": "Roter mot klokken",
"Edit image": "Rediger bilde",
"Color levels": "Fargenivåer",
"Crop": "Beskjær",
"Orientation": "Retning",
"Flip vertically": "Vend loddrett",
"Invert": "Inverter",
"Insert date\/time": "Sett inn dato\/klokkeslett",
"Remove link": "Fjern kobling",
"Url": "URL-adresse",
"Text to display": "Tekst som skal vises",
"Anchors": "Ankere",
"Insert link": "Sett inn kobling",
"New window": "Nytt vindu",
"None": "Ingen",
"The URL you entered seems to be an external link. Do you want to add the required http:\/\/ prefix?": "Det ser ut til at URL-adressen du skrev inn, er en ekstern kobling. Vil du legge til det nødvendige prefikset http:\/\/?",
"Target": "Mål",
"The URL you entered seems to be an email address. Do you want to add the required mailto: prefix?": "Det ser ut til at URL-adressen du skrev inn, er en e-postadresse. Vil du legge til det nødvendige prefikset mailto:?",
"Insert\/edit link": "Sett inn \/ rediger kobling",
"Insert\/edit video": "Sett inn \/ rediger video",
"Poster": "Plakat",
"Alternative source": "Alternativ kilde",
"Paste your embed code below:": "Lim inn innbyggingskoden din nedenfor:",
"Insert video": "Sett inn video",
"Embed": "Bygg inn",
"Nonbreaking space": "Hardt mellomrom",
"Page break": "Sideskift",
"Paste as text": "Lim inn som tekst",
"Preview": "Forhåndsvisning",
"Print": "Skriv ut",
"Save": "Lagre",
"Could not find the specified string.": "Finner ikke den angitte strengen.",
"Replace": "Erstatt",
"Next": "Neste",
"Whole words": "Hele ord",
"Find and replace": "Søk og erstatt",
"Replace with": "Erstatt med",
"Find": "Finn",
"Replace all": "Erstatt alle",
"Match case": "Skill mellom store og små bokstaver",
"Prev": "Forrige",
"Spellcheck": "Stavekontroll",
"Finish": "Fullfør",
"Ignore all": "Ignorer alle",
"Ignore": "Ignorer",
"Add to Dictionary": "Legg til i ordliste",
"Insert row before": "Sett inn rad foran",
"Rows": "Rader",
"Height": "Høyde",
"Paste row after": "Lim inn rad etter",
"Alignment": "Justering",
"Border color": "Kantlinjefarge",
"Column group": "Kolonnegruppe",
"Row": "Rad",
"Insert column before": "Sett inn kolonne foran",
"Split cell": "Del celle",
"Cell padding": "Celleutfylling",
"Cell spacing": "Celleavstand",
"Row type": "Radtype",
"Insert table": "Sett inn tabell",
"Body": "Tekst",
"Caption": "Bildetekst",
"Footer": "Bunntekst",
"Delete row": "Slett rad",
"Paste row before": "Lim inn rad foran",
"Scope": "Omfang",
"Delete table": "Slett tabell",
"H Align": "H-juster",
"Top": "Øverst",
"Header cell": "Overskriftscelle",
"Column": "Kolonne",
"Row group": "Radgruppe",
"Cell": "Celle",
"Middle": "Midt på",
"Cell type": "Celletype",
"Copy row": "Kopier rad",
"Row properties": "Radegenskaper",
"Table properties": "Tabellegenskaper",
"Bottom": "Nederst",
"V Align": "V-juster",
"Header": "Topptekst",
"Right": "Høyre",
"Insert column after": "Sett inn kolonne etter",
"Cols": "Farger",
"Insert row after": "Sett inn rad etter",
"Width": "Bredde",
"Cell properties": "Celleegenskaper",
"Left": "Venstre",
"Cut row": "Klipp ut rad",
"Delete column": "Slett kolonne",
"Center": "Midtstilt",
"Merge cells": "Slå sammen celler",
"Insert template": "Sett inn mal",
"Templates": "Maler",
"Background color": "Bakgrunnsfarge",
"Custom...": "Egendefinert ...",
"Custom color": "Egendefinert farge",
"No color": "Ingen farge",
"Text color": "Tekstfarge",
"Show blocks": "Vis blokker",
"Show invisible characters": "Vis usynlige tegn",
"Words: {0}": "Ord: {0}",
"Insert": "Sett inn",
"File": "Fil",
"Edit": "Rediger",
"Rich Text Area. Press ALT-F9 for menu. Press ALT-F10 for toolbar. Press ALT-0 for help": "RTF-område. Trykk på ALT-F9 for å vise menyen. Trykk på ALT-F10 for å vise verktøylinjen. Trykk på ALT-0 for å vise Hjelp",
"Tools": "Verktøy",
"View": "Vis",
"Table": "Tabell",
"Format": "Format"
});
