tinymce.addI18n('nl_NL',{
"Cut": "Knippen",
"Heading 5": "Koptekst 5",
"Header 2": "Koptekst 2",
"Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X\/C\/V keyboard shortcuts instead.": "Uw browser ondersteunt geen directe toegang tot het klembord. Gebruik in plaats daarvan de sneltoetsen Ctrl + X\/C\/V.",
"Heading 4": "Koptekst 4",
"Div": "Div",
"Heading 2": "Koptekst 2",
"Paste": "Plakken",
"Close": "Sluiten",
"Font Family": "Lettertypefamilie",
"Pre": "Vooraf",
"Align Right": "Rechts uitlijnen",
"New document": "Nieuw document",
"Blockquote": "Blockquote",
"Numbered list": "Genummerde lijst",
"Heading 1": "Koptekst 1",
"Headings": "Koppen",
"Increase indent": "Inspringing vergroten",
"Formats": "Indelingen",
"Headers": "Koppen",
"Select all": "Alles selecteren",
"Header 3": "Koptekst 3",
"Blocks": "Blokken",
"Undo": "Ongedaan maken",
"Strikethrough": "Doorhalen",
"Bullet list": "Lijst met opsommingstekens",
"Header 1": "Koptekst 1",
"Superscript": "Superscript",
"Clear formatting": "Opmaak wissen",
"Font Sizes": "Tekengroottes",
"Subscript": "Subscript",
"Header 6": "Koptekst 6",
"Redo": "Opnieuw uitvoeren",
"Paragraph": "Alinea",
"Ok": "OK",
"Bold": "Vet",
"Code": "Code",
"Italic": "Cursief",
"Align Center": "Centreren",
"Header 5": "Koptekst 5",
"Heading 6": "Koptekst 6",
"Heading 3": "Koptekst 3",
"Decrease indent": "Inspringing verkleinen",
"Header 4": "Koptekst 4",
"Paste is now in plain text mode. Contents will now be pasted as plain text until you toggle this option off.": "Plakken zonder opmaak. Inhoud wordt zonder opmaak geplakt, totdat u deze optie uitschakelt.",
"Underline": "Onderstrepen",
"Cancel": "Annuleren",
"Justify": "Uitvullen",
"Inline": "Inline",
"Copy": "Kopiëren",
"Align Left": "Links uitvullen",
"Visual aids": "Visuele hulpmiddelen",
"Lower Greek": "Grieks kleine letters",
"Square": "Vierkant",
"Default": "Standaard",
"Lower Alpha": "Alpha kleine letters",
"Circle": "Cirkel",
"Disc": "Disk",
"Upper Alpha": "Alpha hoofdletters",
"Upper Roman": "Romeins hoofdletters",
"Lower Roman": "Romeins kleine letters",
"Name": "Naam",
"Anchor": "Anker",
"You have unsaved changes are you sure you want to navigate away?": "Er zijn niet-opgeslagen wijzigingen. Weet u zeker dat u iets anders wilt bekijken?",
"Restore last draft": "Laatste concept herstellen",
"Special character": "Speciaal teken",
"Source code": "Broncode",
"B": "B",
"R": "R",
"G": "G",
"Color": "Kleur",
"Right to Left": "Van rechts naar links",
"Left to Right": "Van links naar rechts",
"Emoticons": "Emoticons",
"Robots": "Robots",
"Document properties": "Documenteigenschappen",
"Title": "Titel",
"Keywords": "Trefwoorden",
"Encoding": "Codering",
"Description": "Beschrijving",
"Author": "Auteur",
"Fullscreen": "Volledig scherm",
"Horizontal line": "Horizontale lijn",
"Horizontal space": "Horizontale ruimte",
"Insert\/edit image": "Afbeelding invoegen\/bewerken",
"General": "Algemeen",
"Advanced": "Geavanceerd",
"Source": "Bron",
"Border": "Rand",
"Constrain proportions": "Proporties beperken",
"Vertical space": "Verticale ruimte",
"Image description": "Beschrijving van afbeelding",
"Style": "Stijl",
"Dimensions": "Afmetingen",
"Insert image": "Afbeelding invoegen",
"Zoom in": "Inzoomen",
"Contrast": "Contrast",
"Back": "Terug",
"Gamma": "Gamma",
"Flip horizontally": "Horizontaal spiegelen",
"Resize": "Formaat wijzigen",
"Sharpen": "Scherper maken",
"Zoom out": "Uitzoomen",
"Image options": "Opties voor afbeelding",
"Apply": "Toepassen",
"Brightness": "Helderheid",
"Rotate clockwise": "Met de klok mee draaien",
"Rotate counterclockwise": "Tegen de klok in draaien",
"Edit image": "Afbeelding bewerken",
"Color levels": "Kleurniveaus",
"Crop": "Bijsnijden",
"Orientation": "Richting",
"Flip vertically": "Verticaal spiegelen",
"Invert": "Omkeren",
"Insert date\/time": "Datum\/tijd invoegen",
"Remove link": "Link verwijderen",
"Url": "URL",
"Text to display": "Tekst die wordt weergegeven",
"Anchors": "Ankers",
"Insert link": "Koppeling invoegen",
"New window": "Nieuw venster",
"None": "Geen",
"The URL you entered seems to be an external link. Do you want to add the required http:\/\/ prefix?": "De URL die u hebt ingevoerd, lijkt een externe koppeling te zijn. Wilt u het benodigde voorvoegsel http:\/\/ toevoegen?",
"Target": "Doel",
"The URL you entered seems to be an email address. Do you want to add the required mailto: prefix?": "De URL die u hebt ingevoerd, lijkt een extern e-mailadres te zijn. Wilt u het benodigde voorvoegsel mailto: toevoegen?",
"Insert\/edit link": "Koppeling invoeren\/bewerken",
"Insert\/edit video": "Video invoegen\/bewerken",
"Poster": "Poster",
"Alternative source": "Alternatieve bron",
"Paste your embed code below:": "Plak hieronder uw invoegcode:",
"Insert video": "Video invoegen",
"Embed": "Invoegen",
"Nonbreaking space": "Harde spatie",
"Page break": "Pagina-einde",
"Paste as text": "Plakken als tekst",
"Preview": "Voorbeeldweergave",
"Print": "Afdrukken",
"Save": "Opslaan",
"Could not find the specified string.": "Kan de opgegeven reeks niet vinden.",
"Replace": "Vervangen",
"Next": "Volgende",
"Whole words": "Hele woorden",
"Find and replace": "Zoeken en vervangen",
"Replace with": "Vervangen door",
"Find": "Zoeken",
"Replace all": "Alles vervangen",
"Match case": "Identieke hoofdletters\/kleine letters",
"Prev": "Vorige",
"Spellcheck": "Spellingscontrole",
"Finish": "Voltooien",
"Ignore all": "Alles negeren",
"Ignore": "Negeren",
"Add to Dictionary": "Toevoegen aan woordenboek",
"Insert row before": "Rij ervoor invoegen",
"Rows": "Rijen",
"Height": "Hoogte",
"Paste row after": "Rij erna plakken",
"Alignment": "Uitlijning",
"Border color": "Randkleur",
"Column group": "Kolomgroep",
"Row": "Rij",
"Insert column before": "Kolom ervoor invoegen",
"Split cell": "Cel splitsen",
"Cell padding": "Celopvulling",
"Cell spacing": "Celafstand",
"Row type": "Rijtype",
"Insert table": "Tabel invoegen",
"Body": "Hoofdtekst",
"Caption": "Bijschrift",
"Footer": "Voettekst",
"Delete row": "Rij verwijderen",
"Paste row before": "Rij ervoor plakken",
"Scope": "Bereik",
"Delete table": "Tabel verwijderen",
"H Align": "H uitlijnen",
"Top": "Bovenaan",
"Header cell": "Koptekst cel",
"Column": "Kolom",
"Row group": "Rijgroep",
"Cell": "Cel",
"Middle": "Midden",
"Cell type": "Celtype",
"Copy row": "Rij kopiëren",
"Row properties": "Rijeigenschappen",
"Table properties": "Tabeleigenschappen",
"Bottom": "Onderaan",
"V Align": "V uitlijnen",
"Header": "Koptekst",
"Right": "Rechts",
"Insert column after": "Kolom erna invoegen",
"Cols": "Kolommen",
"Insert row after": "Rij erna invoegen",
"Width": "Breedte",
"Cell properties": "Celeigenschappen",
"Left": "Links",
"Cut row": "Rij knippen",
"Delete column": "Kolom verwijderen",
"Center": "Centreren",
"Merge cells": "Cellen samenvoegen",
"Insert template": "Sjabloon invoegen",
"Templates": "Sjablonen",
"Background color": "Achtergrondkleur",
"Custom...": "Aangepast...",
"Custom color": "Aangepaste kleur",
"No color": "Geen kleur",
"Text color": "Tekstkleur",
"Show blocks": "Blokken weergeven",
"Show invisible characters": "Onzichtbare tekens weergeven",
"Words: {0}": "Woorden: {0}",
"Insert": "Invoegen",
"File": "Bestand",
"Edit": "Bewerken",
"Rich Text Area. Press ALT-F9 for menu. Press ALT-F10 for toolbar. Press ALT-0 for help": "Gedeelte Rich Text. Druk op ALT-F9 om het menu te tonen. Druk op ALT-F10 om de taakbalk te tonen. Druk op ALT-0 om de hulppagina te tonen",
"Tools": "Tools",
"View": "Weergeven",
"Table": "Tabel",
"Format": "Indeling"
});
