tinymce.addI18n('pt_BR',{
"Cut": "Recortar",
"Heading 5": "Título 5",
"Header 2": "Cabeçalho 2",
"Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X\/C\/V keyboard shortcuts instead.": "Seu navegador não oferece suporte a acesso direto para a área de transferência. Use os atalhos de teclado Ctrl+X\/C\/V.",
"Heading 4": "Título 4",
"Div": "Div",
"Heading 2": "Título 2",
"Paste": "Colar",
"Close": "Fechar",
"Font Family": "Família de fontes",
"Pre": "Pré",
"Align Right": "Alinhar à direita",
"New document": "Novo documento",
"Blockquote": "Bloquear orçamento",
"Numbered list": "Lista numerada",
"Heading 1": "Título 1",
"Headings": "Títulos",
"Increase indent": "Aumentar avanço",
"Formats": "Formatos",
"Headers": "Cabeçalhos",
"Select all": "Selecionar tudo",
"Header 3": "Cabeçalho 3",
"Blocks": "Bloquear",
"Undo": "Desfazer",
"Strikethrough": "Tachado",
"Bullet list": "Lista de marcadores",
"Header 1": "Cabeçalho 1",
"Superscript": "Sobrescrito",
"Clear formatting": "Limpar formatação",
"Font Sizes": "Tamanhos de fonte",
"Subscript": "Subscrito",
"Header 6": "Cabeçalho 6",
"Redo": "Refazer",
"Paragraph": "Parágrafo",
"Ok": "Ok",
"Bold": "Negrito",
"Code": "Código",
"Italic": "Itálico",
"Align Center": "Alinhar centralizado",
"Header 5": "Cabeçalho 5",
"Heading 6": "Título 6",
"Heading 3": "Título 3",
"Decrease indent": "Diminuir avanço",
"Header 4": "Cabeçalho 4",
"Paste is now in plain text mode. Contents will now be pasted as plain text until you toggle this option off.": "A ferramenta colar agora está no modo de texto simples. Conteúdo será colado como texto simples até você desativar essa opção.",
"Underline": "Sublinhado",
"Cancel": "Cancelar",
"Justify": "Justificar",
"Inline": "Em linha",
"Copy": "Copiar",
"Align Left": "Alinhar à esquerda",
"Visual aids": "Recursos visuais",
"Lower Greek": "Caracteres gregos minúsculos",
"Square": "Quadrado",
"Default": "Padrão",
"Lower Alpha": "Alfa minúsculo",
"Circle": "Círculo",
"Disc": "Disco",
"Upper Alpha": "Alfa maiúsculo",
"Upper Roman": "Romano maiúsculo",
"Lower Roman": "Romano minúsculo",
"Name": "Nome",
"Anchor": "Ancorar",
"You have unsaved changes are you sure you want to navigate away?": "Há alterações não salvas. Deseja sair desta página?",
"Restore last draft": "Restaurar último rascunho",
"Special character": "Caractere especial",
"Source code": "Código-fonte",
"B": "B",
"R": "R",
"G": "G",
"Color": "Cor",
"Right to Left": "Da direita para a esquerda",
"Left to Right": "Da esquerda para a direita",
"Emoticons": "Emoticons",
"Robots": "Robôs",
"Document properties": "Propriedades do documento",
"Title": "Título",
"Keywords": "Palavras-chave",
"Encoding": "Codificação",
"Description": "Descrição",
"Author": "Autor",
"Fullscreen": "Tela inteira",
"Horizontal line": "Linha horizontal",
"Horizontal space": "Espaço horizontal",
"Insert\/edit image": "Inserir\/Editar imagem",
"General": "Geral",
"Advanced": "Avançado",
"Source": "Origem",
"Border": "Borda",
"Constrain proportions": "Proporções de restrição",
"Vertical space": "Espaço vertical",
"Image description": "Descrição da imagem",
"Style": "Estilo",
"Dimensions": "Dimensões",
"Insert image": "Inserir imagem",
"Zoom in": "Ampliar",
"Contrast": "Contraste",
"Back": "Voltar",
"Gamma": "Gama",
"Flip horizontally": "Virar horizontalmente",
"Resize": "Redimensionar",
"Sharpen": "Nitidez",
"Zoom out": "Reduzir",
"Image options": "Opções de imagem",
"Apply": "Aplicar",
"Brightness": "Brilho",
"Rotate clockwise": "Girar no sentido horário",
"Rotate counterclockwise": "Girar no sentido anti-horário",
"Edit image": "Editar imagem",
"Color levels": "Níveis de cor",
"Crop": "Recortar",
"Orientation": "Orientação",
"Flip vertically": "Virar verticalmente",
"Invert": "Inverter",
"Insert date\/time": "Inserir a data/hora",
"Remove link": "Remover link",
"Url": "Url",
"Text to display": "Texto a ser exibido",
"Anchors": "Âncoras",
"Insert link": "Inserir link",
"New window": "Nova janela",
"None": "Nenhuma",
"The URL you entered seems to be an external link. Do you want to add the required http:\/\/ prefix?": "A URL que você digitou parece ser um link externo. Deseja adicionar o prefixo http:\/\/ necessário?",
"Target": "Meta",
"The URL you entered seems to be an email address. Do you want to add the required mailto: prefix?": "A URL que você digitou parece ser um endereço de e-mail. Deseja adicionar o prefixo mailto: necessário?",
"Insert\/edit link": "Inserir\/Editar link",
"Insert\/edit video": "Inserir\/Editar vídeo",
"Poster": "Pôster",
"Alternative source": "Fonte alternativa",
"Paste your embed code below:": "Cole abaixo seu código incorporado:",
"Insert video": "Inserir vídeo",
"Embed": "Inserir",
"Nonbreaking space": "Espaço incondicional",
"Page break": "Quebra de página",
"Paste as text": "Colar como texto",
"Preview": "Visualizar",
"Print": "Imprimir",
"Save": "Salvar",
"Could not find the specified string.": "Não foi possível encontrar a cadeia especificada.",
"Replace": "Substituir",
"Next": "Próximo",
"Whole words": "Palavras inteiras",
"Find and replace": "Localizar e substituir",
"Replace with": "Substituir por",
"Find": "Localizar",
"Replace all": "Substituir tudo",
"Match case": "Corresponder maiúsculas/minúsculas",
"Prev": "Anterior",
"Spellcheck": "Corretor ortográfico",
"Finish": "Concluir",
"Ignore all": "Ignorar tudo",
"Ignore": "Ignorar",
"Add to Dictionary": "Adicionar ao dicionário",
"Insert row before": "Inserir linha antes de",
"Rows": "Linhas",
"Height": "Altura",
"Paste row after": "Colar linha depois de",
"Alignment": "Alinhamento",
"Border color": "Cor da borda",
"Column group": "Grupo de colunas",
"Row": "Linha",
"Insert column before": "Inserir coluna antes de",
"Split cell": "Dividir células",
"Cell padding": "Preenchimento da célula",
"Cell spacing": "Espaçamento da célula",
"Row type": "Tipo de linha",
"Insert table": "Inserir tabela",
"Body": "Corpo",
"Caption": "Legenda",
"Footer": "Rodapé",
"Delete row": "Excluir linha",
"Paste row before": "Colar linha antes de",
"Scope": "Escopo",
"Delete table": "Excluir tabela",
"H Align": "Alinhar h",
"Top": "Superior",
"Header cell": "Célula do cabeçalho",
"Column": "Coluna",
"Row group": "Grupo de linhas",
"Cell": "Célula",
"Middle": "Intermediário",
"Cell type": "Tipo de célula",
"Copy row": "Copiar linha",
"Row properties": "Propriedades da linha",
"Table properties": "Propriedades da tabela",
"Row group": "Grupo de linhas",
"Bottom": "Inferior",
"V Align": "Alinhar v",
"Header": "Cabeçalho",
"Right": "À direita",
"Insert column after": "Inserir coluna depois de",
"Cols": "Colunas",
"Insert row after": "Inserir linha depois de",
"Width": "Largura",
"Cell properties": "Propriedades da célula",
"Left": "À Esquerda",
"Cut row": "Recortar linha",
"Delete column": "Excluir  coluna",
"Center": "Centralizar",
"Merge cells": "Mesclar células",
"Insert template": "Inserir modelo",
"Templates": "Modelos",
"Background color": "Cor do plano de fundo",
"Custom...": "Personalizar...",
"Custom color": "Cor personalizada",
"No color": "Sem cor",
"Text color": "Cor do texto",
"Show blocks": "Mostrar blocos",
"Show invisible characters": "Mostrar caracteres invisíveis",
"Words: {0}": "Palavras: {0}",
"Insert": "Inserir",
"File": "Arquivar",
"Edit": "Editar",
"Rich Text Area. Press ALT-F9 for menu. Press ALT-F10 for toolbar. Press ALT-0 for help": "Área Rich Text Pressione ALT-F10 para entrar na barra de ferramentas e, para sair, pressione ESC.",
"Tools": "Ferramentas",
"View": "Exibir",
"Table": "Tabela",
"Format": "Formato"
});
