tinymce.addI18n('sv_SE',{
"Cut": "Klipp ut",
"Heading 5": "Rubrik 5",
"Header 2": "Rubrik 2",
"Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X\/C\/V keyboard shortcuts instead.": "Din webbläsare stöder inte direkt åtkomst till urklipp. Använd Ctrl+X\/C\/V kortkommandon i stället.",
"Heading 4": "Rubrik 4",
"Div": "Div",
"Heading 2": "Rubrik 2",
"Paste": "Klistra in",
"Close": "Stäng",
"Font Family": "Teckensnittsfamilj",
"Pre": "Före",
"Align Right": "Justera höger",
"New document": "Nytt dokument",
"Blockquote": "Citattext",
"Numbered list": "Numrerad lista",
"Heading 1": "Rubrik 1",
"Headings": "Rubriker",
"Increase indent": "Öka indrag",
"Formats": "Format",
"Headers": "Rubriker",
"Select all": "Markera alla",
"Header 3": "Rubrik 3",
"Blocks": "Block",
"Undo": "Ångra",
"Strikethrough": "Genomstruken",
"Bullet list": "Punktlista",
"Header 1": "Rubrik 1",
"Superscript": "Upphöjd",
"Clear formatting": "Rensa formatering",
"Font Sizes": "Teckenstorlekar",
"Subscript": "Nedsänkt",
"Header 6": "Rubrik 6",
"Redo": "Gör om",
"Paragraph": "Stycke",
"Ok": "Ok",
"Bold": "Fetstil",
"Code": "Kod",
"Italic": "Kursiv",
"Align Center": "Centrera",
"Header 5": "Rubrik 5",
"Heading 6": "Rubrik 6",
"Heading 3": "Rubrik 3",
"Decrease indent": "Minska indrag",
"Header 4": "Rubrik 4",
"Paste is now in plain text mode. Contents will now be pasted as plain text until you toggle this option off.": "Klistra in är nu i läget vanlig text. Innehåll kommer nu att klistras in som vanlig text tills du stänger av det här alternativet.",
"Underline": "Understrykning",
"Cancel": "Avbryt",
"Justify": "Justera",
"Inline": "Rak linje",
"Copy": "Kopiera",
"Align Left": "Justera vänster",
"Visual aids": "Visuella hjälpmedel",
"Lower Greek": "Nedre grekiska",
"Square": "Fyrkant",
"Default": "Standard",
"Lower Alpha": "Nedre Alpha",
"Circle": "Cirkel",
"Disc": "Skiva",
"Upper Alpha": "Övre Alpha",
"Upper Roman": "Övre Roman",
"Lower Roman": "Nedre Roman",
"Name": "Namn",
"Anchor": "Ankare",
"You have unsaved changes are you sure you want to navigate away?": "Du har osparade ändringar, vill du navigera vidare utan att spara?",
"Restore last draft": "Återställa senaste utkast",
"Special character": "Specialtecken",
"Source code": "Källkod",
"B": "B",
"R": "R",
"G": "G",
"Color": "Färg",
"Right to Left": "Höger till vänster",
"Left to Right": "Vänster till höger",
"Emoticons": "Uttryckssymboler",
"Robots": "Robotar",
"Document properties": "Dokumentegenskaper",
"Title": "Rubrik",
"Keywords": "Nyckelord",
"Encoding": "Kodning",
"Description": "Beskrivning",
"Author": "Författare",
"Fullscreen": "Helskärm",
"Horizontal line": "Horisontell linje",
"Horizontal space": "Horisontellt utrymme",
"Insert\/edit image": "Infoga\/redigera bild",
"General": "Allmän",
"Advanced": "Avancerad",
"Source": "Källa",
"Border": "Kantlinje",
"Constrain proportions": "Bibehåll proportioner",
"Vertical space": "Vertikalt utrymme",
"Image description": "Bildbeskrivning",
"Style": "Format",
"Dimensions": "Mått",
"Insert image": "Infoga bild",
"Zoom in": "Zooma in",
"Contrast": "Kontrast",
"Back": "Tillbaka",
"Gamma": "Gamma",
"Flip horizontally": "Vänd vågrätt",
"Resize": "Ändra storlek",
"Sharpen": "Öka skärpa",
"Zoom out": "Zooma ut",
"Image options": "Bildalternativ",
"Apply": "Tillämpa",
"Brightness": "Ljusstyrka",
"Rotate clockwise": "Rotera medurs",
"Rotate counterclockwise": "Rotera moturs",
"Edit image": "Redigera bild",
"Color levels": "Färgnivåer",
"Crop": "Beskär",
"Orientation": "Riktning",
"Flip vertically": "Vänd vertikalt",
"Invert": "Invertera",
"Insert date\/time": "Infoga datum\/tid",
"Remove link": "Ta bort länk",
"Url": "Url",
"Text to display": "Text att visa",
"Anchors": "Ankare",
"Insert link": "Infoga länk",
"New window": "Nytt fönster",
"None": "Ingen",
"The URL you entered seems to be an external link. Do you want to add the required http:\/\/ prefix?": "URL-adressen du angav verkar vara en extern länk. Vill du lägga till det nödvändiga http:\/\/ prefixet?",
"Target": "Mål",
"The URL you entered seems to be an email address. Do you want to add the required mailto: prefix?": "URL-adressen du angav verkar vara en e-postadress. Vill du lägga till det nödvändiga prefixet mailto:?",
"Insert\/edit link": "Infoga\/redigera länk",
"Insert\/edit video": "Infoga\/redigera video",
"Poster": "Poster",
"Alternative source": "Alternativ källa",
"Paste your embed code below:": "Klistra in den inbäddade koden nedan:",
"Insert video": "Infoga video",
"Embed": "Bädda in",
"Nonbreaking space": "Hårt blanksteg",
"Page break": "Sidbrytning",
"Paste as text": "Klistra in som text",
"Preview": "Förhandsgranska",
"Print": "Skriv ut",
"Save": "Spara",
"Could not find the specified string.": "Kunde inte hitta angiven sträng.",
"Replace": "Ersätt",
"Next": "Nästa",
"Whole words": "Hela ord",
"Find and replace": "Sök och ersätt",
"Replace with": "Ersätt med",
"Find": "Sök",
"Replace all": "Ersätt alla",
"Match case": "Matcha gemener/versaler",
"Prev": "Föregående",
"Spellcheck": "Stavningskontroll",
"Finish": "Slutför",
"Ignore all": "Ignorera alla",
"Ignore": "Ignorera",
"Add to Dictionary": "Lägg till i ordbok",
"Insert row before": "Infoga rad före",
"Rows": "Rader",
"Height": "Höjd",
"Paste row after": "Klistra in rad efter",
"Alignment": "Justering",
"Border color": "Kantlinjefärg",
"Column group": "Kolumngrupp",
"Row": "Rad",
"Insert column before": "Infoga kolumn före",
"Split cell": "Dela celler",
"Cell padding": "Cellutfyllnad",
"Cell spacing": "Cellavstånd",
"Row type": "Radtyp",
"Insert table": "Infoga tabell",
"Body": "Brödtext",
"Caption": "Bildtext",
"Footer": "Sidfot",
"Delete row": "Ta bort rad",
"Paste row before": "Klistra in rad före",
"Scope": "Omfattning",
"Delete table": "Ta bort tabell",
"H Align": "H Rikta",
"Top": "Överkant",
"Header cell": "Rubrikcell",
"Column": "Kolumn",
"Row group": "Radgrupp",
"Cell": "Cell",
"Middle": "Mitten",
"Cell type": "Celltyp",
"Copy row": "Kopiera rad",
"Row properties": "Egenskaper för rad",
"Table properties": "Tabellegenskaper",
"Row group": "Radgrupp",
"Bottom": "Nertill",
"V Align": "V Rikta",
"Header": "Rubrik",
"Right": "Höger",
"Insert column after": "Infoga kolumn efter",
"Cols": "Kolumner",
"Insert row after": "Infoga rad efter",
"Width": "Bredd",
"Cell properties": "Egenskaper för cell",
"Left": "Vänster",
"Cut row": "Klipp ut rad",
"Delete column": "Radera kolumn",
"Center": "Centrera",
"Merge cells": "Sammanfoga celler",
"Insert template": "Infoga mall",
"Templates": "Mallar",
"Background color": "Bakgrundsfärg",
"Custom...": "Anpassat ...",
"Custom color": "Anpassad färg",
"No color": "Ingen färg",
"Text color": "Textfärg",
"Show blocks": "Visa block",
"Show invisible characters": "Visa osynliga tecken",
"Words: {0}": "Ord: {0}",
"Insert": "Infoga",
"File": "Fil",
"Edit": "Redigera",
"Rich Text Area. Press ALT-F9 for menu. Press ALT-F10 for toolbar. Press ALT-0 for help": "RTF-område Tryck ALT-F10 för verktygsfält och ESC för att avsluta verktygsfältet när du är i det.",
"Tools": "Verktyg",
"View": "Visa",
"Table": "Tabell",
"Format": "Format"
});
