tinymce.addI18n('tr_TR',{
"Cut": "Kes",
"Heading 5": "Başlık 5",
"Header 2": "Üstbilgi 2",
"Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X\/C\/V keyboard shortcuts instead.": "Tarayıcınız panoya doğrudan erişimi desteklemiyor. Lütfen bunun yerine klavye kısayolları Ctrl+X\C\\'yi kullanın.",
"Heading 4": "Başlık 4",
"Div": "Div",
"Heading 2": "Başlık 2",
"Paste": "Yapıştır",
"Close": "Kapat",
"Font Family": "Yazı Tipi Ailesi",
"Pre": "Öncesi",
"Align Right": "Sağa hizala",
"New document": "Yeni belge",
"Blockquote": "Blockquote",
"Numbered list": "Numaralandırılmış liste",
"Heading 1": "Başlık 1",
"Headings": "Başlıklar",
"Increase indent": "Girintiyi artır",
"Formats": "Biçimler",
"Headers": "Üstbilgiler",
"Select all": "Tümünü seç",
"Header 3": "Üstbilgi 3",
"Blocks": "Bloklar",
"Undo": "Geri Al",
"Strikethrough": "Üstü Çizili",
"Bullet list": "Madde işareti listesi",
"Header 1": "Üstbilgi 1",
"Superscript": "Üst Yazı",
"Clear formatting": "Biçimlendirmeyi temizle",
"Font Sizes": "Yazı Tipi Boyutları",
"Subscript": "Alt Yazı",
"Header 6": "Üstbilgi 6",
"Redo": "Yinele",
"Paragraph": "Paragraf",
"Ok": "Tamam",
"Bold": "Kalın",
"Code": "Kod",
"Italic": "İtalik",
"Align Center": "Ortala",
"Header 5": "Üstbilgi 5",
"Heading 6": "Başlık 6",
"Heading 3": "Başlık 3",
"Decrease indent": "Girintiyi azalt",
"Header 4": "Üstbilgi 4",
"Paste is now in plain text mode. Contents will now be pasted as plain text until you toggle this option off.": "Yapıştır özelliği şu anda düz metin modunda. İçerikler, bu seçenek kapatılana kadar düz metin olarak yapıştırılacaktır.",
"Underline": "Altını Çiz",
"Cancel": "İptal",
"Justify": "Yasla",
"Inline": "Satıriçi",
"Copy": "Kopyala",
"Align Left": "Sola hizala",
"Visual aids": "Görsel yardımcılar",
"Lower Greek": "Lower Greek",
"Square": "Kare",
"Default": "Varsayılan",
"Lower Alpha": "Lower Alpha",
"Circle": "Daire",
"Disc": "Disk",
"Upper Alpha": "Upper Alpha",
"Upper Roman": "Upper Roman",
"Lower Roman": "Lower Roman",
"Name": "Ad",
"Anchor": "Yer işareti",
"You have unsaved changes are you sure you want to navigate away?": "Kaydedilmeyen değişiklikleriniz var, bu sayfadan ayrılmak istediğinizden emin misiniz?",
"Restore last draft": "Son taslağı geri yükle",
"Special character": "Özel karakter",
"Source code": "Kaynak kodu",
"B": "B",
"R": "R",
"G": "G",
"Color": "Renk",
"Right to Left": "Sağdan sola",
"Left to Right": "Soldan sağa",
"Emoticons": "Simgeler",
"Robots": "Robotlar",
"Document properties": "Belge özellikleri",
"Title": "Başlık",
"Keywords": "Anahtar Kelimeler",
"Encoding": "Kodlanıyor",
"Description": "Açıklama",
"Author": "Yazar",
"Fullscreen": "Tam Ekran",
"Horizontal line": "Yatay çizgi",
"Horizontal space": "Yatay boşluk",
"Insert\/edit image": "Görüntü ekle\düzenle",
"General": "Genel",
"Advanced": "Gelişmiş",
"Source": "Kaynak",
"Border": "Kenarlık",
"Constrain proportions": "Oranları kısıtla",
"Vertical space": "Dikey boşluk",
"Image description": "Görüntü açıklaması",
"Style": "Stil",
"Dimensions": "Boyutlar",
"Insert image": "Görüntü ekle",
"Zoom in": "Yakınlaştır",
"Contrast": "Kontrast",
"Back": "Geri",
"Gamma": "Gama",
"Flip horizontally": "Yatay olarak döndür",
"Resize": "Yeniden boyutlandır",
"Sharpen": "Keskinleştir",
"Zoom out": "Uzaklaştır",
"Image options": "Görüntü seçenekleri",
"Apply": "Uygula",
"Brightness": "Parlaklık",
"Rotate clockwise": "Saat yönünde döndür",
"Rotate counterclockwise": "Saat yönünün tersine döndür",
"Edit image": "Görüntüyü düzenle",
"Color levels": "Renk seviyeleri",
"Crop": "Kırp",
"Orientation": "Yönlendirme",
"Flip vertically": "Dikey olarak döndür",
"Invert": "Ters",
"Insert date\/time": "Tarih\saat ekle",
"Remove link": "Bağlantıyı kaldır",
"Url": "Url",
"Text to display": "Görüntülenecek metin",
"Anchors": "Yer işaretleri",
"Insert link": "Bağlantı ekle",
"New window": "Yeni pencere",
"None": "Yok",
"The URL you entered seems to be an external link. Do you want to add the required http:\/\/ prefix?": "Girdiğiniz URL dış bağlantı gibi görünüyor. Gerekli http:\\ önekini eklemek istiyor musunuz?",
"Target": "Hedef",
"The URL you entered seems to be an email address. Do you want to add the required mailto: prefix?": "Girdiğiniz URL bir e-posta adresi gibi görünüyor. Gerekli mailto: önekini eklemek istiyor musunuz?",
"Insert\/edit link": "Bağlantı ekle\düzenle",
"Insert\/edit video": "Video ekle\düzenle",
"Poster": "Poster",
"Alternative source": "Alternatif kaynak",
"Paste your embed code below:": "Ekleme kodunuzu aşağıya yapıştırın:",
"Insert video": "Video ekle",
"Embed": "Ekle",
"Nonbreaking space": "Bölünemez boşluk",
"Page break": "Sayfa sonu",
"Paste as text": "Metin olarak yapıştır",
"Preview": "Önizleme",
"Print": "Yazdır",
"Save": "Kaydet",
"Could not find the specified string.": "Belirtilen dize bulunamadı.",
"Replace": "Değiştir",
"Next": "Sonraki",
"Whole words": "Bütün kelimeler",
"Find and replace": "Bul ve değiştir",
"Replace with": "Şununla değiştir",
"Find": "Bul",
"Replace all": "Tümünü değiştir",
"Match case": "Büyük küçük harfleri eşleştir",
"Prev": "Önceki",
"Spellcheck": "Yazım denetimi",
"Finish": "Bitir",
"Ignore all": "Tümünü yoksay",
"Ignore": "Yoksay",
"Add to Dictionary": "Sözlüğe ekle",
"Insert row before": "Önüne satır ekle",
"Rows": "Sıralar",
"Height": "Yükseklik",
"Paste row after": "Arkasına satır yapıştır",
"Alignment": "Hizalama",
"Border color": "Kenarlık rengi",
"Column group": "Sütun grubu",
"Row": "Satır",
"Insert column before": "Önüne sütun ekle",
"Split cell": "Hücreyi böl",
"Cell padding": "Hücre doldurma",
"Cell spacing": "Hücre aralığı",
"Row type": "Satır türü",
"Insert table": "Tablo ekle",
"Body": "Gövde",
"Caption": "Altyazı",
"Footer": "Altbilgi",
"Delete row": "Satırı sil",
"Paste row before": "Önüne satır yapıştır",
"Scope": "Kapsam",
"Delete table": "Tabloyu sil",
"H Align": "H Hizalama",
"Top": "Üst",
"Header cell": "Üstbilgi hücresi",
"Column": "Sütunu",
"Row group": "Satır grubu",
"Cell": "Hücre",
"Middle": "Orta",
"Cell type": "Hücre türü",
"Copy row": "Satırı kopyala",
"Row properties": "Satır özellikleri",
"Table properties": "Tablo özellikleri",
"Row group": "Satır grubu",
"Bottom": "Alt",
"V Align": "V Hizalama",
"Header": "Üstbilgi",
"Right": "Sağ",
"Insert column after": "Ardından sütun ekle",
"Cols": "Stnlar",
"Insert row after": "Ardından satır ekle",
"Width": "Genişlik",
"Cell properties": "Hücre özellikleri",
"Left": "Sol",
"Cut row": "Satırı kes",
"Delete column": "Sütunu sil",
"Center": "Merkez",
"Merge cells": "Hücreleri birleştir",
"Insert template": "Şablon ekle",
"Templates": "Şablonlar",
"Background color": "Arka plan rengi",
"Custom...": "Özel...",
"Custom color": "Özel renk",
"No color": "Renk yok",
"Text color": "Metin rengi",
"Show blocks": "Blokları göster",
"Show invisible characters": "Görünmez karakterleri göster",
"Words: {0}": "Kelimeler: {0}",
"Insert": "Ekle",
"File": "Dosya",
"Edit": "Düzenle",
"Rich Text Area. Press ALT-F9 for menu. Press ALT-F10 for toolbar. Press ALT-0 for help": "Zengin Metin Alanı. Araç çubuğuna giriş yapmak için ALT+F10 tuşlarına basın, araç çubuğundayken çıkış yapmak için ESC tuşuna basın.",
"Tools": "Araçlar",
"View": "Görüntüle",
"Table": "Tablo",
"Format": "Biçim"
});
