tinymce.addI18n('zh_CN',{
"Cut": "剪切",
"Heading 5": "标题 5",
"Header 2": "页眉 2",
"Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X\/C\/V keyboard shortcuts instead.": "您的浏览器不支持直接访问剪贴板。请使用 Ctrl+X\/C\/V 键盘快捷键代替。",
"Heading 4": "标题 4",
"Div": "Div",
"Heading 2": "标题 2",
"Paste": "粘贴",
"Close": "关闭",
"Font Family": "字体系列",
"Pre": "Pre",
"Align Right": "向右对齐",
"New document": "新文档",
"Blockquote": "引用",
"Numbered list": "编号列表",
"Heading 1": "标题 1",
"Headings": "标题",
"Increase indent": "增加缩进",
"Formats": "格式",
"Headers": "页眉",
"Select all": "全选",
"Header 3": "页眉 3",
"Blocks": "块",
"Undo": "撤销",
"Strikethrough": "删除线",
"Bullet list": "项目符号列表",
"Header 1": "页眉 1",
"Superscript": "上标",
"Clear formatting": "清除格式",
"Font Sizes": "字号",
"Subscript": "下标",
"Header 6": "页眉 6",
"Redo": "恢复",
"Paragraph": "段落",
"Ok": "确定",
"Bold": "粗体",
"Code": "代码",
"Italic": "斜体",
"Align Center": "居中对齐",
"Header 5": "页眉 5",
"Heading 6": "标题 6",
"Heading 3": "标题 3",
"Decrease indent": "减少缩进",
"Header 4": "页眉 4",
"Paste is now in plain text mode. Contents will now be pasted as plain text until you toggle this option off.": "现在是以纯文本模式粘贴。内容现在是以纯文本粘贴，除非您关闭此选项。",
"Underline": "下划线",
"Cancel": "取消",
"Justify": "两端对齐",
"Inline": "内嵌",
"Copy": "复制",
"Align Left": "向左对齐",
"Visual aids": "直观教具",
"Lower Greek": "小写希腊字母",
"Square": "方形",
"Default": "默认值",
"Lower Alpha": "小写字母",
"Circle": "圆形",
"Disc": "光盘",
"Upper Alpha": "大写字母",
"Upper Roman": "大写罗马字母",
"Lower Roman": "小写罗马字母",
"Name": "姓名",
"Anchor": "集合",
"You have unsaved changes are you sure you want to navigate away?": "您有未保存的更改，确实要离开吗？",
"Restore last draft": "恢复上次草稿",
"Special character": "特殊字符",
"Source code": "源代码",
"B": "B",
"R": "R",
"G": "G",
"Color": "颜色",
"Right to Left": "从右向左",
"Left to Right": "从左向右",
"Emoticons": "表情符号",
"Robots": "机器人",
"Document properties": "文档属性",
"Title": "标题",
"Keywords": "关键字",
"Encoding": "编码",
"Description": "描述",
"Author": "作者",
"Fullscreen": "全屏",
"Horizontal line": "横线",
"Horizontal space": "水平空间",
"Insert\/edit image": "插入\/编辑图像",
"General": "常规",
"Advanced": "高级",
"Source": "源",
"Border": "边框",
"Constrain proportions": "约束比例",
"Vertical space": "垂直空间",
"Image description": "图像描述",
"Style": "样式",
"Dimensions": "尺寸",
"Insert image": "插入图像",
"Zoom in": "放大",
"Contrast": "对比",
"Back": "返回",
"Gamma": "γ",
"Flip horizontally": "水平翻转",
"Resize": "调整大小",
"Sharpen": "锐化",
"Zoom out": "缩小",
"Image options": "图像选项",
"Apply": "应用",
"Brightness": "亮度",
"Rotate clockwise": "顺时针旋转",
"Rotate counterclockwise": "逆时针旋转",
"Edit image": "编辑图像",
"Color levels": "色彩层次",
"Crop": "修剪",
"Orientation": "定向",
"Flip vertically": "垂直翻转",
"Invert": "倒置",
"Insert date\/time": "插入日期\/时间",
"Remove link": "移除链接",
"Url": "URL",
"Text to display": "要显示的文本",
"Anchors": "集合",
"Insert link": "插入链接",
"New window": "新窗口",
"None": "无",
"The URL you entered seems to be an external link. Do you want to add the required http:\/\/ prefix?": "您输入的 URL 似乎是一个外部链接。您是否希望添加所需的 http:\/\/ 前缀？",
"Target": "目标",
"The URL you entered seems to be an email address. Do you want to add the required mailto: prefix?": "您输入的 URL 似乎是一个电子邮件地址。您是否希望添加所需的 mailto: 前缀？",
"Insert\/edit link": "插入\/编辑链接",
"Insert\/edit video": "插入\/编辑视频",
"Poster": "海报",
"Alternative source": "备用源",
"Paste your embed code below:": "在下方粘贴您的嵌入代码：",
"Insert video": "插入视频",
"Embed": "嵌入",
"Nonbreaking space": "不间断空格",
"Page break": "分页符",
"Paste as text": "粘贴为文本",
"Preview": "预览",
"Print": "打印",
"Save": "保存",
"Could not find the specified string.": "无法找到指定的字符串。",
"Replace": "替换",
"Next": "下一步",
"Whole words": "整个词",
"Find and replace": "查找并替换",
"Replace with": "替换为",
"Find": "查找",
"Replace all": "全部替换",
"Match case": "区分大小写",
"Prev": "上一步",
"Spellcheck": "拼写检查",
"Finish": "完成",
"Ignore all": "全部忽略",
"Ignore": "忽略",
"Add to Dictionary": "添加到词典",
"Insert row before": "在前面插入行",
"Rows": "行",
"Height": "高度",
"Paste row after": "在后面粘帖行",
"Alignment": "对齐方式",
"Border color": "边框颜色",
"Column group": "列分组",
"Row": "行",
"Insert column before": "在后面插入列",
"Split cell": "拆分单元格",
"Cell padding": "单元格填充",
"Cell spacing": "单元格间距",
"Row type": "行类型",
"Insert table": "插入表格",
"Body": "正文",
"Caption": "标题",
"Footer": "页脚",
"Delete row": "删除行",
"Paste row before": "在前面粘帖行",
"Scope": "范围",
"Delete table": "删除表格",
"H Align": "水平对齐",
"Top": "顶部",
"Header cell": "页眉单元格",
"Column": "列",
"Row group": "行组",
"Cell": "单元格",
"Middle": "中间",
"Cell type": "单元格类型",
"Copy row": "复制行",
"Row properties": "行属性",
"Table properties": "表属性",
"Row group": "行组",
"Bottom": "底部",
"V Align": "垂直对齐",
"Header": "页眉",
"Right": "右对齐",
"Insert column after": "在前面插入列",
"Cols": "列",
"Insert row after": "在后面插入行",
"Width": "宽度",
"Cell properties": "单元格属性",
"Left": "左对齐",
"Cut row": "剪切行",
"Delete column": "删除列",
"Center": "居中",
"Merge cells": "合并单元格",
"Insert template": "插入模板",
"Templates": "模板",
"Background color": "背景颜色",
"Custom...": "自定义……",
"Custom color": "自定义颜色",
"No color": "无颜色",
"Text color": "文本颜色",
"Show blocks": "显示块",
"Show invisible characters": "显示不可见字符",
"Words: {0}": "词： {0}",
"Insert": "插入",
"File": "文件",
"Edit": "编辑",
"Rich Text Area. Press ALT-F9 for menu. Press ALT-F10 for toolbar. Press ALT-0 for help": "富文本区域。按 ALT-F10 可调出工具栏，按 ESC 可从工具栏内退出。",
"Tools": "工具",
"View": "查看",
"Table": "表格",
"Format": "格式"
});
