tinymce.addI18n('zh_TW',{
"Cut": "剪下",
"Heading 5": "標題 5",
"Header 2": "頁首 2",
"Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X\/C\/V keyboard shortcuts instead.": "您的瀏覽器不支援直接存取剪貼簿。請改為使用 Ctrl+X\/C\/V 快速鍵。",
"Heading 4": "標題 4",
"Div": "Div",
"Heading 2": "標題 2",
"Paste": "貼上",
"Close": "關閉",
"Font Family": "字型系列",
"Pre": "Pre",
"Align Right": "靠右對齊",
"New document": "新文件",
"Blockquote": "Blockquote",
"Numbered list": "編號列表",
"Heading 1": "標題 1",
"Headings": "標題",
"Increase indent": "增加縮排",
"Formats": "格式",
"Headers": "頁首",
"Select all": "全選",
"Header 3": "頁首 3",
"Blocks": "區塊",
"Undo": "復原",
"Strikethrough": "刪除線",
"Bullet list": "項目符號清單",
"Header 1": "頁首 1",
"Superscript": "上標",
"Clear formatting": "清除格式設定",
"Font Sizes": "字型大小",
"Subscript": "下標",
"Header 6": "頁首 6",
"Redo": "取消復原",
"Paragraph": "段落",
"Ok": "確定",
"Bold": "粗體",
"Code": "代碼",
"Italic": "斜體",
"Align Center": "置中對齊",
"Header 5": "頁首 5",
"Heading 6": "標題 6",
"Heading 3": "標題 3",
"Decrease indent": "減少縮排",
"Header 4": "頁首 4",
"Paste is now in plain text mode. Contents will now be pasted as plain text until you toggle this option off.": "「貼上」目前是純文字模式。在您將此選項切換成關閉前，內容都將以純文字貼上。",
"Underline": "底線",
"Cancel": "取消",
"Justify": "左右對齊",
"Inline": "內置",
"Copy": "複製",
"Align Left": "靠左對齊",
"Visual aids": "視覺輔助工具",
"Lower Greek": "小寫希臘字母",
"Square": "方形",
"Default": "預設",
"Lower Alpha": "小寫字母",
"Circle": "空心圓",
"Disc": "實心圓",
"Upper Alpha": "大寫字母",
"Upper Roman": "大寫羅馬數字",
"Lower Roman": "小寫羅馬數字",
"Name": "姓名",
"Anchor": "錨點",
"You have unsaved changes are you sure you want to navigate away?": "您有尚未儲存的變更，確定要導覽到他處？",
"Restore last draft": "還原上次草稿",
"Special character": "特殊字元",
"Source code": "原始程式碼",
"B": "B",
"R": "R",
"G": "G",
"Color": "色彩",
"Right to Left": "由右至左",
"Left to Right": "由左至右",
"Emoticons": "表情符號",
"Robots": "機器",
"Document properties": "文件屬性",
"Title": "標題",
"Keywords": "關鍵字",
"Encoding": "編碼",
"Description": "說明",
"Author": "作者",
"Fullscreen": "全螢幕",
"Horizontal line": "水平線",
"Horizontal space": "水平間距",
"Insert\/edit image": "插入\/編輯影像",
"General": "一般",
"Advanced": "進階",
"Source": "來源",
"Border": "邊框",
"Constrain proportions": "強制等比例",
"Vertical space": "垂直間距",
"Image description": "影像說明",
"Style": "樣式",
"Dimensions": "尺寸",
"Insert image": "插入影像",
"Zoom in": "放大",
"Contrast": "對比",
"Back": "返回",
"Gamma": "色差補正",
"Flip horizontally": "水平翻轉",
"Resize": "調整大小",
"Sharpen": "銳利化",
"Zoom out": "縮小",
"Image options": "影像選項",
"Apply": "套用",
"Brightness": "亮度",
"Rotate clockwise": "順時鐘旋轉",
"Rotate counterclockwise": "逆時鐘旋轉",
"Edit image": "編輯影像",
"Color levels": "色階",
"Crop": "裁剪",
"Orientation": "方向",
"Flip vertically": "垂直翻轉",
"Invert": "反轉",
"Insert date\/time": "插入日期\/時間",
"Remove link": "移除連結",
"Url": "Url",
"Text to display": "要顯示的文字",
"Anchors": "錨點",
"Insert link": "插入連結",
"New window": "新視窗",
"None": "無",
"The URL you entered seems to be an external link. Do you want to add the required http:\/\/ prefix?": "您輸入的 URL 似乎是外部連結。是否要新增必要的 http:\/\/ 前置詞？",
"Target": "目標",
"The URL you entered seems to be an email address. Do you want to add the required mailto: prefix?": "您輸入的 URL 似乎是電子郵件地址。是否要新增必要的 mailto: 前置詞？",
"Insert\/edit link": "插入\/編輯連結",
"Insert\/edit video": "插入\/編輯視訊",
"Poster": "海報",
"Alternative source": "其他資源",
"Paste your embed code below:": "在下方貼上內嵌程式碼：",
"Insert video": "插入視訊",
"Embed": "內嵌",
"Nonbreaking space": "不分行空格",
"Page break": "分頁",
"Paste as text": "以文字形式貼上",
"Preview": "預覽",
"Print": "列印",
"Save": "儲存",
"Could not find the specified string.": "找不到指定的字串。",
"Replace": "取代",
"Next": "下一步",
"Whole words": "全字拼寫須相符",
"Find and replace": "尋找及取代",
"Replace with": "取代成",
"Find": "尋找",
"Replace all": "全部取代",
"Match case": "大小寫須相符",
"Prev": "上一個",
"Spellcheck": "拼字檢查",
"Finish": "完成",
"Ignore all": "全部忽略",
"Ignore": "忽略",
"Add to Dictionary": "新增至字典",
"Insert row before": "插入列，前於",
"Rows": "列",
"Height": "高度",
"Paste row after": "貼上列，後於",
"Alignment": "對齊",
"Border color": "邊框色彩",
"Column group": "欄群組",
"Row": "列",
"Insert column before": "插入欄，前於",
"Split cell": "分割儲存格",
"Cell padding": "儲存格填補值",
"Cell spacing": "儲存格間距",
"Row type": "列類型",
"Insert table": "插入表格",
"Body": "本文",
"Caption": "標題",
"Footer": "頁尾",
"Delete row": "刪除列",
"Paste row before": "貼上列，前於",
"Scope": "範圍",
"Delete table": "刪除表格",
"H Align": "水平對齊",
"Top": "頂端",
"Header cell": "頁首儲存格",
"Column": "欄",
"Row group": "列群組",
"Cell": "儲存格",
"Middle": "中間",
"Cell type": "儲存格類型",
"Copy row": "複製列",
"Row properties": "資料列內容",
"Table properties": "表格內容",
"Row group": "列群組",
"Bottom": "底端",
"V Align": "垂直對齊",
"Header": "頁首",
"Right": "靠右",
"Insert column after": "插入欄，後於",
"Cols": "欄",
"Insert row after": "插入列，後於",
"Width": "寬度",
"Cell properties": "儲存格內容",
"Left": "靠左",
"Cut row": "剪下列",
"Delete column": "刪除欄",
"Center": "置中",
"Merge cells": "合併儲存格",
"Insert template": "插入範本",
"Templates": "範本",
"Background color": "背景色彩",
"Custom...": "自訂...",
"Custom color": "自訂色彩",
"No color": "無色彩",
"Text color": "文字色彩",
"Show blocks": "顯示區塊",
"Show invisible characters": "顯示不可見的字元",
"Words: {0}": "字數： {0}",
"Insert": "插入",
"File": "檔案",
"Edit": "編輯",
"Rich Text Area. Press ALT-F9 for menu. Press ALT-F10 for toolbar. Press ALT-0 for help": "Rich Text 區域。按下 ALT-F10 以存取工具列，按下 ESC 離開已進入的工具列。",
"Tools": "工具",
"View": "檢視",
"Table": "表格",
"Format": "格式"
});
