tinymce.addI18n('ar_SA',{
"Add Image": "SA Add Image",
"Insert Stuff": "SA Insert Stuff",
"Add Link": "SA Add Link",
"Graphical equation": "SA GE",
"Graphical equation placeholder": "SA GE Placeholder",
"MathML equation": "SA MathML equation",
"MathML equation placeholder": "SA MathML equation",
"Insert stuff placeholder": "SA Insert stuff placeholder",
"Ordered List": "SA Ordered List",
"Indent": "SA Indent",
"Outdent": "SA Outdent",
"Align Full": "SA Align Full",
"Row": "SA Row",
"Address": "SA Address",
"Preformatted": "SA Preformatted",
"HTML Source Editor": "SA HTML Source Editor",
"Close Full Screen Editor": "SA Close Full Screen Editor",
"Open in Full Screen Editor": "SA Open in Full Screen Editor",
"Add Attributes": "SA Add Attributes"
});
