//D2L specific strings

tinymce.addI18n('ar_SA',{
"Add Image": "إضافة صورة",
"Insert Stuff": "إدراج الأغراض",
"More Text Styles": "المزيد من أنماط النص",
"More Insert Options": "المزيد من خيارات الإدراج",
"More Paragraph Formatting": "المزيد من خيارات تنسيق الفقرة",
"Add Link": "إضافة ارتباط",
"Graphical equation": "معادلة رسومية",
"Graphical": "رسومية",
"MathML equation": "معادلة MathML",
"MathML": "MathML",
"LaTeX equation": "معادلة LaTeX",
"LaTeX": "LaTeX",
"equation preview image": "معاينة صورة المعادلة",
"Insert stuff placeholder": "عنصر نائب لإدراج الأغراض",
"Ordered List": "لائحة مرتبة",
"Indent": "مسافة بادئة",
"Outdent": "تحريك إلى مستوى أعلى",
"Align Full": "محاذاة كاملة",
"Address": "العنوان",
"Preformatted": "منسّق مسبقًا",
"HTML Source Editor": "محرر مصدر HTML",
"Close Full Screen Editor": "إغلاق المحرر في وضع ملء الشاشة",
"Open in Full Screen Editor": "فتح المحرر في وضع ملء الشاشة",
"Add Attributes": "إضافة سمات",
"Press ALT-F10 for toolbar, and press ESC to exit toolbar once inside": "اضغط على ALT-F10 لفتح شريط الأدوات، واضغط على ESC للخروج من شريط الأدوات عندما يكون مفتوحًا",

// a11ychecker plugin
"Accessibility Checker": "أداة التحقق من الوصول",
"Check Accessibility": "التحقق من الوصول",
"No accessibility issues detected.": "لم يتم اكتشاف أي مشاكل في الوصول.",
"Issue ": "المشكلة ",
" of ": " من ",
"Images must have alternative text.": "يجب أن تحتوي الصور على نص بديل.",
"Add alternative text:": "إضافة نص بديل:",
"Text cannot be empty.": "لا يمكن أن يكون النص فارغًا.",
"Text cannot be the same as the filename.": "لا يمكن أن يكون النص هو نفس اسم الملف.",
"Alternative text must not be the same as the image filename.": "يجب ألا يكون النص البديل هو نفس اسم ملف الصورة.",
"Tables must have captions.": "يجب أن تحتوي الجداول على تسميات توضيحية.",
"Set table caption:": "تعيين التسمية التوضيحية للجدول:",
"Caption cannot be empty.": "لا يمكن أن تكون التسمية التوضيحية فارغة.",
"Caption cannot be the same as the summary.": "لا يمكن أن تكون التسمية التوضيحية هي نفس الملخص.",
"Complex tables should have summaries.": "يجب أن تحتوي الجداول المعقدة على ملخصات.",
"Set table summary.": "قم بتعيين ملخص الجدول.",
"Summary cannot be empty.": "لا يمكن أن يكون الملخص فارغًا.",
"Table summary cannot be the same as table caption.": "لا يمكن أن يكون ملخص الجدول هو نفس تسمية الجدول التوضيحية.",
"Table caption and summary cannot have the same value.": "لا يمكن أن تكون قيمة التسمية التوضيحية للجدول هي نفس قيمة الملخص.",
"Tables must contain rows and cells.": "يجب أن تحتوي الجداول على صفوف وأعمدة.",
"Tables must have at least one header.": "يجب أن تحتوي الجداول على رأس واحد على الأقل.",
"Set table header:": "تعيين رأس الجدول:",
"Header Row": "صف الرأس",
"Header Column": "عمود الرأس",
"Table headers must be associated with cells.": "يجب أن تقترن رؤوس الجدول بالخلايا.",
"Set header scope:": "تعيين نطاق الرأس:",
"Row": "الصف",
"Column": "العمود",
"Row Group": "مجموعة الصفوف",
"Column Group": "مجموعة الأعمدة",
"Paragraph cannot be used in place of heading.": "لا يمكن أن تُستخدم الفقرة مكان العنوان.",
"Choose a heading level:": "اختيار مستوى العنوان:",
"Heading 1": "العنوان 1",
"Heading 2": "العنوان 2",
"Heading 3": "العنوان 3",
"Heading 4": "العنوان 4",
"Heading 5": "العنوان 5",
"Heading 6": "العنوان 6",
"Heading order must be sequential.": "يجب أن يكون ترتيب العناوين متتاليًا.",
"Adjacent links should be merged.": "يجب دمج الارتباطات المجاورة.",
"Use list markup for lists.": "استخدم علامات القائمة للقوائم.",
"Large text must have a contrast ratio of at least 3:1.": "يجب أن يتمتع النص الكبير بنسبة تباين لا تقل عن 3:1.",
"Visual presentation must have a contrast ratio of at least 4.5:1.": "يجب أن يتمتع العرض التقديمي المرئي بنسبة تباين لا تقل عن 4.5:1."
});
