//D2L specific strings

tinymce.addI18n('da_DK', {
    "Add Image": "Tilføj billede",
    "Insert Stuff": "Indsæt noget",
    "More Text Styles": "Flere teksttyper",
    "More Insert Options": "Flere indstillinger for indsættelse",
    "More Paragraph Formatting": "Mere afsnitsformatering",
    "Add Link": "Tilføj link",
    "Graphical equation": "Grafisk ligning",
    "Graphical": "Grafisk",
    "Chemistry equation": "Kemisk ligning",
    "MathML equation": "MathML-ligning",
    "MathML": "MathML",
    "LaTeX equation": "LaTeX-ligning",
    "LaTeX": "LaTeX",
    "equation preview image": "billede med eksempel på ligning",
    "Insert stuff placeholder": "Pladsholder for indsættelse af noget",
    "Ordered List": "Sorteret liste",
    "Indent": "Ryk ind",
    "Outdent": "Ryk ud",
    "Align Full": "Juster fuld størrelse",
    "Address": "Adresse",
    "Preformatted": "Forudformateret",
    "HTML Source Editor": "Editor til HTML-kilde",
    "Close Full Screen Editor": "Luk redigeringsprogrammet for fuld skærm",
    "Open in Full Screen Editor": "Åbn i redigeringsprogrammet for fuld skærm",
    "Add Attributes": "Tilføj attributter",
    "Press ALT-F10 for toolbar, and press ESC to exit toolbar once inside": "Tryk på Alt-F10 for værktøjslinjen, og tryk på ESC for at afslutte værktøjslinjen, når du er derinde",
    "Emoticons": "Humørikoner",

    // a11ychecker plugin
    "Accessibility Checker": "Tilgængelighedskontrol",
    "Check Accessibility": "Kontrollér tilgængelighed",
    "No accessibility issues detected.": "Ingen tilgængelighedsproblemer fundet.",
    "Issue ": "Udsted ",
    " of ": " af ",
    "Images must have alternative text.": "Billeder skal have alternativ tekst.",
    "Add alternative text:": "Tilføj alternativ tekst:",
    "Text cannot be empty.": "Tekst må ikke være tom.",
    "Text cannot be the same as the filename.": "Tekst kan ikke være det samme som filnavnet.",
    "Alternative text must not be the same as the image filename.": "Alternativ tekst må ikke være den samme som billedets filnavn.",
    "Tables must have captions.": "Tabeller skal have billedtekster.",
    "Set table caption:": "Angiv billedtekst for tabel:",
    "Caption cannot be empty.": "Billedtekst kan ikke være tom.",
    "Caption cannot be the same as the summary.": "Billedtekst kan ikke være den samme som oversigten.",
    "Complex tables should have summaries.": "Komplekse tabeller skal have oversigter.",
    "Set table summary.": "Angiv tabeloversigt.",
    "Summary cannot be empty.": "Oversigt kan ikke være tom.",
    "Table summary cannot be the same as table caption.": "Tabeloversigt kan ikke være den samme som tabelbilledtekst.",
    "Table caption and summary cannot have the same value.": "Tabelbilledtekst og oversigt kan ikke have den samme værdi.",
    "Tables must contain rows and cells.": "Tabeller skal indeholde rækker og celler.",
    "Tables must have at least one header.": "Tabeller skal have mindst én overskrift.",
    "Set table header:": "Angiv tabeloverskrift:",
    "Header Row": "Overskriftsrække",
    "Header Column": "Overskriftskolonne",
    "Table headers must be associated with cells.": "Tabeloverskrifter skal tilknyttes celler.",
    "Set header scope:": "Angiv overskriftens omfang:",
    "Row": "Række",
    "Column": "Kolonne",
    "Row Group": "Rækkegruppe",
    "Column Group": "Kolonnegruppe",
    "Paragraph cannot be used in place of heading.": "Afsnit kan ikke anvendes i stedet for overskrift.",
    "Choose a heading level:": "Vælg et overskriftsniveau:",
    "Heading 1": "Overskrift 1",
    "Heading 2": "Overskrift 2",
    "Heading 3": "Overskrift 3",
    "Heading 4": "Overskrift 4",
    "Heading 5": "Overskrift 5",
    "Heading 6": "Overskrift 6",
    "Heading order must be sequential.": "Overskriftsrækkefølgen skal være fortløbende.",
    "Adjacent links should be merged.": "Tilstødende links skal flettes.",
    "Use list markup for lists.": "Brug listekode for lister.",
    "Large text must have a contrast ratio of at least 3:1.": "Stor tekst skal have et kontrastforhold på mindst 3:1.",
    "Visual presentation must have a contrast ratio of at least 4.5:1.": "Visuel præsentation skal have et kontrastforhold på mindst 4,5:1.",
    "Next": "Næste",
    "Close": "Luk",

    // d2l-emoticons plugin
    "blue funster": "blå funster",
    "celebrate": "fest",
    "heart": "hjerte",
    "red funster": "rød funster",
    "star": "stjerne",
    "sunshine": "solskin",

    "blush with light skin tone": "rødmer med lys hud",
    "cool with light skin tone": "cool med lys hud",
    "goofy with light skin tone": "fjoget med lys hud",
    "happy with light skin tone": "glad med lys hud",
    "joy with light skin tone": "glæde med lys hud",
    "love eyes with light skin tone": "kærlighed i øjnene med lys hud",
    "star eyes with light skin tone": "stjerner i øjnene med lys hud",
    "thinking with light skin tone": "tænksom med lys hud",
    "thumbs up with light skin tone": "godt gået med lys hud",
    "wink with light skin tone": "blinker med øjet med lys hud",
    "wow with light skin tone": "begejstret med lys hud",
    "upside down with light skin tone": "på hovedet med lys hud",

    "blush with dark skin tone": "rødmer med mørk hud",
    "cool with dark skin tone": "cool med mørk hud",
    "goofy with dark skin tone": "fjoget med mørk hud",
    "happy with dark skin tone": "glad med mørk hud",
    "joy with dark skin tone": "glæde med mørk hud",
    "love eyes with dark skin tone": "kærlighed i øjnene med mørk hud",
    "star eyes with dark skin tone": "stjerner i øjnene med mørk hud",
    "thinking with dark skin tone": "tænksom med mørk hud",
    "thumbs up with dark skin tone": "godt gået med mørk hud",
    "wink with dark skin tone": "blinker med mørk hud",
    "wow with dark skin tone": "begejstret med mørk hud",
    "upside down with dark skin tone": "på hovedet med mørk hud"
  });
