//D2L specific strings

tinymce.addI18n('de_DE',{
"Add Image": "Bild hinzufügen",
"Insert Stuff": "Elemente einfügen",
"More Text Styles": "Weitere Textarten",
"More Insert Options": "Mehr Einfügeoptionen",
"More Paragraph Formatting": "Mehr Absatzformatierungen",
"Add Link": "Link hinzufügen",
"Graphical equation": "Grafische Formel",
"Graphical": "Grafisch",
"MathML equation": "MathML-Formel",
"MathML": "MathML",
"LaTeX equation": "LaTeX-Formel",
"LaTeX": "LaTeX",
"equation preview image": "Formel-Vorschaubild",
"Insert stuff placeholder": "Platzhalter für Elemente einfügen",
"Ordered List": "Sortierte Liste",
"Indent": "Einzug",
"Outdent": "Negativer Einzug",
"Align Full": "Vollständig anpassen",
"Address": "Adresse",
"Preformatted": "Vorformatiert",
"HTML Source Editor": "HTML-Quellcode-Editor",
"Close Full Screen Editor": "Vollbildmodus-Editor schließen",
"Open in Full Screen Editor": "Im Vollbildmodus-Editor öffnen",
"Add Attributes": "Attribute hinzufügen",
"Press ALT-F10 for toolbar, and press ESC to exit toolbar once inside": "Drücken Sie ALT-F10, um die Symbolleiste zu öffnen, und drücken Sie die ESC-Taste, um die Symbolleiste wieder zu schließen.",

// a11ychecker plugin
"Accessibility Checker": "Zugriffsprüfung",
"Check Accessibility": "Zugriff prüfen",
"No accessibility issues detected.": "Keine Zugriffsprobleme gefunden.",
"Issue ": "Ausstellen ",
" of ": " von ",
"Images must have alternative text.": "Bilder müssen einen Alternativtext enthalten.",
"Add alternative text:": "Alternativtext hinzufügen:",
"Text cannot be empty.": "Text darf nicht leer sein.",
"Text cannot be the same as the filename.": "Text darf nicht mit dem Dateinamen identisch sein.",
"Alternative text must not be the same as the image filename.": "Alternativtext darf nicht identisch mit dem Dateinamen des Bildes sein.",
"Tables must have captions.": "Tabellen müssen Überschriften enthalten.",
"Set table caption:": "Tabellenüberschrift festlegen:",
"Caption cannot be empty.": "Beschriftung darf nicht leer sein.",
"Caption cannot be the same as the summary.": "Beschriftung darf nicht mit der Übersicht identisch sein.",
"Complex tables should have summaries.": "Komplexe Tabellen sollten Übersichten enthalten.",
"Set table summary.": "Tabellenübersicht festlegen.",
"Summary cannot be empty.": "Übersicht darf nicht leer sein.",
"Table summary cannot be the same as table caption.": "Tabellenübersicht darf nicht mit der Tabellenüberschrift identisch sein.",
"Table caption and summary cannot have the same value.": "Tabellenüberschrift und Übersicht dürfen nicht den gleichen Wert haben.",
"Tables must contain rows and cells.": "Tabellen müssen Zeilen und Zellen enthalten.",
"Tables must have at least one header.": "Die Tabelle muss mindestens eine Überschrift enthalten.",
"Set table header:": "Tabellenüberschrift festlegen:",
"Header Row": "Zeilenüberschrift",
"Header Column": "Spaltenüberschrift",
"Table headers must be associated with cells.": "Tabellenüberschriften müssen den Zellen zugewiesen werden.",
"Set header scope:": "Überschriftsbereich festlegen:",
"Row": "Zeile",
"Column": "Spalte",
"Row Group": "Zeilengruppe",
"Column Group": "Spaltengruppe",
"Paragraph cannot be used in place of heading.": "Absatz kann nicht anstelle der Überschrift verwendet werden.",
"Choose a heading level:": "Wählen Sie eine Überschriftsebene aus:",
"Heading 1": "Überschrift 1",
"Heading 2": "Überschrift 2",
"Heading 3": "Überschrift 3",
"Heading 4": "Überschrift 4",
"Heading 5": "Überschrift 5",
"Heading 6": "Überschrift 6",
"Heading order must be sequential.": "Reihenfolge der Überschrift muss sequenziell sein.",
"Adjacent links should be merged.": "Nebeneinanderstehende Links sollten zusammengeführt werden.",
"Use list markup for lists.": "Verwenden von Listen-Markup für Listen.",
"Large text must have a contrast ratio of at least 3:1.": "Große Schrift muss ein Kontrastverhältnis von mindestens 3:1 haben.",
"Visual presentation must have a contrast ratio of at least 4.5:1.": "Visuelle Präsentation muss ein Kontrastverhältnis von mindestens 4,5:1 haben."
});
