//D2L specific strings

tinymce.addI18n('de_DE',{
"Add Image": "Bild hinzufügen",
"Insert Stuff": "Elemente einfügen",
"More Text Styles": "Weitere Textarten",
"More Insert Options": "Mehr Einfügeoptionen",
"More Paragraph Formatting": "Mehr Absatzformatierungen",
"Add Link": "Link hinzufügen",
"Graphical equation": "Grafische Formel",
"Graphical": "Grafisch",
"Chemistry equation": "Chemische Gleichung",
"MathML equation": "MathML-Formel",
"MathML": "MathML",
"LaTeX equation": "LaTeX-Formel",
"LaTeX": "LaTeX",
"equation preview image": "Formel-Vorschaubild",
"Insert stuff placeholder": "Platzhalter für Elemente einfügen",
"Ordered List": "Sortierte Liste",
"Indent": "Einzug",
"Outdent": "Negativer Einzug",
"Align Full": "Vollständig anpassen",
"Address": "Adresse",
"Preformatted": "Vorformatiert",
"HTML Source Editor": "HTML-Quellcode-Editor",
"Close Full Screen Editor": "Vollbildmodus-Editor schließen",
"Open in Full Screen Editor": "Im Vollbildmodus-Editor öffnen",
"Add Attributes": "Attribute hinzufügen",
"Press ALT-F10 for toolbar, and press ESC to exit toolbar once inside": "Drücken Sie ALT-F10, um die Symbolleiste zu öffnen, und drücken Sie die ESC-Taste, um die Symbolleiste wieder zu schließen.",
"Emoticons": "Emoticons",

// a11ychecker plugin
"Accessibility Checker": "Zugriffsprüfung",
"Check Accessibility": "Zugriff prüfen",
"No accessibility issues detected.": "Keine Zugriffsprobleme gefunden.",
"Issue ": "Ausstellen ",
" of ": " von ",
"Images must have alternative text.": "Bilder müssen einen Alternativtext enthalten.",
"Add alternative text:": "Alternativtext hinzufügen:",
"Text cannot be empty.": "Text darf nicht leer sein.",
"Text cannot be the same as the filename.": "Text darf nicht mit dem Dateinamen identisch sein.",
"Alternative text must not be the same as the image filename.": "Alternativtext darf nicht identisch mit dem Dateinamen des Bildes sein.",
"Tables must have captions.": "Tabellen müssen Überschriften enthalten.",
"Set table caption:": "Tabellenüberschrift festlegen:",
"Caption cannot be empty.": "Beschriftung darf nicht leer sein.",
"Caption cannot be the same as the summary.": "Beschriftung darf nicht mit der Übersicht identisch sein.",
"Complex tables should have summaries.": "Komplexe Tabellen sollten Übersichten enthalten.",
"Set table summary.": "Tabellenübersicht festlegen.",
"Summary cannot be empty.": "Übersicht darf nicht leer sein.",
"Table summary cannot be the same as table caption.": "Tabellenübersicht darf nicht mit der Tabellenüberschrift identisch sein.",
"Table caption and summary cannot have the same value.": "Tabellenüberschrift und Übersicht dürfen nicht den gleichen Wert haben.",
"Tables must contain rows and cells.": "Tabellen müssen Zeilen und Zellen enthalten.",
"Tables must have at least one header.": "Die Tabelle muss mindestens eine Überschrift enthalten.",
"Set table header:": "Tabellenüberschrift festlegen:",
"Header Row": "Zeilenüberschrift",
"Header Column": "Spaltenüberschrift",
"Table headers must be associated with cells.": "Tabellenüberschriften müssen den Zellen zugewiesen werden.",
"Set header scope:": "Überschriftsbereich festlegen:",
"Row": "Zeile",
"Column": "Spalte",
"Row Group": "Zeilengruppe",
"Column Group": "Spaltengruppe",
"Paragraph cannot be used in place of heading.": "Absatz kann nicht anstelle der Überschrift verwendet werden.",
"Choose a heading level:": "Wählen Sie eine Überschriftsebene aus:",
"Heading 1": "Überschrift 1",
"Heading 2": "Überschrift 2",
"Heading 3": "Überschrift 3",
"Heading 4": "Überschrift 4",
"Heading 5": "Überschrift 5",
"Heading 6": "Überschrift 6",
"Heading order must be sequential.": "Reihenfolge der Überschrift muss sequenziell sein.",
"Adjacent links should be merged.": "Nebeneinanderstehende Links sollten zusammengeführt werden.",
"Use list markup for lists.": "Verwenden von Listen-Markup für Listen.",
"Large text must have a contrast ratio of at least 3:1.": "Große Schrift muss ein Kontrastverhältnis von mindestens 3:1 haben.",
"Visual presentation must have a contrast ratio of at least 4.5:1.": "Visuelle Präsentation muss ein Kontrastverhältnis von mindestens 4,5:1 haben.",

// d2l-emoticons plugin
"blue funster": "Funster blau",
"celebrate": "Feiern",
"heart": "Herz",
"red funster": "Funster rot",
"star": "Stern",
"sunshine": "Sonnenschein",

"blush with light skin tone": "Erröten mit heller Haut",
"cool with light skin tone": "Cool mit heller Haut",
"goofy with light skin tone": "Albern mit heller Haut",
"happy with light skin tone": "Glücklich mit heller Haut",
"joy with light skin tone": "Freude mit heller Haut",
"love eyes with light skin tone": "Liebesaugen mit heller Haut",
"star eyes with light skin tone": "Sternaugen mit heller Haut",
"thinking with light skin tone": "Nachdenken mit heller Haut",
"thumbs up with light skin tone": "Daumen hoch mit heller Haut",
"wink with light skin tone": "Zwinkern mit heller Haut",
"wow with light skin tone": "Wow mit heller Haut",
"upside down with light skin tone": "Auf dem Kopf mit heller Haut",

"blush with dark skin tone": "Erröten mit dunkler Haut",
"cool with dark skin tone": "Cool mit dunkler Haut",
"goofy with dark skin tone": "Albern mit dunkler Haut",
"happy with dark skin tone": "Glücklich mit dunkler Haut",
"joy with dark skin tone": "Freude mit dunkler Haut",
"love eyes with dark skin tone": "Liebesaugen mit dunkler Haut",
"star eyes with dark skin tone": "Sternaugen mit dunkler Haut",
"thinking with dark skin tone": "Nachdenken mit dunkler Haut",
"thumbs up with dark skin tone": "Daumen hoch mit dunkler Haut",
"wink with dark skin tone": "Zwinkern mit dunkler Haut",
"wow with dark skin tone": "Wow mit dunkler Haut",
"upside down with dark skin tone": "Auf dem Kopf mit dunkler Haut"
});
