//D2L specific strings

tinymce.addI18n('en_CA',{
"Add Image": "Add Image",
"Insert Stuff": "Insert Stuff",
"More Text Styles": "More Text Styles",
"More Insert Options": "More Insert Options",
"More Paragraph Formatting": "More Paragraph Formatting",
"Add Link": "Add Link",
"Graphical equation": "Graphical equation",
"Graphical equation placeholder": "Graphical equation placeholder",
"MathML equation": "MathML equation",
"MathML equation placeholder": "MathML equation placeholder",
"Insert stuff placeholder": "Insert stuff placeholder",
"Ordered List": "Ordered List",
"Indent": "Indent",
"Outdent": "Outdent",
"Align Full": "Align Full",
"Address": "Address",
"Preformatted": "Preformatted",
"HTML Source Editor": "HTML Source Editor",
"Close Full Screen Editor": "Close Full Screen Editor",
"Open in Full Screen Editor": "Open in Full Screen Editor",
"Add Attributes": "Add Attributes",
"Press ALT-F10 for toolbar, and press ESC to exit toolbar once inside": "Press ALT-F10 for toolbar, and press ESC to exit toolbar once inside",

// a11ychecker plugin
"Accessibility Checker": "Accessibility Checker",
"No accessibility issues detected.": "No accessibility issues detected.",
"Issue ": "Issue ",
" of ": " of ",
"Images must have alternative text.": "Images must have alternative text.",
"Add alternative text:": "Add alternative text:",
"Text cannot be empty.": "Text cannot be empty.",
"Text cannot be the same as the filename.": "Text cannot be the same as the filename.",
"Alternative text must not be the same as the image filename.": "Alternative text must not be the same as the image filename.",
"Tables must have captions.": "Tables must have captions.",
"Set table caption:": "Set table caption:",
"Caption cannot be empty.": "Caption cannot be empty.",
"Caption cannot be the same as the summary.": "Caption cannot be the same as the summary.",
"Complex tables should have summaries.": "Complex tables should have summaries.",
"Set table summary.": "Set table summary.",
"Summary cannot be empty.": "Summary cannot be empty.",
"Table summary cannot be the same as table caption.": "Table summary cannot be the same as table caption.",
"Table caption and summary cannot have the same value.": "Table caption and summary cannot have the same value.",
"Tables must contain rows and cells.": "Tables must contain rows and cells.",
"Tables must have at least one header.": "Tables must have at least one header.",
"Set table header:": "Set table header:",
"Header Row": "Header Row",
"Header Column": "Header Column",
"Table headers must be associated with cells.": "Table headers must be associated with cells.",
"Set header scope:": "Set header scope:",
"Row": "Row",
"Column": "Column",
"Row Group": "Row Group",
"Column Group": "Column Group",
"Paragraph cannot be used in place of heading.": "Paragraph cannot be used in place of heading.",
"Choose a heading level:": "Choose a heading level:",
"Heading 1": "Heading 1",
"Heading 2": "Heading 2",
"Heading 3": "Heading 3",
"Heading 4": "Heading 4",
"Heading 5": "Heading 5",
"Heading 6": "Heading 6",
"Heading order must be sequential.": "Heading order must be sequential.",
"Adjacent links should be merged.": "Adjacent links should be merged.",
"Use list markup for lists.": "Use list markup for lists.",
"Large text must have a contrast ratio of at least 3:1.": "Large text must have a contrast ratio of at least 3:1.",
"Visual presentation must have a contrast ratio of at least 4.5:1.": "Visual presentation must have a contrast ratio of at least 4.5:1."
});
