//D2L specific strings

tinymce.addI18n('es_MX',{
"Add Image": "Agregar imagen",
"Insert Stuff": "Insertar objetos",
"More Text Styles": "Más estilos de texto",
"More Insert Options": "Más opciones para insertar",
"More Paragraph Formatting": "Más opciones de formato de párrafo",
"Add Link": "Agregar enlace",
"Graphical equation": "Ecuación gráfica",
"Graphical": "Gráfico",
"MathML equation": "Ecuación MathML",
"MathML": "MathML",
"LaTeX equation": "Ecuación LaTeX",
"LaTeX": "LaTeX",
"equation preview image": "vista previa de la ecuación",
"Insert stuff placeholder": "Marcador de insertar recursos",
"Ordered List": "Lista ordenada",
"Indent": "Sangría normal",
"Outdent": "Sangría francesa",
"Align Full": "Justificar",
"Address": "Dirección",
"Preformatted": "Con formato previo",
"HTML Source Editor": "Editor de fuente de HTML",
"Close Full Screen Editor": "Cerrar el editor de pantalla completa",
"Open in Full Screen Editor": "Abrir en el editor de pantalla completa",
"Add Attributes": "Agregar atributos",
"Press ALT-F10 for toolbar, and press ESC to exit toolbar once inside": "Presione ALT-F10 para ver la barra de herramientas y presione ESC para salir de la barra de herramientas",
"Emoticons": "Emoticonos",

// a11ychecker plugin
"Accessibility Checker": "Verificador de accesibilidad",
"Check Accessibility": "Verificar accesibilidad",
"No accessibility issues detected.": "No se detectaron problemas de accesibilidad.",
"Issue ": "Problema ",
" of ": " de ",
"Images must have alternative text.": "Las imágenes deben tener un texto alternativo.",
"Add alternative text:": "Agregue el texto alternativo:",
"Text cannot be empty.": "El texto no puede estar vacío.",
"Text cannot be the same as the filename.": "El texto no puede ser el mismo que el nombre del archivo.",
"Alternative text must not be the same as the image filename.": "El texto alternativo no debe ser el mismo que el nombre del archivo de imagen.",
"Tables must have captions.": "Las tablas deben tener subtítulos.",
"Set table caption:": "Establezca el subtítulo de la tabla:",
"Caption cannot be empty.": "El subtítulo no puede quedar vacío.",
"Caption cannot be the same as the summary.": "El subtítulo no puede ser el mismo que el resumen.",
"Complex tables should have summaries.": "Las tablas complejas deben tener resúmenes.",
"Set table summary.": "Establezca el resumen de la tabla.",
"Summary cannot be empty.": "El resumen no puede quedar vacío.",
"Table summary cannot be the same as table caption.": "El resumen de la tabla no puede ser el mismo que el subtítulo de la tabla.",
"Table caption and summary cannot have the same value.": "El subtítulo y el resumen de la tabla no pueden tener el mismo valor.",
"Tables must contain rows and cells.": "Las tablas deben incluir filas y celdas.",
"Tables must have at least one header.": "Las tablas deben tener al menos un encabezado.",
"Set table header:": "Establezca un encabezado de tabla:",
"Header Row": "Fila del encabezado",
"Header Column": "Columna del encabezado",
"Table headers must be associated with cells.": "Los encabezados de las tablas deben estar asociados a las celdas.",
"Set header scope:": "Establezca el alcance del encabezado:",
"Row": "Fila",
"Column": "Columna",
"Row Group": "Grupo de filas",
"Column Group": "Grupo de columnas",
"Paragraph cannot be used in place of heading.": "El párrafo no se puede utilizar en lugar del encabezado.",
"Choose a heading level:": "Elija un nivel de encabezado:",
"Heading 1": "Encabezado 1",
"Heading 2": "Encabezado 2",
"Heading 3": "Encabezado 3",
"Heading 4": "Encabezado 4",
"Heading 5": "Encabezado 5",
"Heading 6": "Encabezado 6",
"Heading order must be sequential.": "El orden del encabezado debe ser secuencial.",
"Adjacent links should be merged.": "Los enlaces adyacentes deberían combinarse.",
"Use list markup for lists.": "Utilice el marcado de listas para las listas.",
"Large text must have a contrast ratio of at least 3:1.": "Los textos grandes deben tener una relación de contraste de al menos 3:1.",
"Visual presentation must have a contrast ratio of at least 4.5:1.": "La presentación visual debe tener una relación de contraste de al menos 4.5:1.",

// d2l-emoticons plugin
"blue funster": "Funster azul",
"celebrate": "celebración",
"heart": "corazón",
"red funster": "Funster rojo",
"star": "estrella",
"sunshine": "sol",

"blush with light skin tone": "sonrojado con tono de piel claro",
"cool with light skin tone": "genial con tono de piel claro",
"goofy with light skin tone": "tonto con tono de piel claro",
"happy with light skin tone": "feliz con tono de piel claro",
"joy with light skin tone": "alegre con tono de piel claro",
"love eyes with light skin tone": "ojos de corazón con tono de piel claro",
"star eyes with light skin tone": "ojos de estrella con tono de piel claro",
"thinking with light skin tone": "pensando con tono de piel claro",
"thumbs up with light skin tone": "pulgar hacia arriba con tono de piel claro",
"wink with light skin tone": "guiño con tono de piel claro",
"wow with light skin tone": "sorprendido con tono de piel claro",
"upside down with light skin tone": "boca abajo con tono de piel claro",

"blush with dark skin tone": "sonrojado con tono de piel oscuro",
"cool with dark skin tone": "genial con tono de piel oscuro",
"goofy with dark skin tone": "tonto con tono de piel oscuro",
"happy with dark skin tone": "feliz con tono de piel oscuro",
"joy with dark skin tone": "alegre con tono de piel oscuro",
"love eyes with dark skin tone": "ojos de corazón con tono de piel oscuro",
"star eyes with dark skin tone": "ojos de estrella con tono de piel oscuro",
"thinking with dark skin tone": "pensando con tono de piel oscuro",
"thumbs up with dark skin tone": "pulgar hacia arriba con tono de piel oscuro",
"wink with dark skin tone": "guiño con tono de piel oscuro",
"wow with dark skin tone": "sorprendido con tono de piel oscuro",
"upside down with dark skin tone": "boca abajo con tono de piel oscuro"
});
