//D2L specific strings

tinymce.addI18n('fi_FI', {
    "Add Image": "Lisää kuva",
    "Insert Stuff": "Lisää tietoja",
    "More Text Styles": "Lisää tekstityylejä",
    "More Insert Options": "Lisää lisäysvaihtoehtoja",
    "More Paragraph Formatting": "Lisää kappalemuotoiluja",
    "Add Link": "Lisää linkki",
    "Graphical equation": "Graafinen yhtälö",
    "Graphical": "Graafinen",
    "Chemistry equation": "Kemiallinen yhtälö",
    "MathML equation": "MathML-yhtälö",
    "MathML": "MathML",
    "LaTeX equation": "LaTeX-yhtälö",
    "LaTeX": "LaTeX",
    "equation preview image": "yhtälön esikatselukuva",
    "Insert stuff placeholder": "Lisää tietoja -paikkamerkki",
    "Ordered List": "Järjestetty luettelo",
    "Indent": "Sisennä",
    "Outdent": "Ulonna",
    "Align Full": "Tasaa täysi",
    "Address": "Osoite",
    "Preformatted": "Esimuotoiltu",
    "HTML Source Editor": "HTML-lähde-editori",
    "Close Full Screen Editor": "Sulje koko näytön editori",
    "Open in Full Screen Editor": "Avaa koko näytön editoriin",
    "Add Attributes": "Lisää määritteitä",
    "Press ALT-F10 for toolbar, and press ESC to exit toolbar once inside": "Avaa työkalurivi valitsemalla ALT-F10 ja kun pääset sisään, sulje työkalurivi valitsemalla ESC",
    "Emoticons": "Hymiöt",

    // a11ychecker plugin
    "Accessibility Checker": "Helppokäyttöisyyden tarkistaminen",
    "Check Accessibility": "Tarkista helppokäyttöisyys",
    "No accessibility issues detected.": "Helppokäyttöisyysongelmia ei havaittu.",
    "Issue ": "Ongelma ",
    " of ": " / ",
    "Images must have alternative text.": "Kuvissa on oltava vaihtoehtoinen teksti.",
    "Add alternative text:": "Lisää vaihtoehtoinen teksti:",
    "Text cannot be empty.": "Teksti ei voi olla tyhjä.",
    "Text cannot be the same as the filename.": "Teksti ei voi olla sama kuin tiedostonimi.",
    "Alternative text must not be the same as the image filename.": "Vaihtoehtoinen teksti ei saa olla sama kuin kuvan tiedostonimi.",
    "Tables must have captions.": "Taulukoissa on oltava kuvatekstit.",
    "Set table caption:": "Aseta taulukon kuvateksti:",
    "Caption cannot be empty.": "Kuvateksti ei voi olla tyhjä.",
    "Caption cannot be the same as the summary.": "Kuvateksti ei voi olla sama kuin yhteenveto.",
    "Complex tables should have summaries.": "Monimutkaisissa taulukoissa on oltava yhteenveto.",
    "Set table summary.": "Aseta taulukon yhteenveto.",
    "Summary cannot be empty.": "Yhteenveto ei voi olla tyhjä.",
    "Table summary cannot be the same as table caption.": "Taulukon yhteenveto ei voi olla sama kuin taulukon kuvateksti.",
    "Table caption and summary cannot have the same value.": "Taulukon kuvatekstillä ja yhteenvedolla ei voi olla sama arvo.",
    "Tables must contain rows and cells.": "Taulukoiden on sisällettävä rivejä ja soluja.",
    "Tables must have at least one header.": "Taulukoissa on oltava vähintään yksi ylätunniste.",
    "Set table header:": "Aseta taulukon ylätunniste:",
    "Header Row": "Ylätunnisterivi",
    "Header Column": "Ylätunnistesarake",
    "Table headers must be associated with cells.": "Taulukon ylätunnisteiden on liityttävä soluihin.",
    "Set header scope:": "Aseta ylätunnisteen laajuus:",
    "Row": "Rivi",
    "Column": "Sarake",
    "Row Group": "Riviryhmä",
    "Column Group": "Sarakeryhmä",
    "Paragraph cannot be used in place of heading.": "Kappaletta ei voi käyttää otsikon sijasta.",
    "Choose a heading level:": "Valitse otsikkotaso:",
    "Heading 1": "Otsikko 1",
    "Heading 2": "Otsikko 2",
    "Heading 3": "Otsikko 3",
    "Heading 4": "Otsikko 4",
    "Heading 5": "Otsikko 5",
    "Heading 6": "Otsikko 6",
    "Heading order must be sequential.": "Otsikon järjestyksen on oltava peräkkäinen.",
    "Adjacent links should be merged.": "Vierekkäiset linkit on yhdistettävä.",
    "Use list markup for lists.": "Käytä luetteloissa luettelomerkintöjä.",
    "Large text must have a contrast ratio of at least 3:1.": "Suuren tekstin kontrastisuhteen on oltava vähintään 3:1.",
    "Visual presentation must have a contrast ratio of at least 4.5:1.": "Visuaalisen esityksen kontrastisuhteen on oltava vähintään 4,5:1.",

    // d2l-emoticons plugin
    "blue funster": "sininen vitsailija",
    "celebrate": "juhla",
    "heart": "sydän",
    "red funster": "punainen vitsailija",
    "star": "tähti",
    "sunshine": "auringonpaiste",

    "blush with light skin tone": "poskipuna ja vaalea ihonsävy",
    "cool with light skin tone": "viileä ja vaalea ihonsävy",
    "goofy with light skin tone": "hassu ja vaalea ihonsävy",
    "happy with light skin tone": "iloinen ja vaalea ihonsävy",
    "joy with light skin tone": "hauska ja vaalea ihonsävy",
    "love eyes with light skin tone": "sydänsilmä ja vaalea ihonsävy",
    "star eyes with light skin tone": "tähtisilmä ja vaalea ihonsävy",
    "thinking with light skin tone": "ajattelu ja vaalea ihonsävy",
    "thumbs up with light skin tone": "peukku ylös ja vaalea ihonsävy",
    "wink with light skin tone": "silmänisku ja vaalea ihonsävy",
    "wow with light skin tone": "wow ja vaalea ihonsävy",
    "upside down with light skin tone": "ylösalaisin ja vaalea ihonsävy",

    "blush with dark skin tone": "poskipuna ja tumma ihonsävy",
    "cool with dark skin tone": "viileä ja tumma ihonsävy",
    "goofy with dark skin tone": "hassu ja tumma ihonsävy",
    "happy with dark skin tone": "iloinen ja tumma ihonsävy",
    "joy with dark skin tone": "hauska ja tumma ihonsävy",
    "love eyes with dark skin tone": "sydänsilmä ja tumma ihonsävy",
    "star eyes with dark skin tone": "tähtisilmä ja tumma ihonsävy",
    "thinking with dark skin tone": "ajattelu ja tumma ihonsävy",
    "thumbs up with dark skin tone": "peukku ylös ja tumma ihonsävy",
    "wink with dark skin tone": "silmänisku ja tumma ihonsävy",
    "wow with dark skin tone": "wow ja tumma ihonsävy",
    "upside down with dark skin tone": "ylösalaisin ja tumma ihonsävy"
  });
