//D2L specific strings

tinymce.addI18n('fr_CA',{
"Add Image": "Ajouter une image",
"Insert Stuff": "Inclure quelque chose",
"More Text Styles": "Plus de styles de texte",
"More Insert Options": "Plus d'options d'inclusion",
"More Paragraph Formatting": "Plus d'options de formatage de paragraphe",
"Add Link": "Ajouter un lien",
"Graphical equation": "Équation graphique",
"Graphical": "Graphique",
"MathML equation": "Équation MathML",
"MathML": "MathML",
"LaTeX equation": "Équation LaTeX",
"LaTeX": "LaTeX",
"equation preview image": "aperçu de l'équation",
"Insert stuff placeholder": "Paramètre fictif d'insertion de matériel",
"Ordered List": "Liste numérotée",
"Indent": "Retrait positif",
"Outdent": "Retrait négatif",
"Align Full": "Justifier",
"Address": "Adresse",
"Preformatted": "Préformaté",
"HTML Source Editor": "Éditeur de source HTML",
"Close Full Screen Editor": "Fermer l'éditeur plein écran",
"Open in Full Screen Editor": "Ouvrir l'éditeur plein écran",
"Add Attributes": "Ajouter des attributs",
"Press ALT-F10 for toolbar, and press ESC to exit toolbar once inside": "Appuyez sur Alt + F10 pour afficher la barre d'outils et sur Échap pour la faire disparaître.",
"Emoticons": "Émoticônes",

// a11ychecker plugin
"Accessibility Checker": "Vérificateur d'accessibilité",
"Check Accessibility": "Vérifier l'accessibilité",
"No accessibility issues detected.": "Aucun problème d'accessibilité détecté.",
"Issue ": "Problème ",
" of ": " sur ",
"Images must have alternative text.": "Les images doivent être accompagnées d'un texte de remplacement.",
"Add alternative text:": "Ajouter du texte de remplacement :",
"Text cannot be empty.": "Le champ de texte ne peut pas rester vide.",
"Text cannot be the same as the filename.": "Le texte ne peut pas correspondre au nom du fichier.",
"Alternative text must not be the same as the image filename.": "Le texte de remplacement ne doit pas correspondre au nom du fichier de l'image.",
"Tables must have captions.": "Les tableaux doivent comporter une légende.",
"Set table caption:": "Définir la légende du tableau :",
"Caption cannot be empty.": "La légende ne peut pas rester vide.",
"Caption cannot be the same as the summary.": "La légende ne peut pas correspondre au sommaire.",
"Complex tables should have summaries.": "Les tableaux complexes doivent comporter un sommaire.",
"Set table summary.": "Définir le sommaire du tableau.",
"Summary cannot be empty.": "Le sommaire ne peut pas rester vide.",
"Table summary cannot be the same as table caption.": "Le sommaire d'un tableau ne doit pas être identique à sa légende.",
"Table caption and summary cannot have the same value.": "La légende et le sommaire du tableau ne peuvent pas avoir la même valeur.",
"Tables must contain rows and cells.": "Les tableaux doivent comporter des rangées et des cellules.",
"Tables must have at least one header.": "Les tableaux doivent comporter au moins un en-tête.",
"Set table header:": "Définir l'en-tête du tableau :",
"Header Row": "Rangée d'en-tête",
"Header Column": "Colonne d'en-tête",
"Table headers must be associated with cells.": "Les en-têtes de tableaux doivent être associés à des cellules.",
"Set header scope:": "Définir la portée de l'en-tête :",
"Row": "Rangée",
"Column": "Colonne",
"Row Group": "Groupe de rangées",
"Column Group": "Groupe de colonnes",
"Paragraph cannot be used in place of heading.": "Le paragraphe ne peut pas servir d'en-tête.",
"Choose a heading level:": "Choisir un niveau d'en-tête :",
"Heading 1": "En-tête de section 1",
"Heading 2": "En-tête de section 2",
"Heading 3": "En-tête de section 3",
"Heading 4": "En-tête de section 4",
"Heading 5": "En-tête de section 5",
"Heading 6": "En-tête de section 6",
"Heading order must be sequential.": "L'ordre des en-têtes doit être séquentiel.",
"Adjacent links should be merged.": "Les liens adjacents devraient être fusionnés.",
"Use list markup for lists.": "Utiliser le balisage de liste pour les listes.",
"Large text must have a contrast ratio of at least 3:1.": "Le texte en gros caractères doit avoir un rapport de contraste d'au moins 3:1.",
"Visual presentation must have a contrast ratio of at least 4.5:1.": "La présentation visuelle doit avoir un rapport de contraste d'au moins 4,5:1.",

// d2l-emoticons plugin
"blue funster": "Funster bleu",
"celebrate": "célébration",
"heart": "cœur",
"red funster": "Funster rouge",
"star": "étoile",
"sunshine": "soleil",

"blush with light skin tone": "gêné peau pâle",
"cool with light skin tone": "cool peau pâle",
"goofy with light skin tone": "délire peau pâle",
"happy with light skin tone": "heureux peau pâle",
"joy with light skin tone": "joyeux peau pâle",
"love eyes with light skin tone": "amoureux peau pâle",
"star eyes with light skin tone": "ébloui peau pâle",
"thinking with light skin tone": "pensif peau pâle",
"thumbs up with light skin tone": "OK peau pâle",
"wink with light skin tone": "clin d’œil peau pâle",
"wow with light skin tone": "wow peau pâle",
"upside down with light skin tone": "renversé peau pâle",

"blush with dark skin tone": "gêné peau foncée",
"cool with dark skin tone": "cool peau foncée",
"goofy with dark skin tone": "délire peau foncée",
"happy with dark skin tone": "heureux peau foncée",
"joy with dark skin tone": "joyeux peau foncée",
"love eyes with dark skin tone": "amoureux peau foncée",
"star eyes with dark skin tone": "ébloui peau foncée",
"thinking with dark skin tone": "pensif peau foncée",
"thumbs up with dark skin tone": "OK peau foncée",
"wink with dark skin tone": "clin d’œil peau foncée",
"wow with dark skin tone": "wow peau foncée",
"upside down with dark skin tone": "renversé peau foncée"
});
