//D2L specific strings

tinymce.addI18n('ja',{
"Add Image": "イメージの追加",
"Insert Stuff": "素材の挿入",
"More Text Styles": "その他のテキストスタイル",
"More Insert Options": "その他の挿入オプション",
"More Paragraph Formatting": "その他のパラグラフ書式",
"Add Link": "リンクの追加",
"Graphical equation": "グラフィカル数式",
"Graphical": "グラフィカル",
"MathML equation": "MathML 数式",
"MathML": "MathML",
"LaTeX equation": "LaTeX 数式",
"LaTeX": "LaTeX",
"equation preview image": "数式のプレビューイメージ",
"Insert stuff placeholder": "素材のプレースホルダの挿入",
"Ordered List": "番号付きリスト",
"Indent": "インデント",
"Outdent": "アウトデント",
"Align Full": "均等割り",
"Address": "アドレス",
"Preformatted": "事前フォーマット",
"HTML Source Editor": "HTML ソースエディタ",
"Close Full Screen Editor": "フルスクリーンエディタを閉じる",
"Open in Full Screen Editor": "フルスクリーンエディタで開く",
"Add Attributes": "属性の追加",
"Press ALT-F10 for toolbar, and press ESC to exit toolbar once inside": "ツールバーを表示するには ALT-F10 キーを、ツールバーを終了するにはツールバーにカーソルを置いた状態で ESC キーを押します",

// a11ychecker plugin
"Accessibility Checker": "アクセシビリティチェック",
"Check Accessibility": "アクセシビリティのチェック",
"No accessibility issues detected.": "アクセシビリティの問題は検出されませんでした。",
"Issue ": "発行 ",
" of ": " / ",
"Images must have alternative text.": "イメージに代替テキストを設定する必要があります。",
"Add alternative text:": "代替テキストの追加:",
"Text cannot be empty.": "テキストは空にできません。",
"Text cannot be the same as the filename.": "テキストはファイル名と同じにできません。",
"Alternative text must not be the same as the image filename.": "代替テキストはイメージファイル名と同じにしてはいけません。",
"Tables must have captions.": "テーブルにはキャプションを設定する必要があります。",
"Set table caption:": "テーブルキャプションの設定:",
"Caption cannot be empty.": "キャプションは空にできません。",
"Caption cannot be the same as the summary.": "キャプションはサマリーと同じにできません。",
"Complex tables should have summaries.": "複雑なテーブルにはサマリーを設定してください。",
"Set table summary.": "テーブルサマリーを設定します。",
"Summary cannot be empty.": "サマリーは空にできません。",
"Table summary cannot be the same as table caption.": "テーブルサマリーはテーブルキャプションと同じにできません。",
"Table caption and summary cannot have the same value.": "テーブルのキャプションとサマリーには同じ値を設定できません。",
"Tables must contain rows and cells.": "テーブルには一定の行とセルが含まれている必要があります。",
"Tables must have at least one header.": "テーブルには 1 つ以上の見出しを設定する必要があります。",
"Set table header:": "テーブル見出しの設定:",
"Header Row": "見出し行",
"Header Column": "見出し列",
"Table headers must be associated with cells.": "テーブル見出しはセルと関連付ける必要があります。",
"Set header scope:": "見出し範囲の設定:",
"Row": "行",
"Column": "列",
"Row Group": "行グループ",
"Column Group": "列グループ",
"Paragraph cannot be used in place of heading.": "パラグラフは見出しの代わりに使用できません。",
"Choose a heading level:": "見出しレベルの選択:",
"Heading 1": "見出し 1",
"Heading 2": "見出し 2",
"Heading 3": "見出し 3",
"Heading 4": "見出し 4",
"Heading 5": "見出し 5",
"Heading 6": "見出し 6",
"Heading order must be sequential.": "見出し順序は連続している必要があります。",
"Adjacent links should be merged.": "隣接リンクをマージしてください。",
"Use list markup for lists.": "リストにはリストマークアップを使用します。",
"Large text must have a contrast ratio of at least 3:1.": "大テキストは 3:1 以上のコントラスト比に設定する必要があります。",
"Visual presentation must have a contrast ratio of at least 4.5:1.": "視覚表示は 4.5:1 以上のコントラスト比に設定する必要があります。"
});
