//D2L specific strings

tinymce.addI18n('ko_KR',{
"Add Image": "이미지 추가",
"Insert Stuff": "항목 삽입",
"More Text Styles": "텍스트 스타일 더보기",
"More Insert Options": "삽입 옵션 더보기",
"More Paragraph Formatting": "단락 형식 지정 더보기",
"Add Link": "링크 추가",
"Graphical equation": "그래픽 수식",
"Graphical": "그래픽",
"MathML equation": "MathML 수식",
"MathML": "MathML",
"LaTeX equation": "LaTeX 수식",
"LaTeX": "LaTeX",
"equation preview image": "수식 미리 보기 이미지",
"Insert stuff placeholder": "항목 자리표시자 삽입",
"Ordered List": "순서 지정 목록",
"Indent": "들여쓰기",
"Outdent": "내어쓰기",
"Align Full": "양쪽 정렬",
"Address": "주소",
"Preformatted": "서식 설정되어 있음",
"HTML Source Editor": "HTML 소스 편집기",
"Close Full Screen Editor": "전체 화면 편집기 닫기",
"Open in Full Screen Editor": "전체 화면 편집기에서 열기",
"Add Attributes": "속성 추가",
"Press ALT-F10 for toolbar, and press ESC to exit toolbar once inside": "도구 모음을 불러오려면 ALT-F10을 누르고, 도구 모음을 끝내려면 도구 모음 내에서 ESC를 누르십시오.",

// a11ychecker plugin
"Accessibility Checker": "접근성 검사기",
"Check Accessibility": "접근성 검사",
"No accessibility issues detected.": "접근성 문제가 발견되지 않았습니다.",
"Issue ": "문제 ",
" of ": " / ",
"Images must have alternative text.": "이미지에는 대체 텍스트가 있어야 합니다.",
"Add alternative text:": "대체 텍스트 추가:",
"Text cannot be empty.": "텍스트는 비워둘 수 없습니다.",
"Text cannot be the same as the filename.": "텍스트는 파일명과 동일해서는 안 됩니다.",
"Alternative text must not be the same as the image filename.": "대체 텍스트는 이미지 파일명과 동일해서는 안 됩니다.",
"Tables must have captions.": "표에는 캡션이 있어야 합니다.",
"Set table caption:": "표 캡션 설정:",
"Caption cannot be empty.": "캡션은 비워둘 수 없습니다.",
"Caption cannot be the same as the summary.": "캡션은 요약과 동일해서는 안 됩니다.",
"Complex tables should have summaries.": "복잡한 표에는 요약이 있어야 합니다.",
"Set table summary.": "표 요약을 설정하십시오.",
"Summary cannot be empty.": "요약은 비워둘 수 없습니다.",
"Table summary cannot be the same as table caption.": "표 요약은 표 캡션과 동일해서는 안 됩니다.",
"Table caption and summary cannot have the same value.": "표 캡션과 요약의 값은 동일해서는 안 됩니다.",
"Tables must contain rows and cells.": "표는 행 및 셀을 포함해야 합니다.",
"Tables must have at least one header.": "표에는 하나 이상의 머리글이 있어야 합니다.",
"Set table header:": "표 머리글 설정:",
"Header Row": "머리글 행",
"Header Column": "머리글 열",
"Table headers must be associated with cells.": "표 머리글은 셀과 연결되어야 합니다.",
"Set header scope:": "머리글 범위 설정:",
"Row": "행",
"Column": "열",
"Row Group": "행 그룹",
"Column Group": "열 그룹",
"Paragraph cannot be used in place of heading.": "단락은 머리글 대신 사용할 수 없습니다.",
"Choose a heading level:": "머리글 수준 선택:",
"Heading 1": "머리글 1",
"Heading 2": "머리글 2",
"Heading 3": "머리글 3",
"Heading 4": "머리글 4",
"Heading 5": "머리글 5",
"Heading 6": "머리글 6",
"Heading order must be sequential.": "머리글 순서는 순차적이어야 합니다.",
"Adjacent links should be merged.": "인접 링크는 병합해야 합니다.",
"Use list markup for lists.": "목록에는 목록 마크업을 사용하십시오.",
"Large text must have a contrast ratio of at least 3:1.": "큰 텍스트의 명암비는 3:1보다 커야 합니다.",
"Visual presentation must have a contrast ratio of at least 4.5:1.": "시각 프레젠테이션의 명암비는 4.5:1보다 커야 합니다."
});
