//D2L specific strings

tinymce.addI18n('nb_NO',{
"Add Image": "Legg til bilde",
"Insert Stuff": "Sett inn ting",
"More Text Styles": "Flere tekststiler",
"More Insert Options": "Flere innsettingsalternativer",
"More Paragraph Formatting": "Mer avsnittsformatering",
"Add Link": "Legg til kobling",
"Graphical equation": "Grafisk formel",
"Graphical": "Grafisk",
"MathML equation": "MathML-formel",
"MathML": "MathML",
"Latex": "Forhåndsvisningsbilde",
"equation preview image": "for Latex-formel",
"Insert stuff placeholder": "Sett inn plassholder for ting",
"Ordered List": "Sortert liste",
"Indent": "Innrykk",
"Outdent": "Reduser innrykk",
"Align Full": "Midtstill fullstendig",
"Address": "Adresse",
"Preformatted": "Forhåndsformatert",
"HTML Source Editor": "Redigeringsprogram for HTML-kilde",
"Close Full Screen Editor": "Lukk redigeringsprogrammet i full skjerm",
"Open in Full Screen Editor": "Åpne redigeringsprogrammet i full skjerm",
"Add Attributes": "Legg til attributter",
"Press ALT-F10 for toolbar, and press ESC to exit toolbar once inside": "Trykk på Alt+F10 for å åpne verktøylinjen, og trykk på Esc for å gå ut av verktøylinjen",

// a11ychecker plugin
"Accessibility Checker": "Tilgjengelighetskontroll",
"Check Accessibility": "Kontroller tilgjengelighet",
"No accessibility issues detected.": "Fant ingen tilgjengelighetsproblemer.",
"Issue ": "Utsted ",
" of ": " for ",
"Images must have alternative text.": "Bilder må ha en alternativ tekst.",
"Add alternative text:": "Legg til alternativ tekst:",
"Text cannot be empty.": "Tekstfeltet kan ikke være blankt.",
"Text cannot be the same as the filename.": "Teksten kan ikke være lik filnavnet.",
"Alternative text must not be the same as the image filename.": "Den alternative teksten kan ikke være lik bildefilnavnet.",
"Tables must have captions.": "Tabellene må ha bildetekst.",
"Set table caption:": "Angi bildetekst for tabell:",
"Caption cannot be empty.": "Bildetekstfeltet kan ikke være blankt.",
"Caption cannot be the same as the summary.": "Bildeteksten kan ikke være lik sammendraget.",
"Complex tables should have summaries.": "Komplekse tabeller må ha sammendrag.",
"Set table summary.": "Angi sammendrag for tabell.",
"Summary cannot be empty.": "Sammendraget kan ikke være blankt.",
"Table summary cannot be the same as table caption.": "Tabellsammendraget kan ikke være likt tabellbildeteksten.",
"Table caption and summary cannot have the same value.": "Tabellbildeteksten og -sammendraget kan ikke ha samme verdi.",
"Tables must contain rows and cells.": "Tabellene må inneholde rader og celler.",
"Tables must have at least one header.": "Tabellene må ha minst én topptekst.",
"Set table header:": "Angi tabelltopptekst:",
"Header Row": "Topptekstrad",
"Header Column": "Topptekstkolonne",
"Table headers must be associated with cells.": "Tabelltopptekstene må være knyttet til celler.",
"Set header scope:": "Angi topptekstomfang:",
"Row": "Rad",
"Column": "Kolonne",
"Row Group": "Radgruppe",
"Column Group": "Kolonnegruppe",
"Paragraph cannot be used in place of heading.": "Avsnittet kan ikke brukes i stedet for en overskrift.",
"Choose a heading level:": "Velg et overskriftsnivå:",
"Heading 1": "Overskrift 1",
"Heading 2": "Overskrift 2",
"Heading 3": "Overskrift 3",
"Heading 4": "Overskrift 4",
"Heading 5": "Overskrift 5",
"Heading 6": "Overskrift 6",
"Heading order must be sequential.": "Rekkefølgen på overskriftene må være sekvensiell.",
"Adjacent links should be merged.": "Nærliggende koblinger skal slås sammen.",
"Use list markup for lists.": "Bruk listemarkering for lister.",
"Large text must have a contrast ratio of at least 3:1.": "Stor tekst må ha et kontrastforhold på minst 3 : 1.",
"Visual presentation must have a contrast ratio of at least 4.5:1.": "En visuell presentasjon må ha et kontrastforhold på minst 4,5 : 1."
});
