//D2L specific strings

tinymce.addI18n('nl_NL',{
"Add Image": "Afbeelding toevoegen",
"Insert Stuff": "Inhoud invoegen",
"More Text Styles": "Meer tekststijlen",
"More Insert Options": "Meer invoegopties",
"More Paragraph Formatting": "Meer alineaopmaken",
"Add Link": "Koppeling toevoegen",
"Graphical equation": "Grafische vergelijking",
"Graphical": "Grafisch",
"MathML equation": "MathML-vergelijking",
"MathML": "MathML",
"Latex": "Latex",
"equation preview image": "voorbeeldafbeelding van vergelijking",
"Insert stuff placeholder": "Tijdelijke aanduiding voor inhoud invoegen",
"Ordered List": "Geordende lijst",
"Indent": "Inspringen",
"Outdent": "Uitspringen",
"Align Full": "Uitvullen",
"Address": "Adres",
"Preformatted": "Vooraf opgemaakt",
"HTML Source Editor": "HTML-editor",
"Close Full Screen Editor": "Editor op volledig scherm afsluiten",
"Open in Full Screen Editor": "Openen in editor op volledig scherm",
"Add Attributes": "Kenmerken toevoegen",
"Press ALT-F10 for toolbar, and press ESC to exit toolbar once inside": "Druk op ALT+F10 om de taakbalk te tonen en druk op Esc om de taakbalk vervolgens te sluiten",

// a11ychecker plugin
"Accessibility Checker": "Toegankelijkheidscontrole",
"Check Accessibility": "Toegankelijkheid controleren",
"No accessibility issues detected.": "Geen toegankelijkheidsproblemen gedetecteerd.",
"Issue ": "Probleem ",
" of ": " van ",
"Images must have alternative text.": "Afbeeldingen moeten alternatieve tekst bevatten.",
"Add alternative text:": "Alternatieve tekst toevoegen:",
"Text cannot be empty.": "Tekst kan niet leeg zijn.",
"Text cannot be the same as the filename.": "Tekst kan niet hetzelfde zijn als de bestandsnaam.",
"Alternative text must not be the same as the image filename.": "Alternatieve tekst mag niet hetzelfde zijn als de bestandsnaam van de afbeelding.",
"Tables must have captions.": "Tabellen moeten een bijschrift bevatten.",
"Set table caption:": "Stel tabelbijschrift in:",
"Caption cannot be empty.": "Bijschrift kan niet leeg zijn.",
"Caption cannot be the same as the summary.": "Bijschrift kan niet hetzelfde zijn als het overzicht.",
"Complex tables should have summaries.": "Complexe tabellen moeten een overzicht bevatten.",
"Set table summary.": "Stel tabeloverzicht in.",
"Summary cannot be empty.": "Overzicht kan niet leeg zijn.",
"Table summary cannot be the same as table caption.": "Tabeloverzicht kan niet hetzelfde zijn als tabelbijschrift.",
"Table caption and summary cannot have the same value.": "Tabelbijschrift en -overzicht kunnen niet dezelfde waarde bevatten.",
"Tables must contain rows and cells.": "Tabellen moeten rijen en cellen bevatten.",
"Tables must have at least one header.": "Tabellen moeten ten minste één koptekst bevatten.",
"Set table header:": "Stel tabelkoptekst in:",
"Header Row": "Koptekstrij",
"Header Column": "Koptekstkolom",
"Table headers must be associated with cells.": "Tabelkoptekst moet zijn gekoppeld aan cellen.",
"Set header scope:": "Stel bereik koptekst in:",
"Row": "Rij",
"Column": "Kolom",
"Row Group": "Rijgroep",
"Column Group": "Kolomgroep",
"Paragraph cannot be used in place of heading.": "Alinea kan niet worden gebruikt op plek van kop.",
"Choose a heading level:": "Kies een kopniveau:",
"Heading 1": "Koptekst 1",
"Heading 2": "Koptekst 2",
"Heading 3": "Koptekst 3",
"Heading 4": "Koptekst 4",
"Heading 5": "Koptekst 5",
"Heading 6": "Koptekst 6",
"Heading order must be sequential.": "Volgorde van koppen moet sequentieel zijn.",
"Adjacent links should be merged.": "Naast elkaar geplaatste koppelingen moeten worden samengevoegd.",
"Use list markup for lists.": "Gebruik lijstmarkeringen voor lijsten.",
"Large text must have a contrast ratio of at least 3:1.": "Grote tekst moet een contrastverhouding van ten minste 3:1 hebben.",
"Visual presentation must have a contrast ratio of at least 4.5:1.": "Visuele presentatie moet een contrastverhouding van ten minste 4,5:1 hebben."
});
