//D2L specific strings

tinymce.addI18n('pt_BR',{
"Add Image": "Adicionar imagem",
"Insert Stuff": "Inserir Item",
"More Text Styles": "Mais Estilos de Texto",
"More Insert Options": "Mais Opções de Inserção",
"More Paragraph Formatting": "Mais Formatação de Parágrafo",
"Add Link": "Adicionar Link",
"Graphical equation": "Equação gráfica",
"Graphical": "Gráfica",
"Chemistry equation": "Equação química",
"MathML equation": "Equação MathML",
"MathML": "MathML",
"LaTeX equation": "Equação LaTeX",
"LaTeX": "LaTeX",
"equation preview image": "imagem de visual da equação",
"Insert stuff placeholder": "Espaço reservado para inserir itens",
"Ordered List": "Lista Ordenada",
"Indent": "Avanço",
"Outdent": "Recuo",
"Align Full": "Alinhar Tudo",
"Address": "Endereço",
"Preformatted": "Pré-formatado",
"HTML Source Editor": "Editor de Origem de HTML",
"Close Full Screen Editor": "Fechar Editor de tela cheia",
"Open in Full Screen Editor": "Abrir no Editor de tela cheia",
"Add Attributes": "Adicionar atributos",
"Press ALT-F10 for toolbar, and press ESC to exit toolbar once inside": "Pressione ALT-F10 para entrar na barra de ferramentas e, para sair, pressione ESC",
"Emoticons": "Emoticons",

// a11ychecker plugin
"Accessibility Checker": "Verificador de Acessibilidade",
"Check Accessibility": "Verificar Acessibilidade",
"No accessibility issues detected.": "Nenhum problema de acessibilidade detectado.",
"Issue ": "Emissão ",
" of ": " de ",
"Images must have alternative text.": "As imagens devem ter texto alternativo.",
"Add alternative text:": "Adicionar texto alternativo:",
"Text cannot be empty.": "Texto não pode estar em branco.",
"Text cannot be the same as the filename.": "Texto não pode ser igual ao nome do arquivo.",
"Alternative text must not be the same as the image filename.": "Texto alternativo não deve ser igual ao nome de arquivo da imagem.",
"Tables must have captions.": "Tabelas devem ter legendas.",
"Set table caption:": "Definir legenda da tabela:",
"Caption cannot be empty.": "Legenda não pode estar em branco.",
"Caption cannot be the same as the summary.": "Legenda não pode ser igual ao resumo.",
"Complex tables should have summaries.": "Tabelas complexas devem ter resumos.",
"Set table summary.": "Definir resumo da tabela.",
"Summary cannot be empty.": "Resumo não pode estar em branco.",
"Table summary cannot be the same as table caption.": "Resumo da tabela não pode ser igual à legenda da tabela.",
"Table caption and summary cannot have the same value.": "Legenda e resumo da tabela não podem ter o mesmo valor.",
"Tables must contain rows and cells.": "Tabelas devem ter linhas e células.",
"Tables must have at least one header.": "Tabelas devem ter, pelo menos, um cabeçalho.",
"Set table header:": "Definir cabeçalho da tabela:",
"Header Row": "Linha do Cabeçalho",
"Header Column": "Coluna do Cabeçalho",
"Table headers must be associated with cells.": "Cabeçalhos das tabelas devem estar associados às células.",
"Set header scope:": "Definir escopo do cabeçalho:",
"Row": "Linha",
"Column": "Coluna",
"Row Group": "Grupo de Linhas",
"Column Group": "Grupo de Colunas",
"Paragraph cannot be used in place of heading.": "Parágrafo não pode ser usado no lugar do cabeçalho.",
"Choose a heading level:": "Escolha um nível de cabeçalho:",
"Heading 1": "Título 1",
"Heading 2": "Título 2",
"Heading 3": "Título 3",
"Heading 4": "Título 4",
"Heading 5": "Título 5",
"Heading 6": "Título 6",
"Heading order must be sequential.": "Ordem do cabeçalho deve ser sequencial.",
"Adjacent links should be merged.": "Links adjacentes devem ser mesclados.",
"Use list markup for lists.": "Use marcação de lista para listas.",
"Large text must have a contrast ratio of at least 3:1.": "Texto grande deve ter uma proporção de contraste de, pelo menos, 3:1.",
"Visual presentation must have a contrast ratio of at least 4.5:1.": "Apresentação visual deve ter uma proporção de contraste de, pelo menos, 4,5:1.",

// d2l-emoticons plugin
"blue funster": "monstro azul",
"celebrate": "celebração",
"heart": "coração",
"red funster": "monstro vermelho",
"star": "estrela",
"sunshine": "sol brilhando",

"blush with light skin tone": "envergonhado com pele clara",
"cool with light skin tone": "descolado com pele clara",
"goofy with light skin tone": "doidinho com pele clara",
"happy with light skin tone": "feliz com pele clara",
"joy with light skin tone": "gargalhando com pele clara",
"love eyes with light skin tone": "apaixonado com pele clara",
"star eyes with light skin tone": "fascinado com pele clara",
"thinking with light skin tone": "pensativo com pele clara",
"thumbs up with light skin tone": "joia com pele clara",
"wink with light skin tone": "piscando com pele clara",
"wow with light skin tone": "surpreso com pele clara",
"upside down with light skin tone": "sorrindo de ponta cabeça com pele clara",

"blush with dark skin tone": "envergonhado com pele escura",
"cool with dark skin tone": "descolado com pele escura",
"goofy with dark skin tone": "doidinho com pele escura",
"happy with dark skin tone": "feliz com pele escura",
"joy with dark skin tone": "gargalhando com pele escura",
"love eyes with dark skin tone": "apaixonado com pele escura",
"star eyes with dark skin tone": "fascinado com pele escura",
"thinking with dark skin tone": "pensativo com pele escura",
"thumbs up with dark skin tone": "joia com pele escura",
"wink with dark skin tone": "piscando com pele escura",
"wow with dark skin tone": "surpreso com pele escura",
"upside down with dark skin tone": "sorrindo de ponta cabeça com pele escura"
});
