//D2L specific strings

tinymce.addI18n('sv_SE',{
"Add Image": "Lägg till bild",
"Insert Stuff": "Infoga material",
"More Text Styles": "Fler texttyper",
"More Insert Options": "Fler infogningsalternativ",
"More Paragraph Formatting": "Mer styckeformatering",
"Add Link": "Lägg till länk",
"Graphical equation": "Grafisk ekvation",
"Graphical": "Grafiskt",
"Chemistry equation": "Kemiekvation",
"MathML equation": "MathML-ekvation",
"MathML": "MathML",
"LaTeX equation": "LaTeX-ekvation",
"LaTeX": "LaTeX",
"equation preview image": "förhandsgranskning av ekvation",
"Insert stuff placeholder": "Infoga platshållare för material",
"Ordered List": "Sorterad lista",
"Indent": "Öka indrag",
"Outdent": "Minska indrag",
"Align Full": "Justera vänster och höger",
"Address": "Adress",
"Preformatted": "Förformaterad",
"HTML Source Editor": "HTML-källredigerare",
"Close Full Screen Editor": "Stäng helskärmsredigering",
"Open in Full Screen Editor": "Öppna helskärmsredigering",
"Add Attributes": "Lägg till egenskaper",
"Press ALT-F10 for toolbar, and press ESC to exit toolbar once inside": "Tryck ALT-F10 för verktygsfält och ESC för att avsluta verktygsfältet när du är i det",
"Emoticons": "Uttryckssymboler",

// a11ychecker plugin
"Accessibility Checker": "Åtkomstkontroll",
"Check Accessibility": "Kontrollera åtkomst",
"No accessibility issues detected.": "Inga åtkomstproblem upptäcktes.",
"Issue ": "Utfärdande ",
" of ": " av ",
"Images must have alternative text.": "Bilder måste ha alternativ text.",
"Add alternative text:": "Lägg till alternativ text:",
"Text cannot be empty.": "Textfältet får inte vara tomt.",
"Text cannot be the same as the filename.": "Texten kan inte vara samma som filnamnet.",
"Alternative text must not be the same as the image filename.": "Alternativ text får inte vara samma som bildens filnamn.",
"Tables must have captions.": "Tabeller måste ha en text.",
"Set table caption:": "Ange tabelltext:",
"Caption cannot be empty.": "Textfältet kan inte vara tomt.",
"Caption cannot be the same as the summary.": "Bildtexten kan inta vara samma som sammanfattningen.",
"Complex tables should have summaries.": "Komplexa tabeller ska ha en sammanfattning.",
"Set table summary.": "Ange tabellsammanfattning.",
"Summary cannot be empty.": "Sammanfattningen får inte vara tom.",
"Table summary cannot be the same as table caption.": "Tabellsammanfattningen får inta vara samma som tabelltexten.",
"Table caption and summary cannot have the same value.": "Tabelltexten får inte vara samma som sammanfattningen.",
"Tables must contain rows and cells.": "Tabellerna måste innehålla rader och celler.",
"Tables must have at least one header.": "Tabellerna måste ha minst en rubrik.",
"Set table header:": "Ange tabellrubrik:",
"Header Row": "Rubriksrad",
"Header Column": "Rubrikskolumn",
"Table headers must be associated with cells.": "Tabellrubrikerna måste kopplas till cellerna.",
"Set header scope:": "Ange rubrikomfång:",
"Row": "Rad",
"Column": "Kolumn",
"Row Group": "Radgrupp",
"Column Group": "Kolumnen Grupp",
"Paragraph cannot be used in place of heading.": "Paragraf får inte ersätta rubrik.",
"Choose a heading level:": "Välj rubriksnivå:",
"Heading 1": "Rubrik 1",
"Heading 2": "Rubrik 2",
"Heading 3": "Rubrik 3",
"Heading 4": "Rubrik 4",
"Heading 5": "Rubrik 5",
"Heading 6": "Rubrik 6",
"Heading order must be sequential.": "Rubriksordningen måste vara sekventiell.",
"Adjacent links should be merged.": "Intilliggande länkar ska slås ihop.",
"Use list markup for lists.": "Använd listmarkering för lista.",
"Large text must have a contrast ratio of at least 3:1.": "Stor text måste ha ett kontrastförhållande på minst 3:1.",
"Visual presentation must have a contrast ratio of at least 4.5:1.": "Visuell presentation måste ha ett kontrastförhållande på minst 4.5:1.",
"Next": "Nästa",
"Close": "Stäng",

// d2l-emoticons plugin
"blue funster": "blå funster",
"celebrate": "firar",
"heart": "hjärta",
"red funster": "röd funster",
"star": "stjärna",
"sunshine": "sol",

"blush with light skin tone": "rodnar med ljus hudton",
"cool with light skin tone": "cool med ljus hudton",
"goofy with light skin tone": "goofy med ljus hudton",
"happy with light skin tone": "glad med ljus hudton",
"joy with light skin tone": "glädjetårar med ljus hudton",
"love eyes with light skin tone": "hjärtformade ögon med ljus hudton",
"star eyes with light skin tone": "stjärnögon med ljus hudton",
"thinking with light skin tone": "tänker med ljus hudton",
"thumbs up with light skin tone": "tummen upp med ljus hudton",
"wink with light skin tone": "blinkar med ljus hudton",
"wow with light skin tone": "wow med ljus hudton",
"upside down with light skin tone": "upp och ned med ljus hudton",

"blush with dark skin tone": "rodnar med mörk hudton",
"cool with dark skin tone": "cool med mörk hudton",
"goofy with dark skin tone": "goofy med mörk hudton",
"happy with dark skin tone": "glad med mörk hudton",
"joy with dark skin tone": "glädjetårar med mörk hudton",
"love eyes with dark skin tone": "hjärtformade ögon med mörk hudton",
"star eyes with dark skin tone": "stjärnögon med mörk hudton",
"thinking with dark skin tone": "tänker med mörk hudton",
"thumbs up with dark skin tone": "tummen upp med mörk hudton",
"wink with dark skin tone": "blinkar med mörk hudton",
"wow with dark skin tone": "wow med mörk hudton",
"upside down with dark skin tone": "upp och ned med mörk hudton"
});
