//D2L specific strings

tinymce.addI18n('tr_TR',{
"Add Image": "Görüntü Ekle",
"Insert Stuff": "Öğe Ekle",
"More Text Styles": "Daha Fazla Metin Stili",
"More Insert Options": "Daha Fazla Ekleme Seçeneği",
"More Paragraph Formatting": "Daha Fazla Paragraf Biçimlendirmesi",
"Add Link": "Bağlantı Ekle",
"Graphical equation": "Grafik denklemi",
"Graphical": "Grafik",
"Chemistry equation": "Kimya denklemi",
"MathML equation": "MathML denklemi",
"MathML": "MathML",
"LaTeX equation": "LaTeX denklemi",
"LaTeX": "LaTeX",
"equation preview image": "denklem önizleme görüntüsü",
"Insert stuff placeholder": "Öğe yer tutucu ekle",
"Ordered List": "Sıralı Liste",
"Indent": "Girinti",
"Outdent": "Çıkıntı",
"Align Full": "İki Yana Yasla",
"Address": "Adres",
"Preformatted": "Önceden biçimlendirilmiş",
"HTML Source Editor": "HTML Kaynak Düzenleyici",
"Close Full Screen Editor": "Tam Ekran Düzenleyiciyi Kapat",
"Open in Full Screen Editor": "Tam Ekran Düzenleyicide Aç",
"Add Attributes": "Öznitelik Ekle",
"Press ALT-F10 for toolbar, and press ESC to exit toolbar once inside": "Araç çubuğuna giriş yapmak için ALT+F10 tuşlarına basın, araç çubuğundayken çıkış yapmak için ESC tuşuna basın",
"Emoticons": "Simgeler",

// a11ychecker plugin
"Accessibility Checker": "Erişilebilirlik Denetleyici",
"Check Accessibility": "Erişilebilirliği Denetle",
"No accessibility issues detected.": "Herhangi bir erişilebilirlik sorunu algılanmadı.",
"Issue ": "Ver ",
" of ": " / ",
"Images must have alternative text.": "Görüntülerin alternatif metinleri olmalıdır.",
"Add alternative text:": "Alternatif metin ekle:",
"Text cannot be empty.": "Metin boş bırakılamaz.",
"Text cannot be the same as the filename.": "Metin, dosya adıyla aynı olamaz.",
"Alternative text must not be the same as the image filename.": "Alternatif metin, görüntü dosya adıyla aynı olamaz.",
"Tables must have captions.": "Tabloların altyazıları olmalıdır.",
"Set table caption:": "Tablo altyazısını ayarla:",
"Caption cannot be empty.": "Altyazı boş bırakılamaz.",
"Caption cannot be the same as the summary.": "Altyazı, özetle aynı olamaz.",
"Complex tables should have summaries.": "Karmaşık tabloların özetleri olmalıdır.",
"Set table summary.": "Tablo özetini ayarlayın.",
"Summary cannot be empty.": "Özet boş bırakılamaz.",
"Table summary cannot be the same as table caption.": "Tablo özeti, tablo altyazısıyla aynı olamaz.",
"Table caption and summary cannot have the same value.": "Tablo altyazısı ve özet aynı değere sahip olamaz.",
"Tables must contain rows and cells.": "Tablolar satır ve hücre içermelidir.",
"Tables must have at least one header.": "Tabloların en az bir başlığı olmalıdır.",
"Set table header:": "Tablo başlığını ayarla:",
"Header Row": "Başlık Satırı",
"Header Column": "Başlık Sütunu",
"Table headers must be associated with cells.": "Tablo başlıkları hücrelerle ilişkilendirilmelidir.",
"Set header scope:": "Başlık kapsamını ayarla:",
"Row": "Satır",
"Column": "Sütun",
"Row Group": "Satır Grubu",
"Column Group": "Sütun Grubu",
"Paragraph cannot be used in place of heading.": "Paragraf, başlık yerinde kullanılamaz.",
"Choose a heading level:": "Bir başlık düzeyi seç:",
"Heading 1": "Başlık 1",
"Heading 2": "Başlık 2",
"Heading 3": "Başlık 3",
"Heading 4": "Başlık 4",
"Heading 5": "Başlık 5",
"Heading 6": "Başlık 6",
"Heading order must be sequential.": "Başlık sırası ardışık olmalıdır.",
"Adjacent links should be merged.": "Yan bağlantılar birleştirilmelidir.",
"Use list markup for lists.": "Listeler için liste biçimlendirmesini kullanın.",
"Large text must have a contrast ratio of at least 3:1.": "Geniş metnin kontrast oranı en az 3:1 olmalıdır.",
"Visual presentation must have a contrast ratio of at least 4.5:1.": "Görsel sunumun kontrast oranı en az 4,5:1 olmalıdır.",

// d2l-emoticons plugin
"blue funster": "mavi canavar",
"celebrate": "kutlama",
"heart": "kalp",
"red funster": "kırmızı canavar",
"star": "yıldız",
"sunshine": "güneş ışığı",

"blush with light skin tone": "utanmış açık tenli avatar",
"cool with light skin tone": "havalı açık tenli avatar",
"goofy with light skin tone": "şaşkın açık tenli avatar",
"happy with light skin tone": "mutlu açık tenli avatar",
"joy with light skin tone": "neşeli açık tenli avatar",
"love eyes with light skin tone": "gözlerinden kalp çıkan açık tenli avatar",
"star eyes with light skin tone": "gözlerinden yıldız çıkan açık tenli avatar",
"thinking with light skin tone": "düşünceli açık tenli avatar",
"thumbs up with light skin tone": "onaylayan açık tenli el",
"wink with light skin tone": "göz kırpan açık tenli avatar",
"wow with light skin tone": "şaşıran açık tenli avatar",
"upside down with light skin tone": "ters duran açık tenli avatar",

"blush with dark skin tone": "utanmış koyu tenli avatar",
"cool with dark skin tone": "havalı koyu tenli avatar",
"goofy with dark skin tone": "şaşkın koyu tenli avatar",
"happy with dark skin tone": "mutlu koyu tenli avatar",
"joy with dark skin tone": "neşeli koyu tenli avatar",
"love eyes with dark skin tone": "gözlerinden kalp çıkan koyu tenli avatar",
"star eyes with dark skin tone": "gözlerinden yıldız çıkan koyu tenli avatar",
"thinking with dark skin tone": "düşünceli koyu tenli avatar",
"thumbs up with dark skin tone": "onaylayan koyu tenli el",
"wink with dark skin tone": "göz kırpan koyu tenli avatar",
"wow with dark skin tone": "şaşıran koyu tenli avatar",
"upside down with dark skin tone": "ters duran koyu tenli avatar"
});
