//D2L specific strings

tinymce.addI18n('zh_CN',{
"Add Image": "添加图片",
"Insert Stuff": "插入资料",
"More Text Styles": "更多文本类型",
"More Insert Options": "更多插入选项",
"More Paragraph Formatting": "更多段落格式",
"Add Link": "添加链接",
"Graphical equation": "图形等式",
"Graphical": "图形",
"MathML equation": "MathML 等式",
"MathML": "MathML",
"Latex": "LateX",
"equation preview image": "Equation 预览图像",
"Insert stuff placeholder": "插入内容占位符",
"Ordered List": "有序列表",
"Indent": "缩进",
"Outdent": "减少缩进",
"Align Full": "两端对齐",
"Address": "地址",
"Preformatted": "预设格式",
"HTML Source Editor": "HTML 源编辑器",
"Close Full Screen Editor": "关闭全屏编辑器",
"Open in Full Screen Editor": "在全屏编辑器中打开",
"Add Attributes": "添加属性",
"Press ALT-F10 for toolbar, and press ESC to exit toolbar once inside": "按 ALT-F10 可调用工具栏；按 ESC 可退出正在使用的工具栏",

// a11ychecker plugin
"Accessibility Checker": "可访问性检查器",
"Check Accessibility": "检查可访问性",
"No accessibility issues detected.": "未检测到可访问性问题。",
"Issue ": "图像 ",
" of ": " 的 ",
"Images must have alternative text.": "问题必须有替代文本。",
"Add alternative text:": "添加替代文本：",
"Text cannot be empty.": "文本不能为空。",
"Text cannot be the same as the filename.": "文本不能与文件名相同。",
"Alternative text must not be the same as the image filename.": "替代文本不得与图像文件名相同。",
"Tables must have captions.": "表必须有标题。",
"Set table caption:": "设置表标题：",
"Caption cannot be empty.": "标题不能为空。",
"Caption cannot be the same as the summary.": "标题不能与摘要相同。",
"Complex tables should have summaries.": "复杂表应有摘要。",
"Set table summary.": "设置表摘要。",
"Summary cannot be empty.": "摘要不能为空。",
"Table summary cannot be the same as table caption.": "表摘要不能与表标题相同。",
"Table caption and summary cannot have the same value.": "表标题和摘要不能有相同值。",
"Tables must contain rows and cells.": "表必须包含行和单元格。",
"Tables must have at least one header.": "表必须有至少一个标题。",
"Set table header:": "设置表标题：",
"Header Row": "标题行",
"Header Column": "标题列",
"Table headers must be associated with cells.": "表标题必须与单元格关联。",
"Set header scope:": "设置标题范围：",
"Row": "行",
"Column": "列",
"Row Group": "行组",
"Column Group": "列分组",
"Paragraph cannot be used in place of heading.": "段落不能代替标题使用。",
"Choose a heading level:": "选择标题级别",
"Heading 1": "标题 1",
"Heading 2": "标题 2",
"Heading 3": "标题 3",
"Heading 4": "标题 4",
"Heading 5": "标题 5",
"Heading 6": "标题 6",
"Heading order must be sequential.": "标题顺序必须连续。",
"Adjacent links should be merged.": "应合并临近链接。",
"Use list markup for lists.": "对列表使用列表标记。",
"Large text must have a contrast ratio of at least 3:1.": "大文本对比率必须达到至少 3:1。",
"Visual presentation must have a contrast ratio of at least 4.5:1.": "可视演示对比率必须达到至少 4.5:1。"
});
