//D2L specific strings

tinymce.addI18n('zh_CN',{
"Add Image": "添加图片",
"Insert Stuff": "插入资料",
"More Text Styles": "更多文本类型",
"More Insert Options": "更多插入选项",
"More Paragraph Formatting": "更多段落格式",
"Add Link": "添加链接",
"Graphical equation": "图形等式",
"Graphical": "图形",
"Chemistry equation": "化学反应式",
"MathML equation": "MathML 等式",
"MathML": "MathML",
"LaTeX equation": "LaTeX 等式",
"LaTeX": "LaTeX",
"equation preview image": "Equation 预览图像",
"Insert stuff placeholder": "插入内容占位符",
"Ordered List": "有序列表",
"Indent": "缩进",
"Outdent": "减少缩进",
"Align Full": "两端对齐",
"Address": "地址",
"Preformatted": "预设格式",
"HTML Source Editor": "HTML 源编辑器",
"Close Full Screen Editor": "关闭全屏编辑器",
"Open in Full Screen Editor": "在全屏编辑器中打开",
"Add Attributes": "添加属性",
"Press ALT-F10 for toolbar, and press ESC to exit toolbar once inside": "按 ALT-F10 可调用工具栏；按 ESC 可退出正在使用的工具栏",
"Emoticons": "表情符号",

// a11ychecker plugin
"Accessibility Checker": "可访问性检查器",
"Check Accessibility": "检查可访问性",
"No accessibility issues detected.": "未检测到可访问性问题。",
"Issue ": "图像 ",
" of ": " 的 ",
"Images must have alternative text.": "问题必须有替代文本。",
"Add alternative text:": "添加替代文本：",
"Text cannot be empty.": "文本不能为空。",
"Text cannot be the same as the filename.": "文本不能与文件名相同。",
"Alternative text must not be the same as the image filename.": "替代文本不得与图像文件名相同。",
"Tables must have captions.": "表必须有标题。",
"Set table caption:": "设置表标题：",
"Caption cannot be empty.": "标题不能为空。",
"Caption cannot be the same as the summary.": "标题不能与摘要相同。",
"Complex tables should have summaries.": "复杂表应有摘要。",
"Set table summary.": "设置表摘要。",
"Summary cannot be empty.": "摘要不能为空。",
"Table summary cannot be the same as table caption.": "表摘要不能与表标题相同。",
"Table caption and summary cannot have the same value.": "表标题和摘要不能有相同值。",
"Tables must contain rows and cells.": "表必须包含行和单元格。",
"Tables must have at least one header.": "表必须有至少一个标题。",
"Set table header:": "设置表标题：",
"Header Row": "标题行",
"Header Column": "标题列",
"Table headers must be associated with cells.": "表标题必须与单元格关联。",
"Set header scope:": "设置标题范围：",
"Row": "行",
"Column": "列",
"Row Group": "行组",
"Column Group": "列分组",
"Paragraph cannot be used in place of heading.": "段落不能代替标题使用。",
"Choose a heading level:": "选择标题级别",
"Heading 1": "标题 1",
"Heading 2": "标题 2",
"Heading 3": "标题 3",
"Heading 4": "标题 4",
"Heading 5": "标题 5",
"Heading 6": "标题 6",
"Heading order must be sequential.": "标题顺序必须连续。",
"Adjacent links should be merged.": "应合并临近链接。",
"Use list markup for lists.": "对列表使用列表标记。",
"Large text must have a contrast ratio of at least 3:1.": "大文本对比率必须达到至少 3:1。",
"Visual presentation must have a contrast ratio of at least 4.5:1.": "可视演示对比率必须达到至少 4.5:1。",
"Next": "下一步",
"Close": "关闭",

// d2l-emoticons plugin
"blue funster": "蓝色小丑",
"celebrate": "庆祝",
"heart": "心",
"red funster": "红色小丑",
"star": "星",
"sunshine": "阳光",

"blush with light skin tone": "脸红（浅肤色）",
"cool with light skin tone": "扮酷（浅肤色）",
"goofy with light skin tone": "傻傻的（浅肤色）",
"happy with light skin tone": "开心（浅肤色）",
"joy with light skin tone": "笑哭（浅肤色）",
"love eyes with light skin tone": "色（浅肤色）",
"star eyes with light skin tone": "星星眼（浅肤色）",
"thinking with light skin tone": "思考（浅肤色）",
"thumbs up with light skin tone": "强（浅肤色）",
"wink with light skin tone": "眨眼（浅肤色）",
"wow with light skin tone": "惊叹（浅肤色）",
"upside down with light skin tone": "倒立（浅肤色）",

"blush with dark skin tone": "脸红（深肤色）",
"cool with dark skin tone": "扮酷（深肤色）",
"goofy with dark skin tone": "傻傻的（深肤色）",
"happy with dark skin tone": "开心（深肤色）",
"joy with dark skin tone": "笑哭（深肤色）",
"love eyes with dark skin tone": "色（深肤色）",
"star eyes with dark skin tone": "星星眼（深肤色）",
"thinking with dark skin tone": "思考（深肤色）",
"thumbs up with dark skin tone": "强（深肤色）",
"wink with dark skin tone": "眨眼（深肤色）",
"wow with dark skin tone": "惊叹（深肤色）",
"upside down with dark skin tone": "倒立（深肤色）"
});
