//D2L specific strings

tinymce.addI18n('zh_TW',{
"Add Image": "新增影像",
"Insert Stuff": "插入媒體",
"More Text Styles": "更多文字樣式",
"More Insert Options": "更多插入選項",
"More Paragraph Formatting": "更多段落格式設定",
"Add Link": "新增連結",
"Graphical equation": "圖形方程式",
"Graphical": "圖形",
"Chemistry equation": "化學方程式",
"MathML equation": "MathML 方程式",
"MathML": "MathML",
"LaTeX equation": "LaTeX 方程式",
"LaTeX": "LaTeX",
"equation preview image": "方程式預覽影像",
"Insert stuff placeholder": "插入媒體預留位置",
"Ordered List": "已排序列表",
"Indent": "縮排",
"Outdent": "凸排",
"Align Full": "完整對齊",
"Address": "地址",
"Preformatted": "預設格式",
"HTML Source Editor": "HTML 原始檔編輯器",
"Close Full Screen Editor": "關閉全螢幕編輯器",
"Open in Full Screen Editor": "在全螢幕編輯器中開啟",
"Add Attributes": "新增屬性",
"Press ALT-F10 for toolbar, and press ESC to exit toolbar once inside": "按下 ALT-F10 可存取工具列，按下 ESC 可退出工具列",
"Emoticons": "表情符號",

// a11ychecker plugin
"Accessibility Checker": "協助工具檢查程式",
"Check Accessibility": "檢查協助工具",
"No accessibility issues detected.": "未偵測到協助工具問題。",
"Issue ": "問題 ",
" of ": " / ",
"Images must have alternative text.": "影像必須具有替代文字。",
"Add alternative text:": "新增替代文字：",
"Text cannot be empty.": "文字不可為空白。",
"Text cannot be the same as the filename.": "文字不能與檔名相同。",
"Alternative text must not be the same as the image filename.": "替代文字不得與影像檔名相同。",
"Tables must have captions.": "表格必須具有標題。",
"Set table caption:": "設定表格標題：",
"Caption cannot be empty.": "標題不可為空白。",
"Caption cannot be the same as the summary.": "標題不能與摘要相同。",
"Complex tables should have summaries.": "複雜的表格應具有摘要。",
"Set table summary.": "設定表格摘要。",
"Summary cannot be empty.": "摘要不可為空白。",
"Table summary cannot be the same as table caption.": "表格摘要不能與表格標題相同。",
"Table caption and summary cannot have the same value.": "表格標題和摘要不可具有相同的值。",
"Tables must contain rows and cells.": "表格必須包含列與儲存格。",
"Tables must have at least one header.": "表格必須具有至少一個標頭。",
"Set table header:": "設定表格標頭：",
"Header Row": "標頭列",
"Header Column": "標頭欄",
"Table headers must be associated with cells.": "表格標頭必須與儲存格相關聯。",
"Set header scope:": "設定標頭範圍：",
"Row": "列",
"Column": "欄",
"Row Group": "列群組",
"Column Group": "欄群組",
"Paragraph cannot be used in place of heading.": "段落不能用於取代標題。",
"Choose a heading level:": "選擇標題層級：",
"Heading 1": "標題 1",
"Heading 2": "標題 2",
"Heading 3": "標題 3",
"Heading 4": "標題 4",
"Heading 5": "標題 5",
"Heading 6": "標題 6",
"Heading order must be sequential.": "標題順序必須為循序。",
"Adjacent links should be merged.": "應合併相鄰連結。",
"Use list markup for lists.": "使用清單的清單標記。",
"Large text must have a contrast ratio of at least 3:1.": "大型文字必須具有至少 3:1 的對比率。",
"Visual presentation must have a contrast ratio of at least 4.5:1.": "視覺化簡報必須具有至少 4.5:1 的對比率。",
"Next": "下一個",
"Close": "關閉",

// d2l-emoticons plugin
"blue funster": "藍色淘氣鬼",
"celebrate": "慶祝",
"heart": "愛心",
"red funster": "紅色淘氣鬼",
"star": "星星",
"sunshine": "陽光",

"blush with light skin tone": "臉紅 (淺膚色)",
"cool with light skin tone": "酷 (淺膚色)",
"goofy with light skin tone": "諧趣 (淺膚色)",
"happy with light skin tone": "開心 (淺膚色)",
"joy with light skin tone": "樂壞了 (淺膚色)",
"love eyes with light skin tone": "眼冒愛心 (淺膚色)",
"star eyes with light skin tone": "眼神發亮 (淺膚色)",
"thinking with light skin tone": "思考中 (淺膚色)",
"thumbs up with light skin tone": "讚 (淺膚色)",
"wink with light skin tone": "眨眼 (淺膚色)",
"wow with light skin tone": "驚呆了 (淺膚色)",
"upside down with light skin tone": "上下顛倒 (淺膚色)",

"blush with dark skin tone": "臉紅 (深膚色)",
"cool with dark skin tone": "酷 (深膚色)",
"goofy with dark skin tone": "諧趣 (深膚色)",
"happy with dark skin tone": "開心 (深膚色)",
"joy with dark skin tone": "樂壞了 (深膚色)",
"love eyes with dark skin tone": "眼冒愛心 (深膚色)",
"star eyes with dark skin tone": "眼神發亮 (深膚色)",
"thinking with dark skin tone": "思考中 (深膚色)",
"thumbs up with dark skin tone": "讚 (深膚色)",
"wink with dark skin tone": "眨眼 (深膚色)",
"wow with dark skin tone": "驚呆了 (深膚色)",
"upside down with dark skin tone": "上下顛倒 (深膚色)"
});
